"""Dihedral-inequivalence certificate for window W (stdlib only).
Group generated by reverse / complement / inverse acting on (base, shaded cells).
Prints orbit canonical reps and asserts all 8 meshes pairwise inequivalent,
and classical 1324 vs 2143 dihedral orbits disjoint.
"""
import itertools

K = 4
B1324 = (0, 2, 1, 3)
B2143 = (1, 0, 3, 2)
W = [
    ("M0", B1324, frozenset({(0, 0)})),
    ("M1", B1324, frozenset({(0, 1)})),
    ("M2", B1324, frozenset({(1, 1)})),
    ("M3", B1324, frozenset({(2, 2)})),
    ("M4", B2143, frozenset({(0, 0)})),
    ("M5", B2143, frozenset({(0, 1)})),
    ("M6", B2143, frozenset({(1, 1)})),
    ("M7", B2143, frozenset({(2, 2)})),
]

def rev(p, cells):
    q = tuple(p[K - 1 - j] for j in range(K))
    return q, frozenset((K - c, r) for (c, r) in cells)

def comp(p, cells):
    q = tuple(K - 1 - x for x in p)
    return q, frozenset((c, K - r) for (c, r) in cells)

def inv(p, cells):
    q = [0] * K
    for j, x in enumerate(p):
        q[x] = j
    return tuple(q), frozenset((r, c) for (c, r) in cells)

def orbit(p, cells):
    seen = set()
    stack = [(p, cells)]
    while stack:
        cur = stack.pop()
        if cur in seen:
            continue
        seen.add(cur)
        for f in (rev, comp, inv):
            stack.append(f(*cur))
    return seen

def canon(p, cells):
    return min(orbit(p, cells))

if __name__ == "__main__":
    reps = {}
    for name, p, cells in W:
        reps[name] = canon(p, cells)
    # pairwise inequivalence
    vals = list(reps.values())
    assert len(set(vals)) == 8, "COLLISION in W dihedral orbits!"
    # base orbits disjoint
    o1 = set(q for (q, _) in orbit(B1324, frozenset()))
    o2 = set(q for (q, _) in orbit(B2143, frozenset()))
    assert o1.isdisjoint(o2), "base orbits overlap!"
    print("DIHEDRAL_OK: 8/8 pairwise inequivalent; base orbits disjoint")
    print("orbit sizes:", {n: len(orbit(p, c)) for n, p, c in W})
    print("1324 classical orbit:", sorted(o1))
    print("2143 classical orbit:", sorted(o2))
