from math import gcd

p = 11
k = 10
u = (2**k - 1) // p
v = (3**k - 1) // p
C = p**k - 1

assert (u, v) == (93, 5368)
assert gcd(u, v) == 1

F_T = u * v - u - v
g_T = (u - 1) * (v - 1) // 2
assert F_T == 493763
assert g_T == 246882

# Directly enumerate the two-generator semigroup through its Frobenius number.
reachable = bytearray(F_T + 1)
for x in range(F_T // u + 1):
    base = x * u
    for y in range((F_T - base) // v + 1):
        reachable[base + y * v] = 1

gaps = [n for n in range(1, F_T + 1) if not reachable[n]]
assert len(gaps) == g_T
assert max(gaps) == F_T

# The exceptional small quotient at m=4 is already generated by u.
q4 = (4**k - 1) // p
assert q4 == 1025 * u

# Every nonmultiple of 11 with m >= 5 has quotient above F(T).
q5 = (5**k - 1) // p
assert q5 == 887784
assert q5 > F_T

# C itself lies in T=<u,v>; this is used when reducing the C coefficient modulo 11.
xC, yC = 278893056, 69
assert C == xC * u + yC * v
assert C % p == p - 1

# Sanity check: the first 500 original generators lie in
# <11u,11v,C>, using the proof's two cases.
A, B = p * u, p * v

def in_T(n):
    if n < 0:
        return False
    # Solve n = u*x + v*y with 0 <= y < u.
    y = (n * pow(v, -1, u)) % u
    return n >= v * y

for m in range(1, 501):
    g = m**k - 1
    if m == 1:
        assert g == 0
    elif m % p:
        q = g // p
        assert g % p == 0
        assert in_T(q)
    else:
        r = m // p
        if r == 1:
            assert g == C
        else:
            q = p**9 * (r**k - 1)
            assert q > F_T and in_T(q)
            assert g == C + p * q

# Canonical-residue formulas for Gamma_10 = 11T + C*N_0.
floor_sum = sum((r * C) // p for r in range(1, p))
assert floor_sum == 5 * (C - 1)

a10 = 10 * C + p * F_T
b10 = p * g_T + floor_sum
assert a10 == 259379677393
assert b10 == 129689838697
assert a10 == 2 * b10 - 1

# Check symmetry of T directly; the proof transports it residue-by-residue to Gamma_10.
for z in range(F_T + 1):
    assert bool(reachable[z]) != bool(reachable[F_T - z])

paper_lower_bound = 129687123005
assert b10 - paper_lower_bound == 2715692

print(f"T=<93,5368>: F(T)={F_T}, g(T)={g_T}")
print(f"C=11^10-1={C}=93*{xC}+5368*{yC}")
print(f"Gamma_10=<1023,59048,{C}>")
print(f"a_10={a10}")
print(f"b_10={b10}")
print(f"2*b_10-1={2*b10-1}")
print(f"improvement over the published lower bound={b10-paper_lower_bound}")
print("finite generator sanity check: m=1..500 passed")
print("two-generator symmetry check through F(T) passed")
