#!/usr/bin/env python3
"""Truncated-polynomial ledger for the tacnode in characteristic 7.

Verifies, reproducibly and exactly:
  1. Ring identities: e1=(x^2+y)/2=(u^2,0), e2=(x^2-y)/2=(0,v^2) in B,
     m_A^2 = (x^2,xy,y^2) contained in I=(u^2)x(v^2).
  2. Unit group R^× of R=F7[eps]/eps^2 is cyclic C42, generator 3+3eps.
  3. Milnor K2^M(R) = C42/<log(a)log(1-a)> is trivial (gcd witness),
     and likewise K2^M(F7)=0 (the C6 block).
  4. Diagonal unit map R^× -> R^× x R^× is injective (trivial kernel).

Conventions: R element a+b*eps is the tuple (a,b) mod 7.
B elements mod (u^4,v^4) shown only for the exact polynomial identities
(which hold exactly, not just mod truncation).
"""
import math
import json

P = 7

def add(x, y):
    return ((x[0] + y[0]) % P, (x[1] + y[1]) % P)

def sub(x, y):
    return ((x[0] - y[0]) % P, (x[1] - y[1]) % P)

def mul(x, y):
    return ((x[0] * y[0]) % P, (x[0] * y[1] + x[1] * y[0]) % P)

def pw(x, n):
    r = (1, 0)
    b = x
    k = n
    while k:
        if k & 1:
            r = mul(r, b)
        b = mul(b, b)
        k >>= 1
    return r

# ---- 1. exact conductor identities (pairs of univariate polynomials) ----
# poly helpers: coeff lists, lowest degree first
def ptrim(f):
    f = list(f)
    while len(f) > 1 and f[-1] % P == 0:
        f.pop()
    return [a % P for a in f]

def padd(f, g):
    n = max(len(f), len(g))
    return ptrim([( (f[i] if i < len(f) else 0) + (g[i] if i < len(g) else 0)) % P
            for i in range(n)])

def pmul(f, g):
    h = [0] * (len(f) + len(g) - 1)
    for i, a in enumerate(f):
        for j, b in enumerate(g):
            h[i + j] = (h[i + j] + a * b) % P
    return h

def pscale(f, c):
    return [(c * a) % P for a in f]

INV2 = 4  # 2^{-1} mod 7
# x=(u,v), y=(u^2,-v^2); x^2=(u^2,v^2)
xu, xv = [0, 1], [0, 1]
yu, yv = [0, 0, 1], [0, 0, 6]  # -1 = 6 mod 7
x2u, x2v = pmul(xu, xu), pmul(xv, xv)
e1u = pscale(padd(x2u, yu), INV2)
e1v = pscale(padd(x2v, yv), INV2)
e2u = pscale(padd(x2u, pscale(yu, 6)), INV2)
e2v = pscale(padd(x2v, pscale(yv, 6)), INV2)
assert e1u == [0, 0, 1] and e1v == [0], "e1 == (u^2,0)"
assert e2u == [0] and e2v == [0, 0, 1], "e2 == (0,v^2)"
# m_A^2 generators inside I: x^2=(u^2,v^2), xy=(u^3,-v^3), y^2=(u^4,v^4)
xyu, xyv = pmul(xu, yu), pmul(xv, yv)
y2u, y2v = pmul(yu, yu), pmul(yv, yv)
assert x2u[0] == 0 and x2u[1] == 0 and x2v[0] == 0 and x2v[1] == 0
assert xyu[0] == 0 and xyu[1] == 0 and xyv[0] == 0 and xyv[1] == 0
assert y2u[0] == 0 and y2u[1] == 0 and y2v[0] == 0 and y2v[1] == 0
print("1. conductor identities: e1=(u^2,0), e2=(0,v^2), m_A^2 subset I: OK")

# ---- 2. unit group of R ----
units = [(a, b) for a in range(1, P) for b in range(P)]
assert len(units) == P * (P - 1)
unitset = set(units)
assert len(units) == 42
gamma = (3, 3)
assert pw(gamma, 42) == (1, 0), "gamma^42 = 1"
assert all(pw(gamma, k) != (1, 0) for k in range(1, 42)), "order exactly 42"
dlog = {}
for k in range(42):
    dlog[pw(gamma, k)] = k
assert len(dlog) == 42, "R^× cyclic of order 42 = C6 x C7"
print("2. R^× cyclic C42 generated by 3+3eps: OK")

# ---- 3a. Milnor K2^M(F7)=0 (C6 block) ----
# F7^× = <3>, discrete logs mod 6
flog = {pow(3, k, 7): k for k in range(6)}
assert len(flog) == 6
fvals = []
for a in range(2, 7):  # a and 1-a both nonzero units
    c = (1 - a) % 7
    if c != 0:
        fvals.append((flog[a] * flog[c]) % 6)
g = 0
for v in fvals:
    g = math.gcd(g, v)
assert math.gcd(g, 6) == 1, "field Steinberg relations generate C6 tensor"
print("3a. K2^M(F7)=0, field Steinberg gcd with 6 is 1: OK", fvals)

# ---- 3b. Milnor K2^M(R)=0 ----
# K2^M(R) = C42 / < v_a = log(a)log(1-a) : a,1-a units >.
one = (1, 0)
vals = []   # (a, log a, log(1-a), v)
for a in units:
    c = sub(one, a)
    if c in unitset:
        vals.append((a, dlog[a], dlog[c], (dlog[a] * dlog[c]) % 42))
assert len(vals) == 35, "42 units minus 7 with 1-a nonunit"
g = 0
for (_, _, _, v) in vals:
    g = math.gcd(g, v)
G = math.gcd(g, 42)
assert G == 1, "Steinberg values generate all of C42"
print("3b. K2^M(R)=0: %d Steinberg pairs, gcd(values,42)=1: OK" % len(vals))

# explicit Bezout witness: integers c_i with sum c_i v_i = 1 mod 42
def egcd_list(vs):
    # returns (g, coeffs) with sum coeffs[i]*vs[i] = g
    g = 0
    coeffs = [0] * len(vs)
    for i, v in enumerate(vs):
        if g == 0:
            g = v
            coeffs[i] = 1
        else:
            # combine g (with current coeffs) and v
            import math as m
            gg = m.gcd(g, v)
            # extended euclid for (g, v)
            def eg(a, b):
                if b == 0:
                    return (a, 1, 0)
                qq, rr = divmod(a, b)
                gg2, s, t = eg(b, rr)
                return (gg2, t, s - qq * t)
            _, s, t = eg(g, v)
            coeffs = [c * s for c in coeffs]
            coeffs[i] += t
            g = gg
    return g, coeffs

vs = [v for (_, _, _, v) in vals]
g2, coeffs = egcd_list(vs)
assert g2 == math.gcd(g, 0) or True
combo = sum(c * v for c, v in zip(coeffs, vs)) % 42
# g2 divides 42-group; rescale to witness 1 mod 42 via inverse of g2 mod 42 if coprime
assert math.gcd(g2, 42) == 1
inv = pow(g2, -1, 42)
w = [(c * inv) % 42 for c in coeffs]
assert sum(c * v for c, v in zip(w, vs)) % 42 == 1
terms = [(vals[i][0], vals[i][1], vals[i][2], vals[i][3], w[i])
         for i in range(len(vals)) if w[i] % 42 != 0]
print("    Bezout witness: sum c_a*log(a)log(1-a) = 1 mod 42 with %d nonzero terms" % len(terms))
for (a, la, lc, v, c) in terms[:12]:
    print("      a=%s log(a)=%d log(1-a)=%d v=%d coeff=%d" % (a, la, lc, v, c))

# ---- 4. diagonal unit injection ----
ker = [w for w in units if (w, w) == ((1, 0), (1, 0)) or w == (1, 0)]
assert all(ww == (1, 0) for ww in [w for w in units if (w, w) == ((1, 0), (1, 0))])
diag = {}
for w in units:
    diag.setdefault((w, w), []).append(w)
assert all(len(v) == 1 for v in diag.values()), "diagonal injective"
print("4. diagonal R^× -> R^× x R^× injective (|image|=42): OK")

out = {
    "ring": "R=F7[eps]/eps^2",
    "units_order": 42,
    "gamma_order": 42,
    "n_steinberg_pairs": len(vals),
    "gcd_steinberg_values_42": G,
    "field_block_gcd_with_6": 1,
    "diagonal_injective": True,
    "witness_terms": [
        {"a": list(a), "log_a": la, "log_1_minus_a": lc, "v": v, "coeff": c}
        for (a, la, lc, v, c) in terms
    ],
}
with open("output/artifacts/ledger.json", "w") as f:
    json.dump(out, f, indent=2)
print("wrote output/artifacts/ledger.json")
