# Independent verification of the separating homomorphism theta: G3 -> S4.
# Conventions: permutations on {0,1,2,3} applied left to right;
# compose(p,q)(i) = q(p(i)). Word R = A B^-1 A B C^2.
# Images: A = (2 3) [transposition], B = id, C = (0 1 2 3) [4-cycle].

def compose(p, q):
    return tuple(q[p[i]] for i in range(len(p)))

def invert(p):
    q = [0] * len(p)
    for i, v in enumerate(p):
        q[v] = i
    return tuple(q)

def pw(p, k):
    n = len(p)
    e = tuple(range(n))
    if k < 0:
        p, k = invert(p), -k
    r = e
    for _ in range(k):
        r = compose(r, p)
    return r

def order(p):
    e = tuple(range(len(p)))
    q = p
    m = 1
    while q != e:
        q = compose(q, p)
        m += 1
        assert m <= 25
    return m

A = (0, 1, 3, 2)   # transposition (2 3)
B = (0, 1, 2, 3)   # identity
C = (1, 2, 3, 0)   # 4-cycle (0 1 2 3)
E = (0, 1, 2, 3)

R = compose(compose(compose(compose(A, invert(B)), A), B), pw(C, 2))
print("R =", R, "| R^6 =", pw(R, 6), "== e:", pw(R, 6) == E,
      "=> theta extends to G3 = <a,b,c | R^6=1>")

u = pw(R, 3)          # theta(x), x = w3^3
v = compose(compose(A, u), invert(A))  # theta(y), y = a x a^-1
print("theta(x) = R^3 =", u, "order:", order(u))
print("theta(y) = A R^3 A^-1 =", v, "order:", order(v))
print("theta(x) != e:", u != E, "| theta(x) != theta(y):", u != v)

# Image size (subgroup of S4 generated by A,B,C) -- non-abelian check
gens = [A, B, C]
seen = {E}
stack = [E]
while stack:
    g = stack.pop()
    for h in gens:
        for k in (compose(g, h), compose(g, invert(h))):
            if k not in seen:
                seen.add(k)
                stack.append(k)
print("image order:", len(seen), "(= 24 means onto S4, so G3 non-abelian)")

# Cycle-structure cross-check of distinctness (0-based):
# R should be (0 2)(1 3); V should be (0 3)(1 2).
print("R == (0 2)(1 3):", R == (2, 3, 0, 1), "| V == (0 3)(1 2):", v == (3, 2, 1, 0))
