#!/usr/bin/env python3
"""Exact finite-group replay for the prism-quandle inner group and orbit group."""
from collections import deque, Counter
from math import gcd

# Quaternion group Q8 encoded as (sign, basis), basis 0=1,1=i,2=j,3=k.
# Multiplication table stores sign and basis for positive basis products.
TAB = {
    (0,0):(1,0),(0,1):(1,1),(0,2):(1,2),(0,3):(1,3),
    (1,0):(1,1),(1,1):(-1,0),(1,2):(1,3),(1,3):(-1,2),
    (2,0):(1,2),(2,1):(-1,3),(2,2):(-1,0),(2,3):(1,1),
    (3,0):(1,3),(3,1):(1,2),(3,2):(-1,1),(3,3):(-1,0),
}
Q8=[(s,b) for s in (1,-1) for b in range(4)]

def qmul(x,y):
    s1,b1=x; s2,b2=y
    s,b=TAB[(b1,b2)]
    return (s1*s2*s,b)

def qinv(x):
    for y in Q8:
        if qmul(x,y)==(1,0) and qmul(y,x)==(1,0): return y
    raise AssertionError

# alpha: i->j->k->i and fixes +/-1.
def alpha(x):
    s,b=x
    return (s,{0:0,1:2,2:3,3:1}[b])

def alphapow(x,k):
    for _ in range(k%3): x=alpha(x)
    return x

# Gamma=Q8 x C7.
G=[(q,a) for q in Q8 for a in range(7)]
e=((1,0),0)

def gmul(x,y): return (qmul(x[0],y[0]), (x[1]+y[1])%7)
def ginv(x): return (qinv(x[0]), (-x[1])%7)
def theta(x): return (alpha(x[0]), (-x[1])%7)
def thetapow(x,k):
    for _ in range(k%6): x=theta(x)
    return x

# P7 operation x*y=theta(x y^{-1}) y.
def op(x,y): return gmul(theta(gmul(x,ginv(y))), y)
idx={x:i for i,x in enumerate(G)}

def perm_comp(p,q):
    # p after q
    return tuple(p[q[i]] for i in range(len(q)))

def perm_inv(p):
    r=[0]*len(p)
    for i,j in enumerate(p): r[j]=i
    return tuple(r)

rights=[]
for y in G:
    rights.append(tuple(idx[op(x,y)] for x in G))

idp=tuple(range(len(G)))
# Generate Inn exactly from all right translations.
gens=list(dict.fromkeys(rights))
seen={idp}; dq=deque([idp])
while dq:
    a=dq.popleft()
    for g in gens:
        h=perm_comp(g,a)
        if h not in seen:
            seen.add(h); dq.append(h)
assert len(seen)==336

# permutation order
def lcm(a,b): return a//gcd(a,b)*b
def porder(p):
    vis=[False]*len(p); o=1
    for i in range(len(p)):
        if not vis[i]:
            j=i; n=0
            while not vis[j]:
                vis[j]=True; n+=1; j=p[j]
            o=lcm(o,n)
    return o
inn_orders=Counter(porder(p) for p in seen)
assert inn_orders[12]==0

# Identity stabilizer and displacement subgroup size.
ie=idx[e]
stab=sum(1 for p in seen if p[ie]==ie)
assert stab==6
S_e=rights[ie]
Se_inv=perm_inv(S_e)
disp_gens=[perm_comp(Sy,Se_inv) for Sy in rights]
seenD={idp}; dq=deque([idp])
while dq:
    a=dq.popleft()
    for g in disp_gens:
        h=perm_comp(g,a)
        if h not in seenD:
            seenD.add(h); dq.append(h)
assert len(seenD)==56

# Verify the split product model T* x D14 has the same order spectrum.
# T*=Q8 rt C3 under alpha; D14=C7 rt C2 under inversion.
T=[(q,r) for q in Q8 for r in range(3)]
D=[(a,s) for a in range(7) for s in range(2)]

def tmul(x,y):
    q,r=x; q2,r2=y
    return (qmul(q,alphapow(q2,r)), (r+r2)%3)
def dmul(x,y):
    a,s=x; b,t=y
    return ((a + (b if s==0 else -b))%7, (s+t)%2)

def order_elem(x,mul,identity,limit=100):
    y=identity
    for n in range(1,limit+1):
        y=mul(y,x)
        if y==identity:return n
    raise AssertionError

t_orders=Counter(order_elem(x,tmul,((1,0),0)) for x in T)
d_orders=Counter(order_elem(x,dmul,(0,0)) for x in D)
prod_orders=Counter()
for ot,ct in t_orders.items():
    for od,cd in d_orders.items(): prod_orders[lcm(ot,od)]+=ct*cd
assert sum(prod_orders.values())==336
assert prod_orders==inn_orders
assert prod_orders[12]==0

# Lambda as the twisted extension generated by Gamma and f, with f g f^-1=theta(g), f^6=z=(-1,0) in Q8.
z=((-1,0),0)
# canonical representatives (g,r), r in 0..5, with multiplication carry z when r+s>=6.
L=[(g,r) for g in G for r in range(6)]

def lmul(x,y):
    g,r=x; h,s=y
    hh=thetapow(h,r)
    u=r+s
    carry=u//6
    rr=u%6
    out=gmul(g,hh)
    if carry:
        out=gmul(out,z)
    return (out,rr)
Lid=(e,0)
f=(e,1)
assert len(L)==336
assert order_elem(f,lmul,Lid,limit=30)==12
lambda_orders=Counter(order_elem(x,lmul,Lid,limit=100) for x in L)
assert lambda_orders[12]>0
assert lambda_orders != inn_orders

print(
    'VERIFY_OK '
    f'quandle_size={len(G)} '
    f'inn_order={len(seen)} '
    f'displacement_order={len(seenD)} '
    f'identity_stabilizer={stab} '
    f'inn_order12={inn_orders[12]} '
    f'lambda_order={len(L)} '
    f'lambda_order12={lambda_orders[12]} '
    f'f_order={order_elem(f,lmul,Lid,limit=30)}'
)
