"""Attempt to decide the Loewy structure of the 5-factor summand U for p=3,k=7,j=3.
Strategy: use the homomorphisms alpha and gamma (Props 4.5, 4.7) to get submodule/quotient info,
as done in Prop 5.13(ii)-(iv) for j=2. Test whether they pin down U.

Setup: S((7e),(3e)) has summands: A = D^{T(2,1^8)}<3> (simple), U = rest (5 factors).
Submodule lattice constraints:
- alpha_{7,3}: S((8e),(2e)) -> S((7e),(3e)), degree 1. But S((8e),(2e)): k'=8,j'=2, n=10.
  For j'=2: divisibility among 10,9,8: p=3 divides 10? no, 9 yes, 8 no -> exactly ONE -> Thm 5.20 applies!
  So S((8e),(2e)) structure is KNOWN (almost-semisimple). Its image under alpha gives submodule info in S((7e),(3e)).
- gamma_{7,3}: S((7e,2e+1),(e-1)) -> S((7e),(3e)) degree 3 gives the D^{T(2^3,1^4)} factor (Prop 4.7).
- Also S((7e),(3e)) contains S((8e),(2e))? No wait: alpha maps S((ke+e),(je-e)) = S((8e),(2e)) into S((7e),(3e)).
  Actually ke+e = 8e, je-e = 2e. Yes.

Compute S((8e),(2e)) via Thm 5.19: n=10=3*3+1, i=1, j=2. Case (i)(a) i odd, i in {0,...,j-1}={0,1}: i=1 odd.
  Result: L_{(i+1)/2}=L_1 + sum_{r=0}^{floor(1/2)=0} N_r + sum_{m=3..2} (empty).
  N_0 = L_{0}|L_{1}|L_{0} (since floor(1/2)=0, ceil(1/2)=1: N_0 = L_0 | L_1 | L_0).
  So Delta(1^8)xDelta(1^2) = L(2,1^8) + (L(1^10)|L(2,1^8)|L(1^10)).
  Under T-map: D^T(2,1^8)<2> simple summand + (D^T(1^10)|D^T(2,1^8)|D^T(1^10))<2>.
  So S((8e),(2e)) = D((8e+? ...)) simple + uniserial of length 3.
  Image im(alpha) inside S((7e),(3e)): alpha is degree 1, so shifts: <2> -> <3>. Head of im must be D((10e),0)<3>?
  In Prop 5.13(ii) they showed alpha injective when dim im >1 via leading-term argument. Can we show injectivity here?
  If alpha injective, then U contains a uniserial submodule L0|L1'|... hmm but L(2,1^8) is in the OTHER block, so
  the length-3 uniserial (in block {L0,L2?,...}) -- wait for n=10 the Weyl modules for S((8e),(2e)) involve m=0,1,2:
    D0=L(1^10), D1=L(2,1^8), D2=L(2^2,1^6). Block of D1 = {L1} separate; block of D0,D2: D2 = L0|L2.
  So the length-3 piece is L0|L2'|... no: N_0 = L_0|L_1|L_0 mixes BLOCKS?! L_1 is in a different block than L_0!
  Contradiction? N_0 = L_{floor(i/2)-r} | L_{ceil(i/2)+1+r} | ... with i=1: floor=0, ceil=1: N_0 = L_0 | L_2 | L_0.
  (Using Lx shorthand Lx = L(2^x,1^{n-2x}).) So N_0 = L(1^10)|L(2^2,1^6)|L(1^10). Same block {L0,L2,L3}. Good - I misread.
  So S((8e),(2e)) = L(2,1^8)-simple + (L0|L2|L0 uniserial).
  im(alpha) then has head D^T(1^10)<3> = D((10e),0)<3> and is a submodule of U (since D((10e),0) in U's block).
  U has socle...? If alpha injective, U contains submodule with head L0. Both configs A and B have socle containing L0? 
  Config A socle = L(2^2,1^6) only. So injectivity of alpha would RULE OUT config A independently!
  And MSS's Donkin argument also rules out A. Consistent.
  But does it distinguish further (e.g. uniserial options)? im(alpha) uniserial L0|L2|L0 of length 3 inside U (5 factors).
  Quotient U/im(alpha) would have factors L2, L3 (2 factors): L(2^2,1^6), L(2^3,1^4) with extension L2|L3 (=D3 head).
  Hmm: U/im: contains D3 = L2|L3 as quotient (head L3). Self-duality of U constrains...
  Let's see: if im(alpha) = L0|L2|L0 (submodule), and U self-dual with head containing L0+L2...
  Config B: does it contain L0|L2|L0 as submodule? Config B socle = L0+L2 (two socle factors). Submodule L0|L2|L0?
  The left vertical edge L(1^10)(bottom) -- L(2^2,1^6)(top): that's length 2. Plus chain top L2 -> L3 -> bottom-right L2.
  Hmm, config B restricted: submodule generated by top L2? top L2 connects to bottom L0 (left edge) and to L3 (middle).
  So submodule generated by top L2 = whole module (since it connects to both). Not uniserial.
  This is getting complicated without pictures. The point: alpha-injectivity gives a concrete submodule that
  candidate structures must contain; checking config B contains it requires the actual diagram.
  KEY COMPUTATION: is alpha_{7,3} injective? The paper's Prop 5.13(ii) injectivity argument used explicit
  leading-term coefficient analysis (psi_e kills leading term, other coeffs k,...,1 some nonzero mod p).
  For (7,3): alpha(z) = sum_{i=0}^7 (8-i) Psi^{7+i-1}_{3}... downward? Coeffs 8,7,...,1. p=3: coeffs mod 3: 2,1,0,2,1,0,2,1.
  Some zero, some nonzero - same as before, dim im >1 plausible. But injectivity needs: im has simple head D((10e),0)<3>
  and is submodule of the length-? module. Since S((8e),(2e)) has TWO summands (simple + length-3), alpha could kill
  the simple summand (different block) - that's fine, restriction to the length-3 piece: is it injective on that piece?
  The head of the length-3 piece is L0 = D((10e),0). If alpha kills the head, im would be smaller.
  Leading-term analysis: leading term (k+1)z = 8z; 8 mod 3 = 2 != 0, so leading term SURVIVES (psi_e kills it? in j=2 case
  psi_e killed leading term; here the brick structure differs). Cannot conclude without the full KLR computation.
  This is exactly the 'bounded recovery test': try to push the alpha/gamma route; it requires a full KLR basis
  computation in S((7e),(3e)) (dimension = binomial(30, 3e)? huge) - infeasible by hand, and no computer KLR package
  available in this environment. So the Loewy decision is BLOCKED on computation, not on theory.
"""
print("analysis recorded")
# Summand count for the auxiliary S((8e),(2e)) in char 3:
def leq_p(a,b,p):
    def padic(n):
        d=[]
        if n==0: return [0]
        while n>0: d.append(n%p); n//=p
        return d
    da,db=padic(a),padic(b); L=max(len(da),len(db)); da+=[0]*(L-len(da)); db+=[0]*(L-len(db))
    return all(x<=y for x,y in zip(da,db))
print("M(8,2),n=10,p=3 summands:", [(m,leq_p(2-m,10-2*m,3)) for m in range(3)], "count=",sum(leq_p(2-m,10-2*m,3) for m in range(3)))
