"""Generalize: the REAL question. C4 looks prime-plausible. But target claims for ALL 2-connected
(2-vertex-connected: G-v connected forall v) graphs. Need to hunt for counterexample among larger graphs.

Key structural insight attempt: V(I_{n-1}) = rank<=n-2 locus, parametrized by U ((n-2) x n) with zero-constraints
X_ij = u_i . u_j = 0 for nonedges ij. Zero set Z in A^{(n-2)n} cut by (#nonedges) quadrics. If Z is irreducible
(and char 0 symmetric diagonalization surjects onto rank<=n-2 locus), then V irreducible. Then primality = radicality.

For C4: constraints decouple (disjoint vars) => Z = product => irreducible. For general G? Constraints couple.
E.g. n=5, G=C5: constraints u1u3+v1v3+w1w3=0 (3 vectors u,v,w since n-2=3), 5 constraints sharing vars. Is Z irreducible?
A complete intersection of 5 quadrics in A^15... could be reducible!

But WAIT — more dangerous: the map may have fibers/degeneracies, or V may have components of different dims.
Alternative counterexample route: find graph G 2-connected where V has TWO components, e.g. where rank<=n-2 locus
splits. Hmm.

Actually, think about n=5, G = K5 minus a matching? Or consider graphs where some (n-1)-minor is IDENTICALLY ZERO
as polynomial! If some 3x3... for n=5, deleting row i col j leaves 4x4 sparse matrix; its det may vanish identically
for sparsity reasons (e.g., a zero row/col in the submatrix: if vertex i has degree... deleting row i: column k in submatrix
is zero if k's only neighbor... hmm). If MANY minors vanish identically, I is generated by few polys, variety large,
maybe reducible.

KEY EXAMPLE hunt: n=4, G = "paw"? 2-connectedness for n=4 requires G-v connected for all v: C4, diamond (K4-e), K4 qualify;
paw fails? paw = triangle + pendant: removing the triangle-vertex adjacent to pendant disconnects. Star fails, path fails.
So n=4 tests: C4 (done: looks irreducible, radical TBD), diamond, K4 (classical prime).

n=5: 2-connected graphs include C5, K5, wheels, etc. Let me test C5 computationally: 5 diag + 5 edge vars = 10 vars,
25 minors of size 4 (15 distinct up to symmetry: 5 diag-deletions + 10 off-diag... (5x5 sym: 15 distinct)). Degree-4 polys.
Grevlex GB in 10 vars might be heavy but let's try.

Also diamond n=4 first (9 vars).
"""
import sympy as sp

def sparse_sym(n, edges, diag_syms, edge_syms):
    M = sp.zeros(n)
    for i in range(n):
        M[i, i] = diag_syms[i]
    for (i, j), s in zip(edges, edge_syms):
        M[i, j] = s
        M[j, i] = s
    return M

def minors_n_1(M, n):
    gens = {}
    for di in range(n):
        for dj in range(di, n):
            rr = [x for x in range(n) if x != di]
            cc = [x for x in range(n) if x != dj]
            gens[(di, dj)] = sp.expand(M.extract(rr, cc).det())
    return gens

# Diamond: K4 minus edge 13 (1-indexed): vertices 0..3, edges all but (0,2).
a,b,c,d,p,q,r,s,t = sp.symbols('a b c d p q r s t')
# edges: 01:p, 03:s? let's: 01,02? no. Diamond: missing edge (0,2). edges: 01,03,12,23,13(i.e.1,3).
diag = [a,b,c,d]
edges = [(0,1),(0,3),(1,2),(2,3),(1,3)]
esyms = [p,s,q,r,t]
M = sparse_sym(4, edges, diag, esyms)
g = minors_n_1(M, 4)
print("=== Diamond n=4 ===")
nident = 0
for k, v in g.items():
    flag = "IDENTICALLY ZERO" if v == 0 else ""
    if v == 0: nident += 1
    print(f"M_{k}: {str(v)[:160]} {flag}")
print("identically zero count:", nident)
