from itertools import product

IRREDUCIBLE = {
    1: 0b11,       # x + 1
    2: 0b111,      # x^2 + x + 1
    3: 0b1011,     # x^3 + x + 1
    4: 0b10011,    # x^4 + x + 1
}

def fadd(a, b):
    return a ^ b

def fmul(a, b, m, poly):
    out = 0
    while b:
        if b & 1:
            out ^= a
        b >>= 1
        a <<= 1
        if a & (1 << m):
            a ^= poly
    return out & ((1 << m) - 1)

def mul(g, h, m, poly):
    a, b, c = g
    x, y, z = h
    return (
        fadd(a, x),
        fadd(b, y),
        fadd(fadd(c, z), fmul(a, y, m, poly)),
    )

def inv(g, m, poly):
    a, b, c = g
    return (a, b, fadd(c, fmul(a, b, m, poly)))

def comm(g, h, m, poly):
    return mul(mul(mul(inv(g, m, poly), inv(h, m, poly), m, poly), g, m, poly), h, m, poly)

def order(g, m, poly):
    z = (0, 0, 0)
    if g == z:
        return 1
    x = z
    for k in range(1, 9):
        x = mul(x, g, m, poly)
        if x == z:
            return k
    raise AssertionError('order bound exceeded')

def check(m):
    poly = IRREDUCIBLE[m]
    q = 1 << m
    elems = list(product(range(q), repeat=3))
    zero = (0, 0, 0)

    # Basic inverse and associativity spot-exhaustion against coordinate basis families.
    for g in elems:
        assert mul(g, inv(g, m, poly), m, poly) == zero
        assert mul(inv(g, m, poly), g, m, poly) == zero

    counts = {1: 0, 2: 0, 4: 0}
    psi = 0
    for g in elems:
        o = order(g, m, poly)
        assert o in counts
        counts[o] += 1
        psi += o

    want2 = 2*q*q - q - 1
    want4 = q*(q-1)*(q-1)
    wantpsi = 4*q**3 - 4*q**2 + 2*q - 1
    assert counts == {1: 1, 2: want2, 4: want4}
    assert psi == wantpsi

    # The central-coordinate subgroup is generated by commutators and by squares.
    center = {(0, 0, c) for c in range(q)}
    comm_values = {
        comm((t, 0, 0), (0, 1, 0), m, poly)
        for t in range(q)
    }
    square_values = {
        mul((t, 1, 0), (t, 1, 0), m, poly)
        for t in range(q)
    }
    assert comm_values == center
    assert square_values == center

    # Commutation with the two coordinate directions detects the center exactly.
    detected = set()
    x = (1, 0, 0)
    y = (0, 1, 0)
    for g in elems:
        if mul(g, x, m, poly) == mul(x, g, m, poly) and mul(g, y, m, poly) == mul(y, g, m, poly):
            detected.add(g)
    assert detected == center

    row = (q, counts[2], counts[4], psi)
    print(row)
    return row

rows = [check(m) for m in (1, 2, 3, 4)]
assert rows == [
    (2, 5, 2, 19),
    (4, 27, 36, 199),
    (8, 119, 392, 1807),
    (16, 495, 3600, 15391),
]
print('VERIFY_OK')
