"""Core exact toolkit for lane-154 (stdlib only).
S1: exact semigroup invariants by sieve on membership array.
Conventions for E(Gamma):
  q = ceil(c/m); nu = q*m - c.
  Jq window: [c, c+m] inclusive both ends -> len m+1   (E_incl)
           or [c, c+m-1] inclusive -> len m            (E_excl)
  es = # minimal gens < c; ec = # minimal gens >= c  (per Eliahou's partition,
       gens in Jq window counted in ec).
  E = es*delta - q*|dq| + nu, dq = window minus generator points in it.
S2 decides which matches Almiron-Moyano Table 1 row 1: E=-1 for <100,170,171,176>_599.
"""
from math import gcd


def in_sg_sieve(gens, N):
    """membership bitmask is_sg[0..N], assuming all ints >= some bound handled by caller."""
    is_sg = bytearray(b"\x00") * (N + 1)
    is_sg[0] = 1
    for x in range(1, N + 1):
        for g in gens:
            if g <= x and is_sg[x - g]:
                is_sg[x] = 1
                break
    return is_sg


def minimal_gens(gens, is_sg=None, N=None):
    """Reduce generating set to minimal one (drop redundant)."""
    gens = sorted(set(gens))
    mg = []
    covered = bytearray(b"\x00") * (max(gens) * 2 + 1) if gens else bytearray(b"\x01")
    # simple: g is redundant iff in semigroup generated by smaller kept ones
    kept = []
    for g in gens:
        # check membership in <kept>
        if not kept:
            kept.append(g)
            continue
        # sieve up to g with kept
        mem = bytearray(b"\x00") * (g + 1)
        mem[0] = 1
        for x in range(1, g + 1):
            for h in kept:
                if h <= x and mem[x - h]:
                    mem[x] = 1
                    break
        if mem[g]:
            continue  # redundant
        kept.append(g)
    return kept


def semigroup_stats(gens, N=None):
    """Exact stats: assumes conductor <= N-2*max(gens). Returns dict."""
    gens = sorted(set(gens))
    if N is None:
        N = max(gens) * 8 + 5000
    while True:
        is_sg = in_sg_sieve(gens, N)
        # find conductor: largest gap + 1
        gaps = [x for x in range(N + 1) if not is_sg[x]]
        # check tail fully in sg beyond N - 2*maxg
        tail = range(N - 2 * max(gens), N + 1)
        if not all(is_sg[x] for x in tail):
            N *= 2
            continue
        F = max(gaps) if gaps else -1
        c = F + 1
        g = len([x for x in gaps if x < c])
        delta = len([x for x in range(c) if is_sg[x]])
        m = gens[0]
        mg = minimal_gens(gens)
        e = len(mg)
        # concentration: max gap between consecutive sg elements below... use elements < c + m
        sg = [x for x in range(c + m + 1) if is_sg[x]]
        conc = max(b - a for a, b in zip(sg, sg[1:]))
        # Eliahou pieces
        q = -(-c // m)
        nu = q * m - c
        es = sum(1 for x in mg if x < c)
        ec = sum(1 for x in mg if x >= c)
        res = dict(gens=mg, c=c, F=F, g=g, delta=delta, m=m, e=e, conc=conc,
                   q=q, nu=nu, es=es, ec=ec, Wilf=e * delta - c)
        # E inclusive [c, c+m]
        for tag, mlen in (("incl", m + 1), ("excl", m)):
            win = set(range(c, c + mlen))
            pq = win.intersection(mg)
            dq = len(win) - len(pq)
            E = es * delta - q * dq + nu
            res["E_" + tag] = E
            res["dq_" + tag] = dq
        return res
