from collections import Counter

def vp_order_vec(v, p, a):
    m = p ** a
    if v == (0, 0):
        return 1
    def ord_coord(x):
        if x % m == 0:
            return 1
        z = x % m
        val = 0
        while z % p == 0:
            val += 1
            z //= p
        return p ** (a - val)
    o1 = ord_coord(v[0])
    o2 = ord_coord(v[1])
    return max(o1, o2)

def add(x, y, m):
    return ((x[0] + y[0]) % m, (x[1] + y[1]) % m)

def neg(x, m):
    return ((-x[0]) % m, (-x[1]) % m)

def adjacent(x, y, m):
    return (x[0] * y[1] - x[1] * y[0]) % m == 0

def maximal_cliques(vertices, adj_masks):
    n = len(vertices)
    allmask = (1 << n) - 1
    out = []

    def bits(mask):
        while mask:
            b = mask & -mask
            yield b.bit_length() - 1
            mask ^= b

    def bronk(R, P, X):
        if P == 0 and X == 0:
            out.append(R)
            return
        union = P | X
        if union:
            # pivot maximizing neighbors in P
            u = max(bits(union), key=lambda i: (adj_masks[i] & P).bit_count())
            cand = P & ~adj_masks[u] & allmask
        else:
            cand = P
        while cand:
            b = cand & -cand
            v = b.bit_length() - 1
            bronk(R | b, P & adj_masks[v], X & adj_masks[v])
            P ^= b
            X |= b
            cand ^= b

    bronk(0, allmask, 0)
    return out

def is_subgroup(S, m):
    S = set(S)
    if (0,0) not in S:
        return False
    for x in S:
        if neg(x,m) not in S:
            return False
        for y in S:
            if add(x,y,m) not in S:
                return False
    return True

def type_k(S, p, a):
    exponent = max(vp_order_vec(v,p,a) for v in S)
    t = 0
    z = exponent
    while z > 1:
        assert z % p == 0
        t += 1
        z //= p
    # largest cyclic factor has order p^(a-k)
    k = a - t
    return k

def expected_type_counts(p, a):
    c = Counter()
    for k in range((a // 2) + 1):
        if 2*k < a:
            c[k] = p ** (a - 2*k - 1) * (p + 1)
        elif 2*k == a:
            c[k] = 1
    return c

def verify_case(p, a):
    m = p ** a
    V = [(x,y) for x in range(m) for y in range(m)]
    idx = {v:i for i,v in enumerate(V)}
    n = len(V)
    masks = [0] * n
    for i,x in enumerate(V):
        mask = 0
        for j,y in enumerate(V):
            if i != j and adjacent(x,y,m):
                mask |= 1 << j
        masks[i] = mask

    cliques = maximal_cliques(V, masks)
    max_size = max(c.bit_count() for c in cliques)
    assert max_size == m, (p,a,max_size,m)

    max_cliques = [c for c in cliques if c.bit_count() == max_size]
    expected_total = (p ** (a+1) - 1) // (p - 1)
    assert len(max_cliques) == expected_total, (p,a,len(max_cliques),expected_total)

    tc = Counter()
    seen = set()
    for mask in max_cliques:
        S = tuple(V[i] for i in range(n) if (mask >> i) & 1)
        fs = frozenset(S)
        assert fs not in seen
        seen.add(fs)
        assert len(S) == m
        assert is_subgroup(S,m), (p,a,S)
        # edge check
        for i,x in enumerate(S):
            for y in S[i+1:]:
                assert adjacent(x,y,m)
        tc[type_k(S,p,a)] += 1

    assert tc == expected_type_counts(p,a), (p,a,tc,expected_type_counts(p,a))

    # Every directly enumerated subgroup generated by two vectors with order m
    # and cardinality m appears among the maximum cliques.
    # Generate closures for all pairs.
    subgroups = set()
    z = (0,0)
    for x in V:
        for y in V:
            H = set()
            for u in range(m):
                ux = ((u*x[0]) % m, (u*x[1]) % m)
                for v in range(m):
                    H.add(((ux[0] + v*y[0]) % m, (ux[1] + v*y[1]) % m))
            if len(H) == m:
                subgroups.add(frozenset(H))
    assert subgroups == seen, (p,a,len(subgroups),len(seen))

for case in [(2,1),(2,2),(2,3),(3,1),(3,2)]:
    verify_case(*case)

print("VERIFY_OK")
