# Key structural observation for RELATIVE disproof:
# The peripheral structure (set of 2-ended edge groups incident to rigid vertex, up to conjugacy in the RIGID group R)
# has an incidence nerve that recovers the wheel graph. If relative QI preserves enough of this nerve, W5 vs W6 differ.
# But making "nerve is a relative QI invariant" rigorous from scratch is heavy.
# Alternative rigorous lever: the RIGID GROUPS THEMSELVES have different (absolute) QI-relevant data? No: virtually F5 vs F6, both QI F2.
# Another lever: GROWTH of the pair? Same.
# Reconsider the target reading once more:
#  "must W_Gamma and W_Lambda be quasi-isometric when every rigid vertex stabilizer is regarded together with its incident two-ended peripheral subgroups
#   (equivalently, after matching the JSJ trees, are the corresponding rigid vertex pairs relatively quasi-isometric)?"
# Parse: "must [the groups] be QI when [we assume] every rigid vertex stabilizer is regarded together with peripherals, i.e. are matched rigid pairs relatively QI?"
# Two readings:
#  (b1) CONCLUSION = "the matched rigid pairs are relatively QI" (assumption = tree iso). Disproof needs same-tree pair with non-relative-QI rigid pairs.
#  (a) CONCLUSION = "the groups are QI" (assumptions = tree iso + relative QI of rigid pairs). This is Cashen-Martin Thm 3.9 style and likely TRUE.
# Title: "Relative quasi-isometric rigidity for rigid JSJ pieces" + fingerprint "quasi-isometric rigidity classification theorem" + method "CAT(0) cubical boundary rigidity and divergence" suggests the CLAIM is a positive rigidity theorem: tree iso + peripheral data => QI (or rigid pieces are relatively rigid). I.e. reading (a): a classification theorem.
# Under reading (a), the target is plausibly PROVABLE by assembling Cashen-Martin [14] Thm 3.9 (QI tree / tree of QIs from matching JSJ + relative QIs of rigid vertices) + Dani-Thomas visual JSJ + Papasoglu QI-invariance of splittings. The "proof" would be a synthesis, not new computation. But is it within reach to make rigorous + original? It risks being a mere corollary of Cashen-Martin, i.e. NOT original (Admission supposedly reviewed originality; but we must not overclaim).
# Under reading (b1), need planar counterexample; wheels tie on crude invariants; deeper work needed.
# Which reading is right? "must W and W' be QI when every rigid vertex stabilizer is regarded together with its incident peripherals" -- "when" = "given that we also assume relative QI of rigid pairs". Then parenthetical "equivalently, ... are the corresponding rigid vertex pairs relatively QI?" -- hmm, that parenthetical instead equates the whole question to whether rigid pairs are relatively QI. That reads like: the claim under test is precisely "tree iso => rigid pairs relatively QI". I.e. (b1).
# Actually maybe the intended claim: "type-preserving iso of JSJ trees IMPLIES the groups are QI (and in particular rigid pairs are relatively QI)" -- a completeness claim for the tree in the planar case (extending Dani-Thomas Thm 1.4 beyond no-subdiv-K4 to planar-with-K4?). Dani-Thomas Thm 1.4: no subdiv K4 => tree complete. App B: with subdiv K_{n+1} (nonplanar) => tree NOT complete. Target: restrict to PLANAR (subdiv K4 allowed, K5+ impossible planar? subdiv K5 nonplanar) => is tree complete again? That's a sharp, natural question! "Planar + no K5-subdivision => does JSJ tree become complete?" 
# Under THIS reading (completeness for planar class), wheels W5 vs W6 are both planar WITH subdiv K4, same tree shape (?) but are the GROUPS QI or not? If W5-wheel group is NOT QI to W6-wheel group, target (completeness) is FALSE. If they ARE QI (like App B(2): same-n subdivisions are QI; but here n differs 5,6...), unknown.
# Are W5 and W6 wheel RACG groups QI? Global invariants: both 1-ended hyperbolic, same JSJ shape, rigid R6 vs R7. By symmetry with App B(3), expect NOT QI (distinguished via rigid line patterns). But App B(3)'s invariant (min cut size n) ties here (3,3). Hmm, but App B(3) distinguishes different n via min-cut SIZE; our wheels have same "local" K4-structure size (both built from K4 pieces?) so that invariant can't separate. Maybe wheels W5,W6 actually ARE QI?! Via Behrstock-Neumann "fattened tree" flexibility: the JSJ tree + hanging pieces determine QI, and rigid stars with same local branch geometry are QI (as in App B(2): different subdivisions of SAME K_{n+1} are QI despite different branch lengths!). 
# By analogy: W5 vs W6 differ in the NUMBER of branches (5 vs 6 rim), like K4 (6 branches among 4 vertices) vs K5 (10 branches). App B(3) says K4-subdiv vs K5-subdiv NOT QI. So W5 vs W6 (different combinatorics) should also be NOT QI -- but need an invariant that sees 5 vs 6. The Whitehead min-cut failed. What sees 5 vs 6?
# IDEA: the rigid group's peripheral PATTERN QUOTIENT: number of R-orbits... not QI invariant per se. 
# IDEA: L2-Betti numbers of the PAIR? b1^{(2)}(F_n) = n-1: 4 vs 5! But L2-Betti is absolute (F5 vs F6 differ: 4 vs 5) yet F5 QI F6 -- so L2-Betti NOT QI invariant for these? L2-Betti numbers are QI invariants for... they are NOT QI invariants in general (only under mild conditions? Actually L2-Betti numbers ARE QI invariants among... no: F2 vs F3 have different L2 Betti (1 vs 2) but are QI! Correct, not invariant). Dead end.
# IDEA: Use the GROUP's divergence or thickness? Both wheels: hyperbolic? C4-free => hyperbolic RACG (Moussong). Hyperbolic groups have exponential divergence -- ties.
# IDEA: Boundary homeomorphism type? Both boundaries: Menger curve? Sierpinski carpet? For RACGs with planar nerve, boundary... If boundaries differ (e.g. carpet vs Menger), groups not QI. Wheel graphs contain K4 subdivisions; Swiatkowski's results on Coxeter boundaries (Sierpinski carpet). Both wheels likely same boundary type. Tie probably.
# IDEA: JSJ tree of cylinders + Cashen-Martin STRUCTURE INVARIANT (the "stretch factors"/"decoration" refining tree iso)? Edletzberger refined structure invariant is complete when NO rigid vertices. With rigid vertices, the invariant includes rigid vertex data. The structure invariant might distinguish W5/W6 via the rigid vertex's "relative" data (number of incident edge orbits up to... ). But is the structure invariant a QI invariant that goes beyond tree iso? Yes! Cashen-Martin structure invariant = tree + decorations (valences, densities...). If W5/W6 have same bare tree but different DECORATIONS, then target (bare tree => QI) is false AND we don't even need relative-QI of pairs: the groups aren't QI, period. But computing decorations requires the full Cashen-Martin machinery.
# Time check: this is getting deep. Given the 30-min gate, the responsible move may be: request target exit with concrete obstacle (relative-QI distinguishing invariant for planar rigid pairs unresolved; both obvious invariants tie), attempted routes documented, recovery test = the Whitehead computation + JSJ orbit computation. But wait -- exit requires "blocked" with concrete evidence. We have partial progress, not yet a proof of blocked. The gate opens at 30 min; we can continue target after? "continue TARGET only when a concrete credible route remains". Hmm.
print("note done")
