# Whitehead min EDGE-cut gives 3 for both wheels -- not distinguishing. But Cashen-Macura's invariant is finer:
# the decomposition space's minimal cut sets AND their orbit structure / number of complementary components / stabilizer data.
# Also relative QI must preserve the pattern up to... F5 vs F6: ranks differ! A relative QI of pairs (R6, periph) -> (R7, periph)
# induces QI of finite-index free groups F5 -> F6 preserving line patterns. F5 vs F6 are QI, but the PATTERNS differ:
# pattern has 10 lines (5+5) vs 12 lines (6+6). Deeper invariants: e.g. the "line pattern" growth / density? Or the rigid vertex valence data?
# Alternative simpler distinguishing invariant for the PAIRS: the number of peripheral subgroups up to R-conjugacy!
# R_Gamma = <h,r0..r4>: peripheral subgroups = R-conjugates of D_{h,ri} (5 classes? or 1 orbit?) Hmm: under R (not full W), the 5 spoke dihedrals: are they R-conjugate? R acts transitively? The reflection group R = (Z/2)^6 acts on... the dihedral <h,r_i> vs <h,r_j>: conjugate via r_i r_j? (r_i r_j)<h,r_i>(r_i r_j)^{-1} = <r_i r_j h r_j r_i, r_i>. Is that <h,r_j>? r_i r_j h r_j r_i is a reflection (conjugate of h) but not equal to h generally. In the free subgroup F, lines are F-conjugates. The NUMBER of F-orbits of lines: spoke lines {y_i}: y_i vs y_j conjugate in F? y_i = h r_i, y_j = h r_j: f y_i f^{-1} = y_j? In free group, y_i, y_j are basis elements, not conjugate. So 5 distinct F-orbits + rim adjacencies: y_i^{-1}y_j for C5 edges: (i,j)~? cyclically symmetric: all 5 in one F-orbit? Under rotation automorphism (not inner!). F-orbits: y_i^{-1}y_j conjugate to y_k^{-1}y_l iff...? As cyclic words, all length-2 words of form y^{-1}y' with distinct basis elements: conjugacy in F: y_i^{-1}y_j ~ y_k^{-1}y_l iff same cyclic word up to rotation/inversion: y_i^{-1}y_j vs y_k^{-1}y_l: equal as cyclic words iff {i,j}={k,l} with orientation... y_i^{-1} y_j rotated: y_j y_i^{-1} (different word). Inverse: y_j^{-1} y_i. So (i,j) with C5 adjacency: 5 directed edges (undirected 5); each undirected edge gives line (unoriented cyclic: {y_i^{-1}y_j, y_j^{-1}y_i}?). Hmm the dihedral D_{ri,rj} gives cyclic <ri rj> = <y_i^{-1} y_j>, one line per undirected edge. Conjugacy classes in F: 5 spoke classes + rim classes: y_i^{-1}y_j ~ y_k^{-1}y_l iff (k,l) is a rotation of (i,j) by inner action? Inner action can't rotate basis indices (rotation is outer automorphism, not inner). So each of the 5 rim edges gives a DISTINCT F-conjugacy class?! Wait no: f (y_0^{-1} y_1) f^{-1} = y_2^{-1} y_3? That would require mapping basis... free group conjugacy: cyclically reduced words conjugate iff cyclic rotations. y_0^{-1}y_1 rotations: y_0^{-1}y_1, y_1 y_0^{-1}. Inverses: y_1^{-1} y_0, y_0 y_1^{-1}. None equals y_2^{-1}y_3. So indeed distinct classes. Total F-orbits: 5 + 5 = 10 for W5; 6 + 6 = 12 for W6.
# But relative QI does NOT require bijection of conjugacy classes; it coarsely respects the PATTERN (union of lines). The Cashen-Macura invariant (decomposition space cut sets) is the right tool, but min edge-cut tied at 3.
# Hmm. However: maybe count minimal cut sets / their structure differs. Or use a different pair of planar graphs where ranks differ more dramatically AND patterns differ structurally.
# Better idea: use "subdivided K4" (rigid R4, 6 peripheral pairs ALL pairs) vs "subdivided wheel W5" (rigid R6, 10 peripherals, sparse pattern)? But then JSJ trees differ (different V1 orbit counts: K4 subdiv has ONE branch type (all branches symmetric under S4) => 1 V1 orbit; wheel has 2 V1 orbits => trees NOT type-isomorphic). Bad.
# Alternative: keep wheels W5 vs W6 (same tree shape) and find finer relative invariant. Options:
#  (a) Rank itself: F5 vs F6 -- but free groups of different rank ARE QI, so rank isn't QI invariant. However RELATIVE QI of (F_n, pattern) might still force... no direct contradiction from rank alone.
#  (b) Number of F-orbits of lines (10 vs 12)? Not a relative-QI invariant in general (QI can merge/split orbits? No -- a pattern-preserving QI induces bijection on... actually a QI of pairs need not induce bijection on conjugacy classes; it maps lines to within bounded distance of lines, inducing homeomorphism of decomposition spaces. The decomposition space remembers the pattern quotient. Distinguishing 10-class vs 12-class patterns via decomposition space topology: the minimal finite cut sets' structure (how many, sizes, complementary components) may differ.
#  (c) Simpler: Bowditch boundary / JSJ of the RIGID group itself? R is virtually free; its boundary is Cantor set; peripheral lines give pairs. The decomposition space D = partial(F)/~ collapsing each line's endpoint pair. For patterns from different wheels, D differs. Cashen-Macura: D's topology + cut sets. Computing full D invariant is heavy.
#  (d) EASIEST RIGOROUS ROUTE: Papasoglu-Whyte + diameter? No.
#  (e) Use Euler characteristic / L2-Betti / cost? R6=(Z/2)^6 vs R7=(Z/2)^7: both virtually free; QI invariant? Virtually free groups: QI classified by... all (Z/2)^*n (n>=2?) Hmm: (Z/2)*(Z/2) = D_inf (2-ended) vs (Z/2)^3+ (virtually free, infinitely ended). Among infinitely-ended virtually free groups, QI classification: Mosher-Sageev-Whyte: determined by... the "number of ends of pairs"? For virtually free groups, QI type determined by the homeomorphism type of boundary + ... Actually all (Z/2)^{*n}, n>=3? They have Cantor set boundaries; are they all QI? Free groups F_k all QI (k>=2). (Z/2)^{*n} virtually F_{n-1}... wait (Z/2)^{*n} has index-2 subgroup free of rank n-1. So R6 virtually F5, R7 virtually F6, both QI to F2. So absolute QI doesn't distinguish. Must use RELATIVE (pattern) data. 
#  (f) The peripheral structure's "intersection graph" / nerve: for R6, nerve of peripheral cosets? The pattern of 10 dihedrals in R6: nerve = wheel W5 (the original graph restricted to B!). For R7: wheel W6. A relative QI induces QI of the "coset intersection complex"? There's a known invariant: the "nerve" of the peripheral structure up to QI (Behrstock-Drutu-Mosher thickness / "network"?). Hmm.
#  (g) CLEANEST: divergence of the pair? Or: attach "hanging" data? No hangings here.
#  (h) RECONSIDER: maybe choose planar pair where rigid groups are NOT even absolutely QI! E.g. rigid group virtually free (wheels) vs rigid group with different geometry? But planar rigid stars B all give (Z/2)^*|B| (virtually free). To get non-virtually-free rigid, need B containing... <B> for B essential set: all generators order 2, no edges within B? In wheels, B = essentials, no two adjacent? h adjacent to none in B (spoke interiors separate), rim adjacents separated by interiors => B independent set => <B> = free product of Z/2s. Always virtually free for "3-convex" graphs. So absolute QI never distinguishes planar 3-convex rigid groups. Relative pattern is the only lever.
#  (i) STRONGEST AVAILABLE: Cashen-Macura line-pattern rigidity (used in App B): the decomposition space + Whitehead min-cut analysis. For wheels, min edge-cut tied (3,3). Need finer: the STRUCTURE of minimal cut sets. In App B K_{n+1}: min cut sets size n of two types (vertex-incident vs positive-inverse bipartition). For wheels W5: min cuts size 3: which? Let's enumerate them and compare W5 vs W6 minimal-cut-set orbit structures. If the minimal-cut-set combinatorics differ (e.g. number of min cuts, or complementary component counts), that distinguishes the patterns relatively.
# Let's enumerate all min edge-cuts (size 3) for both Whitehead graphs and analyze.
print("analysis note written")
