"""Verify S structure: action, associativity sample, centre, Frattini, abelian maximals, Omega1, sections."""
import numpy as np, json, itertools, hashlib
E = np.load("output/artifacts/elems.npy")
MT = np.load("output/artifacts/multable.npy")
N=1024
def mul(a,b): return int(MT[a,b])
def tup(n): return tuple(E[n].tolist())
e = 0  # identity (0,0,0,0,0)
# check identity index
assert tup(0)==(0,0,0,0,0)
# element orders / sanity: closure+identity+inverse via table check
# inverses
INV = np.zeros(N,dtype=np.int32)
row0 = MT[0,:]
# MT[0,n] should be n
assert (row0 == np.arange(N)).all(), "left identity fails"
col0 = MT[:,0]
assert (col0 == np.arange(N)).all(), "right identity fails"
for n in range(N):
    # find inverse: MT[n,m]==0
    m = int(np.where(MT[n,:]==0)[0][0])
    INV[n]=m
print("identity+inverses OK")
# associativity: full check would be 1024^3; do random sample + generator-based check
rng = np.random.default_rng(0)
for t in range(20000):
    a,b,c = rng.integers(0,N,3)
    assert mul(mul(a,b),c)==mul(a,mul(b,c)), (a,b,c)
print("associativity sample 20000 OK")
# also full associativity on generators set implies all? do larger sample 100k quickly
for t in range(100000):
    a,b,c = rng.integers(0,N,3)
    assert mul(mul(a,b),c)==mul(a,mul(b,c))
print("associativity sample 100k OK")

# generators: r=(1,0,0,0,0), s=(0,1,0,0,0), t=(0,0,1,0,0), u=(0,0,0,1,0), v=(0,0,0,0,1)
idx = {tuple(e):n for n,e in enumerate(map(tuple,E.tolist()))}
r=idx[(1,0,0,0,0)]; s=idx[(0,1,0,0,0)]; tt=idx[(0,0,1,0,0)]; u=idx[(0,0,0,1,0)]; v=idx[(0,0,0,0,1)]
def pw(n,k):
    x=0
    for _ in range(k): x=mul(x,n)
    return x
def order(n):
    x=n; k=1
    while x!=0:
        x=mul(x,n); k+=1
        assert k<=2048
    return k
print("orders r,s,t,u,v:", order(r),order(s),order(tt),order(u),order(v))
assert order(r)==8 and order(s)==8 and order(tt)==4 and order(u)==2 and order(v)==2
# action checks: u r u = r^-1 etc. conjugation: u*r*u^{-1} since u order 2, u^-1=u
uru = mul(mul(u,r),u); rinv=INV[r]
assert uru==rinv, (tup(uru),tup(rinv))
usu = mul(mul(u,s),u); assert tup(usu)==(0,3,0,0,0), tup(usu)
utu = mul(mul(u,tt),u); assert tup(utu)==(0,0,3,0,0), tup(utu)
vrv = mul(mul(v,r),v); assert tup(vrv)==(5,0,0,0,0), tup(vrv)
vsv = mul(mul(v,s),v); assert tup(vsv)==(0,7,0,0,0), tup(vsv)
vtv = mul(mul(v,tt),v); assert vtv==tt
# u,v commute
assert mul(u,v)==mul(v,u)
# u,v involutory automorphisms commute: check u v = v u as maps already; check action matrices commute
print("action relations OK")
# Centre: elements commuting with all generators
gens=[r,s,tt,u,v]
Z=[n for n in range(N) if all(mul(n,g)==mul(g,n) for g in gens)]
print("|Z|=",len(Z))
# Frattini: Phi = S^2 [S,S]; compute squares and commutators subgroup
S2={mul(n,n) for n in range(N)}
def comm(a,b): return mul(mul(mul(a,b),INV[a]),INV[b])
C={comm(a,b) for a in range(N) for b in gens}  # enough: commutators with gens generate [S,S] mod? use all pairs sample
# full commutator subgroup: use all pairs (1M) fine
Call={comm(a,b) for a in range(N) for b in range(N)}
print("num squares distinct:",len(S2),"num commutators distinct:",len(Call))
# subgroup generated by S2 union Call: BFS closure
gen=set(S2)|Call
# BFS
H={0}
stack=[0]
genlist=list(gen)
# closure under mul/inv
frontier=[0]
seen={0}
while frontier:
    nxt=[]
    for h in frontier:
        for g in genlist:
            for x in (mul(h,g),mul(g,h)):
                if x not in seen:
                    seen.add(x); nxt.append(x)
    frontier=nxt
Phi=seen
print("|Phi|=",len(Phi),"quotient rank =", end=" ")
import math
q=N//len(Phi)
rk=int(round(math.log2(q)))
print(q, "=> rank", rk)
assert N%len(Phi)==0
# list quotient: check elementary abelian
for n in range(N):
    assert mul(n,n) in Phi  # squares in Phi
print("S/Phi elementary abelian check: squares in Phi OK")
# minimal generators = rank
# Centre description
print("centre elts:", [tup(n) for n in Z][:20])
# Omega1(A): A = <r,s,t> = indices with a=b=0
A=[n for n in range(N) if E[n,3]==0 and E[n,4]==0]
print("|A|=",len(A))
Om=[n for n in A if mul(n,n)==0]
print("|Omega1(A)|=",len(Om))
# check Omega1(A) elementary abelian
for a in Om:
    for b in Om:
        assert mul(a,b) in Om and mul(a,b)==mul(b,a)
print("Omega1(A) elementary abelian OK; elts:",[tup(n) for n in Om])
# V centralizes Omega1(A)?
for w in Om:
    assert mul(u,w)==mul(w,u) and mul(v,w)==mul(w,v)
print("V centralizes Omega1(A) OK => C2^5 section Omega1(A)x<u,v>? check intersection")
U=[0,u,v,mul(u,v)]
inter=set(Om)&set(U)
print("intersection Om cap <u,v>:",inter)
# maximal subgroups: index 2 = kernels of 5 nonzero linear functionals on S/Phi if rank 5
# find Phi cosets and homomorphisms: pick representatives mapping to F2^rk
# Build quotient vector encoding: find 5 elements whose images form basis
# Use linear algebra over F2 via BFS: compute images by expressing each elt as word? Easier: compute abelianization-free approach:
# S/Phi as group: coset mult. Get coset reps via orbit of Phi action.
cosets={}
crep=[]
cn=np.full(N,-1)
for n in range(N):
    # find rep: min of {mul(n,h): h in Phi}? O(N*|Phi|) = 1024*32 fine
    c=min(mul(n,h) for h in Phi)
    if c not in cosets:
        cosets[c]=len(crep); crep.append(c)
    cn[n]=cosets[c]
print("num cosets:",len(crep))
# quotient mul
Q=len(crep)
QM=np.zeros((Q,Q),dtype=int)
for a in range(Q):
    for b in range(Q):
        QM[a,b]=cn[mul(crep[a],crep[b])]
# check abelian + exponent 2
assert all(QM[a,b]==QM[b,a] for a in range(Q) for b in range(Q))
assert all(QM[a,a]==cn[0] for a in range(Q))
print("quotient is elementary abelian C2^",rk)
# abelian maximal check: the rk... maximal subgroups containing Phi correspond to hyperplanes; plus any maximal must contain Phi. So 2^rk-1 maximals? No: number of index-2 subgroups = 2^rk - 1 = 31.
# enumerate: kernels of nonzero linear maps F2^rk -> F2. Need coordinates: find basis images.
# find iso: pick gens images, do gaussian elimination to assign coords
# get images of r,s,t,u,v
def qimg(n): return cn[n]
# build matrix rows = images as vectors unknown; instead construct homomorphisms directly:
# homomorphisms S -> C2 classified by maps on generators satisfying relations mod Phi? Simpler: since S/Phi = F2-vector space with known mult table QM, enumerate all homomorphisms Q->C2 by brute force over linear maps: pick basis of Q.
# find basis: greedy
basis=[]
span={cn[0]}
def add_span(g):
    global span
    new=set(span)
    for h in list(span):
        new.add(QM[h,g])
    span=new
for a in range(Q):
    if a not in span:
        basis.append(a)
        g=a
        new=set(span)
        for h in list(span):
            new.add(QM[h,g])
        span=new
print("basis size:",len(basis))
# coordinates of each elt
coords={}
for a in range(Q):
    # solve a = sum c_i basis[i]: brute force 32
    for mask in range(1<<len(basis)):
        x=cn[0]
        for i in range(len(basis)):
            if mask>>i &1: x=QM[x,basis[i]]
        if x==a:
            coords[a]=mask; break
# 31 hyperplanes: each nonzero functional f(mask)=dot(w,mask)
maximals=[]
for w in range(1,1<<len(basis)):
    ker=[n for n in range(N) if bin(coords[cn[n]]&w).count("1")%2==0]
    maximals.append(ker)
print("num maximals:",len(maximals))
# check each maximal nonabelian
def is_abelian(sub):
    Sset=set(sub)
    for a in sub:
        for b in sub:
            if mul(a,b)!=mul(b,a): return False
    return True
ab=[M for M in maximals if is_abelian(M)]
print("abelian maximals:",len(ab))
# also A overgroups: A has index 4; its three index-2 overgroups
# A cosets in S: reps 0,u,v,uv
# overgroups: A+Au, A+Av, A+Auv
Aset=set(A)
Au=[mul(a,u) for a in A]; Av=[mul(a,v) for a in A]; Auv=[mul(a,mul(u,v)) for a in A]
M1=sorted(Aset|set(Au)); M2=sorted(Aset|set(Av)); M3=sorted(Aset|set(Auv))
print("overgroup sizes:",len(M1),len(M2),len(M3))
print("M1 abelian?",is_abelian(M1),"M2 abelian?",is_abelian(M2),"M3 abelian?",is_abelian(M3))
# sectional rank: exhibit C2^5 section: Omega1(A)xV /? check E = Om*U subgroup
EU={mul(x,y) for x in Om for y in U}
print("|Om*U|=",len(EU))
# check subgroup & elementary abelian
ok=all(mul(x,x)==0 for x in EU)
print("Om*U exponent<=2:",ok,"abelian:",is_abelian(sorted(EU)))
# direct product?
print("Om cap U:",inter,"=> section order",len(EU))
out={"|Z|":len(Z),"|Phi|":len(Phi),"frattini_rank":rk,"num_maximals":len(maximals),
 "abelian_maximals":len(ab),"|Omega1(A)|":len(Om),"|OmU|":len(EU),
 "M_overgroups_abelian":[is_abelian(M1),is_abelian(M2),is_abelian(M3)],
 "centre_sample":[tup(n) for n in Z]}
json.dump(out,open("output/artifacts/S_invariants.json","w"),indent=1)
print(json.dumps(out,indent=1))
