import itertools
from math import comb
def C(n,r): return comb(n,r) if 0<=r<=n else 0

# How many graphs on 12 vertices with color-class sizes (3,3,3,3), complete multipartite minus extra edges... all Delta graphs contain K_{3,3,3,3} minus? No: Delta graph CONTAINS all cross edges? Every facet is rainbow, but a cross pair {u,v} (different colors) need not be an edge (edge = contained in some facet). So Delta graph is a SUBGRAPH of K_{n1,...,nd}, missing cross edges too.
# Gamma graph: K_{3,3,3,3} minus 24-? Gamma f1=42 of 66 possible. K_{3333} has 54 edges. So Gamma graph = K_{3333} minus 12 cross edges.
# Key: beta_{i,i+1} via W-sum. For each W, comp(G[W])-1. Adding edges decreases it. No clean comparison since neither graph contains the other.
# Best route to upper bound: for each W, comp-1 <= (#mono pairs in W capped?) Actually comp(G[W])-1 <= max(0, (#color classes meeting W with... )) hmm.
# Simple universal bound: comp(G[W])-1 <= sum_j C(|W cap V_j|, 2)? No: each extra component beyond first needs >= 1 missing adjacency... Standard: comp-1 <= number of missing edges? comp(G[W])-1 <= C(|W|,2)-e(G[W]). Summing: beta_{i,i+1} <= C(n,2)-f1 times C(n-2,i-1)? Because each missing edge {a,b} lies in C(n-2,|W|-2) sets W. So beta_{i,i+1} <= m*C(n-2,i-1) where m = #missing edges.
# For Gamma d=4,k=3: m=24. Bound: 24*C(10,i-1). i=1: 24 ok equality. i=2: 24*10=240 vs formula 80. Too weak (factor 3). Because one W with t components counted t-1 but has >= t-1 missing... actually >= C(t,2)? Components pairwise nonadjacent: missing edges >= sum_{p<q} |Cp||Cq| >= C(t,2). And comp-1 = t-1 <= C(t,2) for t>=2 with equality only t=2. So beta <= m*C(n-2,i-1) with slack from t>=3 sets. For UPPER bound vs Gamma need better.
# Balanced structure: missing MONO edges are forced (C(nj,2) each, total 12 for 3333). Missing CROSS edges: Gamma misses 12, Delta misses >= 0 (could be 0! e.g., joins have full cross edges... join C6*C6 graph = K_{3,3,3,3} complete multipartite: f1=54 > Gamma 42).
# So Delta graphs can have MORE edges than Gamma (joins!) yet formula still holds there. The extremality is genuinely about distribution, not edge count. The missing-edge bound m*C(n-2,i-1) would give joins (m=12) beta <= 12*C(10,i-1): i=2 -> 120 vs actual 32. Very loose.
# Refined: count per W: comp(G[W])-1. For W with vertices in >=2 colors and full cross edges (multipartite), components arise only from... complete multipartite induced subgraph is connected unless W is mono. So joins get contributions ONLY from mono W: sum_j C(nj,i+1)... for 3333,i=2: 4*C(3,3)=4?? but actual beta_23=32. So cross W DO contribute: W with 2 colors where one side... e.g. W={a1,a2,b1}: cross edges present a1b1,a2b1 -> connected. Hmm then why 32? W with vertices in 2 colors, sizes (2,1): connected. (3,1)? connected. So which W disconnected? Only mono W (4 of size 3: C(3,3)=1 each -> 4)?? Actual is 32. So my strand code must be counting non-multipartite... wait join graph IS complete multipartite. Let me recheck: nbr built from facets: facet = edge1+edge2 = quad; graph edges = all pairs within quad INCLUDING mono pairs?! a1,a2 from same cycle edge have different colors (cycle alternating) so no mono edges... but pair (a1,a2) same edge different colors: edge in graph. Cross pairs: (a from E1, c from E2): in same facet -> edge. So graph = full K_{3,3,3,3}? f1 = 54-12=... K_{3333} edges = (144-36)/2=54. All cross pairs appear? (a,c): a in some cycle edge, c in some cycle edge -> facet contains both -> yes edge. So graph complete multipartite, f1=54. Then beta_23 should be 4 (mono triples)? But computed 32. Contradiction -> BUG in strand? comp(G[W])-1 for W mono triple: G[W] has NO edges -> 3 components -> contributes 2, not 1! Right: tilde H0 dim = comp-1 = 2. So mono triples contribute 4*2=8, still not 32. W of size 4 with (2,2) split across 2 colors: K_{2,2} connected. (3,1): connected. (2,1,1): connected. Mono size-4? C(3,4)=0. Hmm 32-8=24 more from where? W size 4, colors (2,2) same... let me just debug: enumerate contributing W.
