from math import isqrt

def prime(n):
    if n < 2:
        return False
    for q in range(2, isqrt(n) + 1):
        if n % q == 0:
            return False
    return True

def factors(n):
    out = []
    q = 2
    while q * q <= n:
        if n % q == 0:
            out.append(q)
            while n % q == 0:
                n //= q
        q += 1
    if n > 1:
        out.append(n)
    return out

def nonsquare(p):
    for d in range(2, p):
        if pow(d, (p - 1) // 2, p) == p - 1:
            return d
    raise AssertionError("no nonsquare")

def mul(x, y, p, d):
    a, b = x
    c, e = y
    return ((a*c + b*e*d) % p, (a*e + b*c) % p)

def power(x, n, p, d):
    r = (1, 0)
    while n:
        if n & 1:
            r = mul(r, x, p, d)
        x = mul(x, x, p, d)
        n //= 2
    return r

def primitive(p, d):
    n = p*p - 1
    fs = factors(n)
    for a in range(p):
        for b in range(p):
            if (a, b) == (0, 0):
                continue
            x = (a, b)
            if all(power(x, n // q, p, d) != (1, 0) for q in fs):
                return x
    raise AssertionError("no primitive element")

def trace(x, p):
    # In F_p[a]/(a^2-d) with d nonsquare, a^p=-a, so Tr(A+B*a)=2A.
    return (2 * x[0]) % p

def check(p, m):
    assert prime(p) and p % 2 == 1
    assert m >= 4 and (p + 1) % m == 0 and m < p + 1
    d = nonsquare(p)
    g = primitive(p, d)
    qminus1 = p*p - 1
    hsize = qminus1 // m
    H = {power(g, m*j, p, d) for j in range(hsize)}
    assert len(H) == hsize

    # Prime-field multiplicative group is generated by g^(p+1).
    Fpstar = {(a, 0) for a in range(1, p)}
    assert Fpstar <= H

    quotient_size = (p + 1) // m
    assert len(H) // len(Fpstar) == quotient_size
    assert quotient_size >= 2
    eligible_nontrivial_characters = quotient_size - 1
    assert eligible_nontrivial_characters >= 1

    # Representatives of H/F_p^* and K^*/H.
    line_reps = [power(g, m*t, p, d) for t in range(quotient_size)]
    orbit_reps = [power(g, j, p, d) for j in range(m)]

    # For each nonzero H-orbit zH, count projective lines with zero trace.
    # Exactly one H-orbit contains the unique trace-zero projective line.
    zero_line_counts = []
    for z in orbit_reps:
        count = 0
        for t in line_reps:
            if trace(mul(z, t, p, d), p) == 0:
                count += 1
        zero_line_counts.append(count)
    assert sorted(zero_line_counts) == [0] * (m - 1) + [1]
    distinguished = zero_line_counts.index(1)

    # Matrix support: entry (row,column) is nonzero exactly when
    # the product orbit equals the distinguished orbit.
    support = []
    for row in range(m):
        row_support = []
        for col in range(m):
            row_support.append((row + col) % m == distinguished)
        support.append(row_support)
    assert all(sum(row) == 1 for row in support)
    assert all(sum(support[r][c] for r in range(m)) == 1 for c in range(m))
    assert sum(sum(row) for row in support) == m
    assert m*m - sum(sum(row) for row in support) == m*m - m

    # Exact projective-line additive sums used in the proof:
    # p-1 on the zero-trace line, -1 otherwise.
    assert (p - 1) - (-1) == p
    return (p, m, quotient_size, eligible_nontrivial_characters, distinguished)

cases = []
for p in (7, 11, 19, 23, 31, 43, 47, 59):
    for m in range(4, p + 1):
        if (p + 1) % m == 0 and m < p + 1:
            cases.append(check(p, m))

assert len(cases) >= 20
print("VERIFY_OK")
