"""Exact apolarity engine over QQ for binomial Macaulay duals (divided-power action)."""
from fractions import Fraction
from itertools import product as iproduct

def mons(nvars, deg):
    if nvars == 1:
        return [(deg,)]
    out = []
    def rec(k, rem, cur):
        if k == nvars - 1:
            out.append(tuple(cur + [rem])); return
        for e in range(rem + 1):
            rec(k + 1, rem - e, cur + [e])
    rec(0, deg, [])
    return out

def contract(f, F):
    """f in S acts on F in dual: f o F, both dicts exp->coeff(Fraction). Returns dict."""
    out = {}
    for a, ca in f.items():
        for b, cb in F.items():
            if all(bb >= aa for aa, bb in zip(a, b)):
                e = tuple(bb - aa for aa, bb in zip(a, b))
                out[e] = out.get(e, Fraction(0)) + ca * cb
    return {e: c for e, c in out.items() if c != 0}

def ann_basis(F, nvars, deg_f, deg_F):
    """Basis of Ann(F)_deg_f as list of coeff-vectors over monomials of degree deg_f."""
    import numpy as np
    from fractions import Fraction
    src = mons(nvars, deg_f)
    tgt = mons(nvars, deg_F - deg_f) if deg_F >= deg_f else []
    if not tgt:
        return [None] * len(src), src  # everything annihilates
    # matrix M[t, s] = coeff: (x^s o X^{...}) — build via contraction of basis elts
    import sympy as sp
    M = sp.zeros(len(tgt), len(src))
    Fkeys = list(F.keys())
    for j, s in enumerate(src):
        for b, cb in F.items():
            if all(bb >= ss for ss, bb in zip(s, b)):
                e = tuple(bb - ss for ss, bb in zip(s, b))
                i = tgt.index(e)
                M[i, j] += cb
    ns = M.nullspace()
    return ns, src

def ann_gens_binomial(u, v, nvars=4, maxdeg=None):
    """Return dict deg->list of polys (dict exp->Fraction) generating Ann(X^u-X^v) up to maxdeg."""
    F = {tuple(u): Fraction(1), tuple(v): Fraction(-1)}
    d = sum(u)
    if maxdeg is None:
        maxdeg = d + 1
    out = {}
    for deg in range(1, maxdeg + 1):
        ns, src = ann_basis(F, nvars, deg, d)
        polys = []
        for vec in ns:
            p = {s: vec[j] for j, s in enumerate(src) if vec[j] != 0}
            if p:
                polys.append(p)
        out[deg] = polys
    return out

def poly_str(p, varnames=('x','y','z','w')):
    ts = []
    for e in sorted(p):
        c = p[e]
        m = '*'.join(f"{varnames[i]}^{e[i]}" if e[i] > 1 else varnames[i] for i in range(len(e)) if e[i])
        m = m or '1'
        ts.append(f"({c})*{m}")
    return ' + '.join(ts) or '0'

def min_gens_of_ideal(gens_by_deg, nvars=4):
    """Greedy minimal generating set: keep polys not in ideal generated by previous kept ones (via simple normal-form check on monomial multiples)."""
    # Represent ideal membership test by linear algebra: f in (G) iff f = sum g*h with deg h = deg f - deg g.
    kept = []
    for deg in sorted(gens_by_deg):
        for p in gens_by_deg[deg]:
            if not in_ideal(p, kept, nvars):
                kept.append((deg, p))
    return kept

def _mul_space(G, nvars, deg):
    """All monomial multiples of G landing in degree deg."""
    out = []
    for dg, g in G:
        if dg > deg:
            continue
        for m in mons(nvars, deg - dg):
            q = {}
            for e, c in g.items():
                ne = tuple(a + b for a, b in zip(e, m))
                q[ne] = q.get(ne, Fraction(0)) + c
            out.append(q)
    return out

def in_ideal(p, G, nvars):
    import sympy as sp
    deg = max(sum(e) for e in p)
    space = _mul_space(G, nvars, deg)
    if not space:
        return False
    keys = sorted(set().union(*[set(q) for q in space], set(p)))
    M = sp.zeros(len(keys), len(space))
    for j, q in enumerate(space):
        for e, c in q.items():
            M[keys.index(e), j] = c
    b = sp.Matrix([p.get(e, Fraction(0)) for e in keys])
    aug = M.row_join(b)
    return M.rank() == aug.rank()
