import sys
sys.path.insert(0,'output/artifacts')
from klproof2 import C, INTERVAL, LEN, KEYS, kseen, N
from collections import defaultdict
# mu(x,w) for x<w: coeff of q^{(m-1)/2}, m=lw-lx (0 if m even)
def Ppoly(x,w):
    cx=C[w].get(x,{})
    sh={k+LEN[w]:v for k,v in cx.items()}
    return {k//2:v for k,v in sh.items()}
def mu(x,w):
    if x==w: return 0
    if x not in INTERVAL.get(w,set()): return 0
    m=LEN[w]-LEN[x]
    if m%2==0: return 0
    return Ppoly(x,w).get((m-1)//2,0)
# check nontrivial mus
pairs=[(x,w,mu(x,w)) for w in INTERVAL for x in INTERVAL[w] if mu(x,w)!=0]
print("num mu-pairs:",len(pairs))
from collections import Counter
print(Counter(m for _,_,m in pairs))
for x,w,m in pairs[:40]:
    print(f"mu({kseen[KEYS[x]]},{kseen[KEYS[w]]})={m}")
# W-graph: left descent sets; edges x--w if mu!=0 either direction and descL differ appropriately.
# descents: left descent D_L(w)={s: l(sw)<l(w)}; need left mult. Build left mult from group law.
from kl import E,S1,S2,Sth,THV
def mm(A,B): return ((A[0][0]*B[0][0]+A[0][1]*B[1][0], A[0][0]*B[0][1]+A[0][1]*B[1][1]),(A[1][0]*B[0][0]+A[1][1]*B[1][0], A[1][0]*B[0][1]+A[1][1]*B[1][1]))
def mv(A,v): return (A[0][0]*v[0]+A[0][1]*v[1], A[1][0]*v[0]+A[1][1]*v[1])
def va(u,v): return (u[0]+v[0],u[1]+v[1])
MID=((E(1),E(0)),(E(0),E(1))); ZV=(E(0),E(0))
GENS=[(Sth,THV),(S1,ZV),(S2,ZV)]
def compose(g,h): return (mm(g[0],h[0]), va(mv(g[0],h[1]),g[1]))
def key(g): return (g[0][0][0],g[0][0][1],g[0][1][0],g[0][1][1],g[1][0],g[1][1])
import sys
sys.path.insert(0,'output/artifacts')
from klproof2 import elems
K2I={key(g):i for i,g in enumerate(elems)}
descL=[set() for _ in range(N)]
for i,g in enumerate(elems):
    for s in range(3):
        h=compose(GENS[s],g)
        j=K2I.get(key(h),None)
        if j is not None and LEN[j]<LEN[i]: descL[i].add(s)
# left cells: graph with edges x-y if mu(x,y)!=0 or mu(y,x)!=0 (within ball, len<=6 part)
import collections
adj=[set() for _ in range(N)]
S=list(INTERVAL.keys())
Sset=set(S)
for x in S:
    for w in S:
        if x==w: continue
        if mu(x,w)!=0 or mu(w,x)!=0:
            # KL left-cell edge condition: descL inclusion... standard left preorder generated by: x <=_L w if exists ... use full W-graph edges: connect if mu!=0 AND descL(x) not subset descL(w)? For cells partition use generalized Tau-invariant + mu-graph components refined by descents.
            adj[x].add(w)
# connected components of mu-graph
seen={}; comps=[]
for x in S:
    if x in seen: continue
    stack=[x]; seen[x]=len(comps); comp=[x]
    while stack:
        u=stack.pop()
        for v in adj[u]:
            if v not in seen: seen[v]=len(comps); stack.append(v); comp.append(v)
    comps.append(comp)
print("mu-graph components:",len(comps))
for c in comps:
    print(f"  size {len(c)}: lens={sorted(LEN[i] for i in c)} descs={sorted(map(lambda i:sorted(descL[i]),c))}")
