"""Reproducible verification for lane-1353 lattice obstruction.
Computes discriminants, Smith invariants, and 2-elementary test
(2N* subset N  <=>  2*adj(M) divisible by det(M)) for the named pair.
Ordinary intersection theory for N+/N- is derived in DRAFT.md;
this script checks the Nikulin 2-elementary criterion from those matrices.
"""
import math, json, pathlib

def det2(M):
    if len(M)==1: return M[0][0]
    return M[0][0]*M[1][1]-M[0][1]*M[1][0]

def snf2(M):
    if len(M)==1: return [abs(M[0][0])]
    a,b,c,d = M[0][0],M[0][1],M[1][0],M[1][1]
    g = math.gcd(math.gcd(abs(a),abs(b)), math.gcd(abs(c),abs(d)))
    return [g, abs(det2(M))//g]

def two_star_integral(M):
    d = det2(M)
    if len(M)==1:
        # 2N*<=N  <=>  d | 2
        return d in (1,-1,2,-2)
    adj = [[M[1][1],-M[0][1]],[-M[1][0],M[0][0]]]
    return all((2*x) % d == 0 for row in adj for x in row)

# True polarising lattices from DRAFT.md Sec.1 (rank 2, sig (1,1))
Nplus  = [[4,6],[6,6]]    # Bl(P3) along CI(2,3)
Nminus = [[6,2],[2,-2]]   # Bl(Q3) along conic
# Rank-1 sublattices generated by -K|_Sigma
Rplus  = [[4]]            # (-K+)^3/(-K+|)^2 = 4
Rminus = [[6]]            # = 6

for name, M in [("N+",Nplus),("N-",Nminus),("R+",Rplus),("R-",Rminus)]:
    d = det2(M)
    print(f"{name}: det={d} SNF={snf2(M)} 2N*<=N: {two_star_integral(M)}")

# N+ has no vector of square 2: 2x^2+6xy+3y^2=1 has no integer solution (mod 3)
sols = [(x,y) for x in range(-5,6) for y in range(-5,6)
        if 2*x*x+6*x*y+3*y*y == 1]
print("square-2 vectors in (1/2)N+ rescaled form:", sols)
assert sols == []
assert snf2(Nplus)==[2,6] and snf2(Nminus)==[2,8]
assert not two_star_integral(Nplus) and not two_star_integral(Nminus)
assert not two_star_integral(Rplus) and not two_star_integral(Rminus)
print("OK: none is 2-elementary; Nikulin fixed-lattice obstruction verified.")
