"""Orbit-correct psi-floor counts F_{d,k}.

Fix: for partial markings (n<|P|) the naive Inj/Aut quotient need not be
integral. The correct unlabelled count is the number of Aut(D)-orbits of
valid labelled sequences, computed explicitly via union-find over the
automorphism group (generated by swaps of identical unbounded beads at a
floor and swaps of parallel identical elevator beads).
"""
import math
from floor_enum import enumerate_diagrams


def build_poset(d, edges, u):
    E = len(edges)
    nP = d + E + sum(u)
    pred = [set() for _ in range(nP)]
    for v in range(1, d):
        pred[v].add(v - 1)
    bid = d
    edge_beads = []
    for (i, j), w in edges:
        pred[bid].add(i)
        pred[j].add(bid)
        edge_beads.append(bid)
        bid += 1
    unb_at = {}
    for v in range(d):
        lst = []
        for _ in range(u[v]):
            pred[v].add(bid)
            lst.append(bid)
            bid += 1
        unb_at[v] = lst
    assert bid == nP
    anc = [set() for _ in range(nP)]
    for _ in range(nP):
        for e in range(nP):
            for p in list(pred[e]):
                anc[e].add(p)
                anc[e] |= anc[p]
    predmask = [0] * nP
    for e in range(nP):
        m = 0
        for p in anc[e]:
            m |= 1 << p
        predmask[e] = m
    return nP, predmask, edge_beads, unb_at


def aut_group(nP, edges, edge_beads, unb_at):
    ident = tuple(range(nP))
    gens = []
    for v, lst in unb_at.items():
        for a in range(len(lst) - 1):
            p = list(ident)
            x, y = lst[a], lst[a + 1]
            p[x], p[y] = p[y], p[x]
            gens.append(tuple(p))
    # parallel identical (pair,w) edge beads
    key2beads = {}
    for b, key in zip(edge_beads, edges):
        key2beads.setdefault(key, []).append(b)
    for lst in key2beads.values():
        for a in range(len(lst) - 1):
            p = list(ident)
            x, y = lst[a], lst[a + 1]
            p[x], p[y] = p[y], p[x]
            gens.append(tuple(p))

    def compose(g, h):
        return tuple(g[h[i]] for i in range(nP))

    G = {ident}
    stack = [ident]
    while stack:
        g = stack.pop()
        for gen in gens:
            for h in (compose(g, gen), compose(gen, g)):
                if h not in G:
                    G.add(h)
                    stack.append(h)
    return G


def valid_sequences(nP, predmask, n):
    """All order-preserving injections chain[n] -> P as tuples."""
    out = []
    seq = []

    def seq_ok(e):
        for q in seq:
            if (predmask[q] >> e) & 1:
                return False
        return True

    def rec(mask):
        if len(seq) == n:
            out.append(tuple(seq))
            return
        for e in range(nP):
            if not (mask >> e) & 1 and seq_ok(e):
                seq.append(e)
                rec(mask | (1 << e))
                seq.pop()

    rec(0)
    return out


def count_orbits(seqs, G):
    parent = list(range(len(seqs)))
    index = {s: i for i, s in enumerate(seqs)}

    def find(a):
        while parent[a] != a:
            parent[a] = parent[parent[a]]
            a = parent[a]
        return a

    def union(a, b):
        ra, rb = find(a), find(b)
        if ra != rb:
            parent[ra] = rb

    for i, s in enumerate(seqs):
        for g in G:
            t = tuple(g[e] for e in s)
            j = index.get(t)
            if j is not None:
                union(i, j)
    return len({find(i) for i in range(len(seqs))})


def valency(d, edges, u, v):
    inc = sum(1 for (i, j), w in edges if i == v or j == v)
    return inc + u[v] + 2


def F_table(d):
    diags = enumerate_diagrams(d)
    rows = {}
    for k in range(0, 3 * d - 1 + 1):
        n = 3 * d - 1 - k
        tot = 0
        for Dd in diags:
            edges, u, mu = Dd["edges"], Dd["u"], Dd["mu"]
            nP, pm, ebeads, unb = build_poset(d, edges, u)
            assert nP == 3 * d - 1
            G = aut_group(nP, edges, ebeads, unb)
            seqs = valid_sequences(nP, pm, n)
            orb = count_orbits(seqs, G)
            csum = sum(math.comb(valency(d, edges, u, v) + k - 1, k) for v in range(d))
            tot += mu * orb * csum
        rows[k] = (n, tot)
    return rows


def main():
    for d in [1, 2, 3]:
        N = {1: 1, 2: 1, 3: 12}[d]
        print(f"=== degree {d} (N_d={N}, expect F_{{d,0}}={d * N})")
        rows = F_table(d)
        for k, (n, tot) in rows.items():
            print(f"  k={k} n={n}: F={tot}")
        print()


if __name__ == "__main__":
    main()
