"""Independent verification for the A7 width-two certificate.
(1) Independent tuple-arithmetic recount of the A5/A6/A7 e2-image:
    asserts pair totals N^2 and N1>0 on every logged class, cross-checked
    against output/artifacts/e2_census.json.
(2) Replays one stored preimage witness per A7 class from the census
    witnesses embedded here (regenerated by enumerate path) — checks
    e2(x,y) has the claimed cycle type.
Convention: (a*b)(i) = a(b(i)); comm(a,b)=a^-1 b^-1 a b; e2=[c,y].
Stdlib only.
"""
import json, itertools

def mul(a, b): return tuple(a[b[i]] for i in range(len(a)))
def inv(p):
    q = [0] * len(p)
    for i, v in enumerate(p): q[v] = i
    return tuple(q)
def comm(a, b): return mul(mul(inv(a), inv(b)), mul(a, b))
def e2(x, y): return comm(comm(x, y), y)
def sgn(p):
    n = len(p); s = [False] * n; c = 0
    for i in range(n):
        if not s[i]:
            c += 1; j = i
            while not s[j]: s[j] = True; j = p[j]
    return 1 if (n - c) % 2 == 0 else -1
def ctype(p):
    n = len(p); s = [False] * n; L = []
    for i in range(n):
        if not s[i]:
            j = i; l = 0
            while not s[j]: s[j] = True; j = p[j]; l += 1
            L.append(l)
    return tuple(sorted(L, reverse=True))

def evens(n):
    return [p for p in itertools.permutations(range(n)) if sgn(p) > 0]

ok = True
for n in (5, 6, 7):
    P = evens(n)
    got = {}
    for x in P:
        for y in P:
            t = ctype(e2(x, y)); got[t] = got.get(t, 0) + 1
    N = len(P)
    assert sum(got.values()) == N * N, (n, sum(got.values()), N * N)
    print(f"A{n}: |G|={N} pairs={N * N} "
          f"counts={ {str(k): v for k, v in sorted(got.items())} }")
    rep = json.load(open("output/artifacts/e2_census.json"))[str(n)]["table"]
    for row in rep:
        t = tuple(sorted(row["cycle_type"], reverse=True))
        assert row["N1_per_elt"] > 0 and row["uniform"], row
        # class total must match recount (split halves share ctype: sum)
    # aggregate recount per ctype vs census class totals
    agg = {}
    for row in rep:
        t = tuple(sorted(row["cycle_type"], reverse=True))
        agg[t] = agg.get(t, 0) + row["N1_per_elt"] * row["size"]
    assert agg == got, (n, agg, got)
    print(f"  census cross-check: OK ({len(rep)} classes)")

# witness replay: one (x, y) per A7 class, stored as explicit perms
W = [
    ((0, 1, 2, 3, 4, 5, 6), (0, 1, 2, 3, 4, 5, 6), (1, 1, 1, 1, 1, 1, 1)),
    ((0, 1, 2, 3, 5, 6, 4), (0, 1, 3, 2, 4, 6, 5), (3, 1, 1, 1, 1)),
    ((0, 1, 2, 3, 5, 6, 4), (0, 1, 2, 4, 5, 3, 6), (2, 2, 1, 1, 1)),
    ((0, 1, 2, 3, 5, 6, 4), (0, 1, 3, 4, 5, 6, 2), (5, 1, 1)),
    ((0, 1, 2, 3, 5, 6, 4), (0, 2, 4, 5, 3, 1, 6), (4, 2, 1)),
    ((0, 1, 2, 3, 5, 6, 4), (0, 2, 4, 5, 1, 6, 3), (3, 3, 1)),
    ((0, 1, 2, 3, 5, 6, 4), (1, 4, 5, 6, 0, 2, 3), (3, 2, 2)),
]
for (x, y, exp) in W:
    assert sgn(x) > 0 and sgn(y) > 0
    t = ctype(e2(x, y))
    status = "OK" if t == exp else "MISMATCH"
    if t != exp: ok = False
    print(f"witness -> {t} expect {exp} {status}")
# 7-cycle halves: two witnesses in opposite A7-halves (aligning-sign split)
W7 = [
    ((0, 1, 2, 3, 5, 6, 4), (1, 4, 3, 5, 0, 2, 6), (2, 4, 1, 6, 5, 3, 0)),
    ((0, 1, 2, 3, 5, 6, 4), (1, 4, 5, 2, 0, 3, 6), (3, 4, 6, 1, 5, 2, 0)),
]
for (x, y, exp) in W7:
    assert sgn(x) > 0 and sgn(y) > 0
    v = e2(x, y)
    assert ctype(v) == (7,) and v == exp, (v, exp)
    print(f"7-cycle witness -> {v} OK")
print("VERIFY:", "OK" if ok else "FAIL")
assert ok
