#!/usr/bin/env python3
"""Lane-157: exact v-number vs induced-matching certificates on 7-vertex graphs.
Stdlib only. For edge ideal I(G) and squarefree f with support A:"""
import itertools, json, sys

def min_vertex_covers(n, edges):
    eset = [set(e) for e in edges]
    covers = []
    for r in range(n + 1):
        for C in itertools.combinations(range(n), r):
            s = set(C)
            if all(e & s for e in eset):
                if not any(set(p) < s for p in covers):
                    covers.append(s)
    return covers

def is_prime_edge_ideal(n, edges):
    # I prime iff complement of a minimal prime... I=(quadrics) prime iff graph is star? No:
    # (edge ideal) prime iff graph has exactly one edge... careful: prime monomial ideal = (vars subset).
    # I(G) generated by quadrics; equals (vars) only if... quadrics can't equal var-ideal unless empty.
    # I prime iff it equals P_C for some C minimal cover, i.e., all generators divisible by single var set with no quadric gens.
    # Simplest: I prime iff G is a star K1,m? I(star center c)=(x_c)*(others) not prime either. Actually edge ideal of nonempty graph is NEVER prime (generated in deg 2, prime monomial ideals generated in deg 1). Empty graph: I=(0) prime.
    return len(edges) == 0

def v_number(n, edges):
    adj = {i: set() for i in range(n)}
    for u, v in edges:
        adj[u].add(v); adj[v].add(u)
    eset = [set(e) for e in edges]
    mincov = min_vertex_covers(n, edges)
    def is_stable(A):
        s = set(A)
        return all(not (set(e) <= s) or len(e & s) < 2 for e in edges) and \
               all(len(set(e) & s) < 2 for e in edges)
    nbr = lambda A: set().union(*(adj[a] for a in A)) if A else set()
    best = None
    # degree 0: I itself prime?
    if is_prime_edge_ideal(n, edges):
        return 0, [], None
    for d in range(1, n + 1):
        for A in itertools.combinations(range(n), d):
            s = set(A)
            # stable?
            if any(len(set(e) & s) == 2 for e in edges):
                continue
            N = set().union(*(adj[a] for a in A)) - s
            # colon = prime iff N minimal cover and G-A-N edgeless
            if N not in mincov:
                continue
            rest = set(range(n)) - s - N
            if any(len(set(e) & rest) == 2 for e in edges):
                continue
            return d, sorted(A), sorted(N)
    return None, None, None

def induced_matching(n, edges):
    m = len(edges)
    best = []
    # search large first
    for k in range(m, -1, -1):
        for idx in itertools.combinations(range(m), k):
            S = [edges[i] for i in idx]
            verts = [v for e in S for v in e]
            if len(set(verts)) != 2 * k:
                continue
            V = set(verts)
            # induced: every edge of G inside V must be in S
            ok = True
            for e in edges:
                if e[0] in V and e[1] in V and (tuple(sorted(e)) not in [tuple(sorted(x)) for x in S]):
                    ok = False; break
            if ok:
                return k, [sorted(e) for e in S]
    return 0, []

def has_C4_C5(n, edges):
    adj = {i: set() for i in range(n)}
    for u, v in edges:
        adj[u].add(v); adj[v].add(u)
    # C4: pairs with >=2 common neighbors
    for u in range(n):
        for w in range(u + 1, n):
            if len((adj[u] & adj[w]) - {u, w}) >= 2:
                return True
    # C5: check 5-subsets containing induced C5
    for Q in itertools.combinations(range(n), 5):
        Q = list(Q)
        cnt = sum(1 for e in edges if e[0] in Q and e[1] in Q)
        if cnt == 5:
            deg = {q: 0 for q in Q}
            for e in edges:
                if e[0] in Q and e[1] in Q:
                    deg[e[0]] += 1; deg[e[1]] += 1
            if all(d == 2 for d in deg.values()):
                return True
    return False

def is_bipartite(n, edges):
    adj = {i: [] for i in range(n)}
    for u, v in edges:
        adj[u].append(v); adj[v].append(u)
    col = {}
    for s in range(n):
        if s in col: continue
        col[s] = 0
        stack = [s]
        while stack:
            u = stack.pop()
            for w in adj[u]:
                if w not in col:
                    col[w] = 1 - col[u]; stack.append(w)
                elif col[w] == col[u]:
                    return False
    return True

def is_well_covered(n, edges):
    mc = min_vertex_covers(n, edges)
    # G well-covered iff all maximal independent sets same size iff all minimal covers same size
    return len({len(c) for c in mc}) == 1

def has_simplicial_partition(n, edges):
    # simplicial vertex: neighborhood is a clique
    adj = {i: set() for i in range(n)}
    for u, v in edges:
        adj[u].add(v); adj[v].add(u)
    simp = set()
    for v in range(n):
        N = adj[v]
        if all(u2 in adj[u1] for u1 in N for u2 in N if u1 < u2):
            simp.add(v)
    # simplicial partition: partition V into blocks each = closed nbhd of simplicial vertex... use known def:
    # partition V = V1|...|rt with each Vi = N[vi] for simplicial vi. Try exact cover search over candidate blocks.
    blocks = []
    for v in simp:
        blocks.append(frozenset(set([v]) | adj[v]))
    # exact cover via backtracking
    V = frozenset(range(n))
    def bt(rem, chosen):
        if not rem: return chosen
        v = next(iter(rem))
        for b in blocks:
            if v in b and b <= rem:
                r = bt(rem - b, chosen + [b])
                if r is not None: return r
        return None
    return bt(V, []) is not None

def prufer_trees(n):
    # yield edge lists for all n^(n-2) labeled trees
    if n == 1:
        yield []
        return
    from itertools import product
    for seq in product(range(n), repeat=n - 2):
        deg = [1] * n
        for s in seq: deg[s] += 1
        import heapq
        leaves = [i for i in range(n) if deg[i] == 1]
        heapq.heapify(leaves)
        deg2 = deg[:]
        el = []
        import heapq as hq
        for s in seq:
            l = hq.heappop(leaves)
            el.append((l, s))
            deg2[l] -= 1; deg2[s] -= 1
            if deg2[s] == 1: hq.heappush(leaves, s)
        l1 = hq.heappop(leaves); l2 = hq.heappop(leaves)
        el.append((l1, l2))
        yield el

def main():
    n = 7
    # 1) headline witness G*
    Gs = [(0,1),(2,3),(4,5),(1,6),(3,6),(5,6)]
    v, A, C = v_number(n, Gs)
    im, M = induced_matching(n, Gs)
    print("G* v,A,C =", v, A, C, " im,M =", im, M)
    assert v == 1 and A == [6] and C == [1,3,5], (v, A, C)
    assert im == 3
    print("G* well-covered?", is_well_covered(n, Gs), "bip?", is_bipartite(n, Gs),
          "C4C5?", has_C4_C5(n, Gs), "simp-part?", has_simplicial_partition(n, Gs))
    # 2) full labeled-tree census (7^5 = 16807)
    import time
    t0 = time.time()
    tot = 0; gapcount = 0; dist = {}
    gapex = []
    agree = True
    for el in prufer_trees(n):
        E = [tuple(sorted(e)) for e in el]
        v1, A1, C1 = v_number(n, E)
        im1, M1 = induced_matching(n, E)
        # dual check of im via brute force independent verification inline (recompute differently)
        # verify v cert manually
        adj = {i: set() for i in range(n)}
        for u, vv in E: adj[u].add(vv); adj[vv].add(u)
        s = set(A1); N = set().union(*(adj[a] for a in A1)) - s if A1 else set()
        assert sorted(N) == sorted(C1), (E, A1, C1)
        mc = min_vertex_covers(n, E)
        assert set(C1) in mc
        rest = set(range(n)) - s - N
        assert not any(e[0] in rest and e[1] in rest for e in E)
        dist[(v1, im1)] = dist.get((v1, im1), 0) + 1
        if v1 + 1 <= im1:
            gapcount += 1
            if len(gapex) < 5: gapex.append((E, v1, A1, C1, im1, M1))
        tot += 1
    print(f"trees: {tot} in {time.time()-t0:.1f}s gapcount={gapcount} dist={sorted(dist.items())}")
    for g in gapex: print("  gap-ex:", g)
    # 3) superset search: add <=3 edges to G*, seek nonbip + non-wellcovered + C4C5 + no simp-partition + gap
    base = set(tuple(sorted(e)) for e in Gs)
    allpairs = [tuple(sorted(e)) for e in itertools.combinations(range(n), 2) if tuple(sorted(e)) not in base]
    found = []
    seen = set()
    for k in (1, 2, 3):
        for extra in itertools.combinations(allpairs, k):
            E = sorted(base | set(extra))
            key = tuple(E)
            if key in seen: continue
            seen.add(key)
            if is_bipartite(n, E): continue
            if is_well_covered(n, E): continue
            if not has_C4_C5(n, E): continue
            if has_simplicial_partition(n, E): continue
            v1, A1, C1 = v_number(n, E)
            im1, M1 = induced_matching(n, E)
            if v1 is not None and v1 + 1 <= im1:
                found.append({"edges": E, "v": v1, "A": A1, "C": C1, "im": im1, "M": M1})
                print("FOUND outside-all:", found[-1])
                if len(found) >= 3: break
        if len(found) >= 3: break
    print("outside-all count:", len(found))
    cert = {"Gstar": {"edges": sorted(base), "v": v, "A": A, "C": C, "im": im, "M": M},
            "tree_census": {"total": tot, "gapcount": gapcount,
                             "dist": {str(k): w for k, w in sorted(dist.items())},
                             "examples": [{"edges": e, "v": a, "A": b, "C": c, "im": d, "M": f} for (e, a, b, c, d, f) in gapex]},
            "outside_all": found}
    with open("/srv/scope-research/rounds/2026-09-07-first-light-01/workspaces/research/lane-157/output/artifacts/cert.json", "w") as fh:
        json.dump(cert, fh, indent=1)
    print("wrote cert.json")

if __name__ == "__main__":
    main()
