# Test DISCRIMINANT-based distinguishing route which IS mutation-invariant:
# For monotone torus L, the Lagrangian cubic / discriminant of Dubrovin's
# Frobenius manifold restricted to the summand generated by L.
# Chekanov vs Clifford in CP2: same #crit but DIFFERENT??? No - same.
# Hmm, in CP2 all Vianna tori generate the same summand? QH(CP2)=3-dim field,
# so all nonzero objects lie in same summand. Distinction there uses
# "wall-crossing / cluster charts", not QH summands.
#
# For dP4: QH is semisimple? QH(dP4) = ? Known: QH of del Pezzo is semisimple
# (Bayer-Manin: del Pezzo surfaces have semisimple quantum cohomology).
# Semisimple => splits into 8 fields. Two tori could generate different
# idempotents, distinguished by critical VALUES of W (eigenvalues of c1*).
# So route: compute Spec(c1*|summand(L)) = critical values of W_L.
# If CritVal(W_toric) != CritVal(W_BC) as sets, different summands -> not isotopic.
#
# Let's compute critical values for candidate potentials to see if this
# route is numerically plausible (proof of concept for DRAFT).
from sympy import symbols, diff, together, Poly, solve, N

def critvals(W, x, y):
    Wx = diff(W, x); Wy = diff(W, y)
    numx, _ = together(Wx).as_numer_denom()
    numy, _ = together(Wy).as_numer_denom()
    ex = Poly(numx, x, y).as_expr(); ey = Poly(numy, x, y).as_expr()
    sols = solve([ex, ey], [x, y], dict=True)
    vals = []
    for s in sols:
        try:
            xv = complex(N(s[x])); yv = complex(N(s[y]))
            if abs(xv) < 1e-9 or abs(yv) < 1e-9: continue
            wv = complex(N(W.subs(s)))
            vals.append((round(xv.real,6), round(xv.imag,6), round(yv.real,6), round(yv.imag,6), round(wv.real,6), round(wv.imag,6)))
        except Exception: pass
    return vals

x, y = symbols('x y')
W_toric_8term = x*y + x + x/y + y + 1/y + y/x + 1/x + 1/(x*y)  # symmetric octagon, 8 terms
W_BC_4term = x + y + 1/x + 1/y  # S2xS2-like Clifford, 4 terms
W_BC_3term = x + y + 1/(x*y)    # CP2-like Clifford, 3 terms
for name, W in [("toric8", W_toric_8term), ("BC4", W_BC_4term), ("BC3", W_BC_3term)]:
    print("="*30, name)
    for v in critvals(W, x, y):
        print("  crit:", v)
