"""Complete exact-rational SRG feasibility ledger, 51 <= v <= 100.

Stdlib only. Recomputes from integer inputs:
  count equation, spectrum type, restricted eigenvalues/multiplicities,
  Krein numbers q_ij^k in exact Q(sqrt(D)) pair arithmetic (with an
  independent plain-Fraction cross-check in the integral case),
  absolute-bound data, primitivity flags.
Emits ledger.json and replay.log deterministically.
"""
import json
import math
from fractions import Fraction

VLO, VHI = 51, 100


class QS:
    """Exact element a + b*sqrt(D) over Q, D a fixed positive nonsquare int."""

    __slots__ = ("a", "b", "D")

    def __init__(self, a, b, D):
        self.a = Fraction(a)
        self.b = Fraction(b)
        self.D = D

    def __add__(self, o):
        assert o.D == self.D
        return QS(self.a + o.a, self.b + o.b, self.D)

    def __mul__(self, o):
        assert o.D == self.D
        return QS(self.a * o.a + self.b * o.b * self.D,
                  self.a * o.b + self.b * o.a, self.D)

    def scale(self, q):
        q = Fraction(q)
        return QS(self.a * q, self.b * q, self.D)

    def is_rational(self):
        return self.b == 0

    def __repr__(self):
        return "QS(%s,%s,D=%d)" % (self.a, self.b, self.D)


def enumerate_count_solutions():
    """All integer (v,k,lam,mu) with 51<=v<=100 satisfying
    k(k-lam-1) = (v-k-1)*mu, 2<=k<=v-2, 0<=lam<k, 0<=mu<=k."""
    sols = []
    for v in range(VLO, VHI + 1):
        for k in range(2, v - 1):
            for mu in range(0, k + 1):
                num = (v - k - 1) * mu
                if num % k != 0:
                    continue
                lam = k - 1 - num // k
                if lam < 0 or lam >= k:
                    continue
                if k * (k - lam - 1) != (v - k - 1) * mu:
                    continue
                sols.append((v, k, lam, mu))
    return sols


def spectrum(q):
    """Classify spectrum of a count-equation solution.

    Returns dict with type in {integral, conference, excluded}, and for
    feasible types r,s (as (num, den) pairs or ints), f, g, D, d.
    Eigenvalues (t +/- sqrt(D))/2 with t = lam - mu.
    """
    v, k, lam, mu = q
    t = lam - mu
    D = t * t + 4 * (k - mu)
    out = {"D": D, "t": t}
    if D <= 0:
        out["type"] = "excluded"
        out["reason"] = "D<=0"
        return out
    d = math.isqrt(D)
    if d * d == D:
        # integral case: need (t+d) even and integral positive multiplicities
        if (t + d) % 2 != 0:
            out["type"] = "excluded"
            out["reason"] = "half-integer-eigenvalue"
            return out
        r = (t + d) // 2
        s = (t - d) // 2
        num = 2 * k + (v - 1) * t
        if num % d != 0:
            out["type"] = "excluded"
            out["reason"] = "nonintegral-multiplicity"
            return out
        tt = num // d
        if ((v - 1) - tt) % 2 != 0:
            out["type"] = "excluded"
            out["reason"] = "nonintegral-multiplicity"
            return out
        f = ((v - 1) - tt) // 2
        g = ((v - 1) + tt) // 2
        if f <= 0 or g <= 0 or f + g != v - 1:
            out["type"] = "excluded"
            out["reason"] = "nonpositive-multiplicity"
            return out
        if r <= 0 or s >= 0:
            out["type"] = "excluded"
            out["reason"] = "eigenvalue-sign"
            return out
        out.update({"type": "integral", "r": r, "s": s, "f": f,
                    "g": g, "d": d})
        return out
    # conference (non-integral) case: need f=g=(v-1)/2 and numerator 0
    num = 2 * k + (v - 1) * t
    if num == 0 and v % 2 == 1:
        f = g = (v - 1) // 2
        out.update({"type": "conference", "f": f, "g": g,
                    "r_num": t, "r_den": 2, "s_num": t, "s_den": 2})
        return out
    out["type"] = "excluded"
    out["reason"] = "conference-numerator-nonzero"
    return out


def krein_qsqrt(v, k, lam, mu, spec):
    """Exact Krein numbers via Q(sqrt(D)) pair arithmetic.

    Q rows (relations l=0,1,2) x cols (eigenspaces i=0,1,2):
      Q = [[1,f,g],[1,f*u1,g*u2],[1,f*w1,g*w2]]
    with u1=(t+S)/2k, u2=(t-S)/2k, w1=(-(2+t)-S)/2(v-k-1),
         w2=(-(2+t)+S)/2(v-k-1), S=sqrt(D).
    q_ij^k = 1/(v m_k) sum_l k_l Q_li Q_lj Q_lk, with relation valencies
    k_l = (1, k, v-k-1) as weights and m=(1,f,g) only in the denominator.
    Returns (dict[(i,j,k)] -> (a, b) pair, ...).  The true value is
    a + b*sqrt(D).  When D is a perfect square d^2 the pair (a, b) is
    only defined modulo a + d*b (kernel generated by S - d), so callers
    must evaluate a + d*b; when D is a nonsquare the b-parts of the
    symmetrized outputs must vanish (recorded via leftover flag).
    """
    D = spec["D"]
    t = spec["t"]
    f = spec["f"]
    g = spec["g"]
    kval = [1, k, v - k - 1]
    m = [1, f, g]
    S = QS(0, 1, D)
    u1 = QS(Fraction(t, 2 * k), Fraction(1, 2 * k), D)
    u2 = QS(Fraction(t, 2 * k), Fraction(-1, 2 * k), D)
    w1 = QS(Fraction(-(2 + t), 2 * (v - k - 1)), Fraction(-1, 2 * (v - k - 1)), D)
    w2 = QS(Fraction(-(2 + t), 2 * (v - k - 1)), Fraction(1, 2 * (v - k - 1)), D)
    Q = [[QS(1, 0, D), QS(f, 0, D), QS(g, 0, D)],
         [QS(1, 0, D), u1.scale(f), u2.scale(g)],
         [QS(1, 0, D), w1.scale(f), w2.scale(g)]]
    res = {}
    ok = True
    d = math.isqrt(D)
    sq = (d * d == D)
    for i in (0, 1, 2):
        for j in (0, 1, 2):
            for kk in (0, 1, 2):
                tot = QS(0, 0, D)
                for ell in range(3):
                    tot = tot + (Q[ell][i] * Q[ell][j] * Q[ell][kk]).scale(kval[ell])
                tot = tot.scale(Fraction(1, v * m[kk]))
                if sq:
                    # evaluate at S = d (choice of root is fixed by r > s)
                    res[(i, j, kk)] = tot.a + d * tot.b
                else:
                    if not tot.is_rational():
                        ok = False
                    res[(i, j, kk)] = tot.a
    return res, ok


def krein_frac_integral(v, k, r, s, f, g):
    """Independent plain-Fraction Krein computation (integral case only)."""
    kval = [1, k, v - k - 1]
    m = [1, f, g]
    Q = [[Fraction(1), Fraction(f), Fraction(g)],
         [Fraction(1), Fraction(f * r, k), Fraction(g * s, k)],
         [Fraction(1), Fraction(f * (-1 - r), v - k - 1),
          Fraction(g * (-1 - s), v - k - 1)]]
    res = {}
    for i in (0, 1, 2):
        for j in (0, 1, 2):
            for kk in (0, 1, 2):
                tot = Fraction(0)
                for ell in range(3):
                    tot += kval[ell] * Q[ell][i] * Q[ell][j] * Q[ell][kk]
                res[(i, j, kk)] = tot / (v * m[kk])
    return res


def build_ledger():
    sols = enumerate_count_solutions()
    rows = []
    log = []
    log.append("count-equation solutions with 51<=v<=100: %d" % len(sols))
    for (v, k, lam, mu) in sols:
        spec = spectrum((v, k, lam, mu))
        row = {"v": v, "k": k, "lam": lam, "mu": mu}
        row.update({kk: vv for kk, vv in spec.items()})
        prim = not (mu == 0 or mu == k)
        row["primitive"] = prim
        if spec["type"] == "excluded":
            log.append("EXCLUDED (%d,%d,%d,%d): %s" %
                       (v, k, lam, mu, spec["reason"]))
            rows.append(row)
            continue
        f, g = spec["f"], spec["g"]
        # Krein via Q(sqrt(D)) arithmetic
        qd, rat_ok = krein_qsqrt(v, k, lam, mu, spec)
        row["krein_sqrt_leftover_zero"] = rat_ok
        if spec["type"] == "integral":
            qf = krein_frac_integral(v, k, spec["r"], spec["s"], f, g)
            xcheck = all(qf[key] == qd[key] for key in qf)
            row["krein_crosscheck_fraction_agrees"] = xcheck
            assert xcheck, "cross-check failed at %s" % str((v, k, lam, mu))
        kq = {}
        for (i, j, kk), val in sorted(qd.items()):
            if (i, j, kk) == (0, 0, 0):
                continue
            kq["q%d%d^%d" % (i, j, kk)] = str(val)
        row["krein"] = kq
        nonneg = all(val >= 0 for val in qd.values())
        row["krein_nonnegativity"] = "PASS" if nonneg else "FAIL"
        row["krein_zeros"] = sorted("q%d%d^%d" % (i, j, kk)
                                    for (i, j, kk), val in qd.items()
                                    if (i, j, kk) != (0, 0, 0) and val == 0)
        # Absolute bound (primitive connected case)
        if prim:
            b1 = Fraction(f * (f + 3), 2)
            b2 = Fraction(g * (g + 3), 2)
            row["abs_bound_f"] = str(b1)
            row["abs_bound_g"] = str(b2)
            row["abs_bound_verdict"] = ("TIGHT" if (b1 == v or b2 == v)
                                        else ("PASS" if (v <= b1 and v <= b2)
                                              else "FAIL"))
        else:
            row["abs_bound_verdict"] = "NA-imprimitive"
        rows.append(row)
        if row["krein_nonnegativity"] == "FAIL" or \
                row["abs_bound_verdict"] == "FAIL":
            log.append("OBSTRUCTED (%d,%d,%d,%d)" % (v, k, lam, mu))
    n_feas = sum(1 for r in rows if r.get("type") in ("integral", "conference"))
    n_excl = sum(1 for r in rows if r.get("type") == "excluded")
    n_kfail = sum(1 for r in rows if r.get("krein_nonnegativity") == "FAIL")
    n_afail = sum(1 for r in rows if r.get("abs_bound_verdict") == "FAIL")
    n_tight = sum(1 for r in rows if r.get("abs_bound_verdict") == "TIGHT")
    log.append("feasible-spectrum: %d, excluded: %d" % (n_feas, n_excl))
    log.append("krein-FAIL: %d, absbound-FAIL: %d, absbound-TIGHT: %d"
               % (n_kfail, n_afail, n_tight))
    return rows, log


def main():
    rows, log = build_ledger()
    ledger = {"window": [VLO, VHI],
              "arithmetic": "exact rational + Q(sqrt(D)) pair arithmetic",
              "rows": rows}
    with open("ledger.json", "w") as fh:
        json.dump(ledger, fh, sort_keys=True, indent=1)
        fh.write("\n")
    with open("replay.log", "w") as fh:
        for line in log:
            fh.write(line + "\n")
    print("rows=%d" % len(rows))
    print("\n".join(log))


if __name__ == "__main__":
    main()
