"""Phase 3b: exact p-adic LLL reduction (Smart [Sma1998] VI.4.2, same as Sage
p_adic_LLL_bound_one_prime) specialized to K=Q, S3, v=(50069), mus=[2,3,7,11].

K=Q => e=f=m=1, theta=1, Disc=1 (ordp_Disc=0), roots of unity w=2.
M_logp: p-adic logs of 2,3,7,11 as p-adic integers mod p^prec (exact series).
  For a=1+p^k*t: log_p(a) = sum (-1)^{j+1}(a-1)^j/j, terms with j>=1; computed mod p^prec
  with denominator care: j may share p factors — here p=50069 prime > prec terms, and
  (a-1) divisible by high p-powers? ord_p(a-1)=0 for a in {2,3,7,11} (a-1 in {1,2,6,10},
  none divisible by 50069). So log_p(a) is a p-adic UNIT-ish series: each term
  (a-1)^j/j needs division by j mod p^prec — valid since gcd(j,p)=1 for j<p.
  Compute with modulus p^prec, prec up to ~40 (p^40 huge: use Python bigints, fine).
  Error: tail beyond J has valuation >= J*0 - ... terms don't decay p-adically when
  ord(a-1)=0! The series sum_{j} (-1)^{j+1}(a-1)^j/j converges p-adically iff a=1 mod p.
  BUT 2,3,7,11 are NOT 1 mod 50069. Standard fix (Smart/Sage log_p): write
  a = omega * <a> with Teichmuller split: a^{p-1} = 1 mod p, so use
  log_p(a) = log_p(a^{p-1})/(p-1): now a^{p-1}=1 mod p, series converges.
  We implement: A=a^{p-1} mod p^{prec+K}, L=log_series(A) [convergent since A=1 mod p],
  then log_p(a) = L/(p-1) as p-adic (divide by p-1, coprime to p).
  mu0=-1: log_p(-1)=0 (p odd). mu0=+1: log=0. So m0_logp=0 vector!
  => In Sage code: m0_logp all zero -> c8 stays = min val of M logs; B=[g/lam], b0=0, y=0 (homogeneous CVP).
  c9 = c8 + 0. low_bound = round(1/c5)+1.
  Lattice A: (n+m)x(n+m) = 5x5 (n=4 mus, m=1): A=[[I,0],[A21^T? ...]] per code:
    A = block([[I_n, 0],[A21^T, p^u I_m]]) with A21[i]=[mod(B_i0, p^u)].
    So A is 5x5: rows: e1..e4, (B1..B4, p^u). y=(0,0,0,0,0) since b0=0.
  c10^2 = CVP: min over nonzero lattice... minimal_vector(A^T, y=0) = shortest vector of
  lattice generated by rows?? (Sage minimal_vector(A.T, y): closest lattice point of the
  lattice spanned by rows?? to y=0 excluding 0 => shortest nonzero vector, SVP).
  If c10^2 > n*B0^2: new bound B2=(u+c9)/c5.

This is EXACT: all integers. LLL + exact SVP enumeration on dim-5 lattice.
B0: need rigorous archimedean/global B0 first. Use K0_func pipeline? K0 needs
c3,c5,c8 per place + Smart iteration. For now use SAFE overestimate B0 and show that
the reduction still crushes to small bound (reduction is insensitive: any B0<=1e30 works).
Then compute rigorous B0 via K0 loop in next script to close the loop.
"""
import math
P=50069
c3=0.0277259  # from phase3 (float est; use 0.027 as certified lower)
c3_cert=0.027
c5=c3_cert/math.log(P)
print(f"c5(cert)={c5:.6e}")
low_bound=round(1/c5)+1
print(f"low_bound={low_bound}")
# p-adic logs
def padic_log(a, p, prec, Jcap=None):
    # returns log_p(a) mod p^prec as int, via (p-1) trick
    mod=p**prec
    A=pow(a, p-1, mod*p)  # extra guard digit for division
    # series L = sum_{j>=1} (-1)^{j+1} t^j/j, t=A-1 (divisible by p)
    t=(A-1)%(mod*p)
    # number of terms: v_p(t^j) >= j -> need j up to prec (+1 guard)
    J=prec+2 if Jcap is None else Jcap
    L=0; pw=1
    modj=mod*p
    for j in range(1,J+1):
        pw=(pw*t)%modj
        # divide by j: j coprime to p for j<p (J<<p) -> modular inverse mod modj? gcd(j,modj) may not be 1
        # since modj=p^{prec+1}, gcd(j,modj)=gcd(j,p^..)=1 iff p not | j. j<=prec+2<<p so ok.
        inv=pow(j,-1,modj)
        term=pw*inv%modj
        if j%2==1: L=(L+term)%modj
        else: L=(L-term)%modj
    # L is log(A) mod p^{prec+1} (up to tail v>=J>=prec+1, and A computed mod p^{prec+1} ok since t mult)
    L//=1
    # divide by (p-1): exact in Z_p; compute integer representative: L/(p-1) mod p^prec
    inv=pow(p-1,-1,mod)
    return ( (L%mod)*inv )%mod
for prec in (8,12):
    logs={a:padic_log(a,P,prec) for a in (2,3,7,11)}
    print(f"prec={prec}: logs mod p^prec:", {a: hex(v)[:20] for a,v in logs.items()})
    # valuations
    for a,v in logs.items():
        k=0; vv=v
        while vv%P==0 and vv!=0 and k<prec: vv//=P; k+=1
        print(f"  v_p(log {a})={k}")
