"""Debug: Sage computes minimal_vector(A.transpose(), y), i.e., lattice generated by COLUMNS
of A (= rows of A^T), CVP target y. For K=Q: A is 5x5, columns:
c1=(1,0,0,0,B1), c2=(0,1,0,0,B2), c3=(0,0,1,0,B3), c4=(0,0,0,1,B4), c5=(0,0,0,0,p^u).
Lattice point: (z1,z2,z3,z4, z1B1+...+z4B4+z5 p^u). y=(0,0,0,0,0) since b0=0.
Closest nonzero... but Sage minimal_vector includes 0 itself (dist 0)? Then c10^2=0 always
and test 0 > nB0^2 fails — that can't be the intent. Check Sage minimal_vector semantics:
it likely returns min over LATTICE POINTS MINUS... or y is generally nonzero. In OUR case
mu0=+-1 gives b0=0, y=0 — degenerate! What does Smart's Lemma VI.5 say when mu0=+-1?
The linear form Lambda = sum b_i log(mu_i) + log(mu0): log(mu0)=0, and the S-unit equation
reduces: need SEPARATE handling — the approximation lattice must use the EQUATION, i.e.,
x+y=1 gives an extra relation. Actually Smart Lemma IX.3: Lambda = log|...| with mu0 from
possible_mu0s possibly nontrivial (mu0 = beta_rs products — NOT just +-1!). possible_mu0s
for v=(50069): beta valuations at v: 50069 has val 1, others 0. beta_k=50069, nk=1.
ns=[0,0,0,0], combinations of range(1)= {(0,0,0,0)} -> sigma=0 -> temp=1 -> mu0s = {+-1}.
So mu0=+-1 indeed, m0_logp=0. Then in Sage's p_adic_LLL_bound_one_prime:
  'for a in m0_logp: if a != 0 ...' — all zero, skip. c8 stays. B=[g/lam], b0=0, y=0.
  minimal_vector(A.T, 0): if that returns 0 (trivial point), c10^2=0, never > nB0^2, u+=1
  forever -> 'increase precision' True eventually. UNLESS minimal_vector excludes 0.
Check Sage minimal_vector source: does it compute shortest vector (excluding 0)?
If SVP (excluding 0): our computation above IS that: shortest^2=1 (the e_i!). e_i are
in the column lattice (c1..c4 have 1 in first coords). So c10^2=1 permanently — the
reduction NEVER fires at this place?! That means: at v=(50069), the de Weger step with
M=[2,3,7,11] cannot reduce because e_i are always short lattice vectors. Resolution in
Smart's method: iterate over ALL mu0 AND the reduction at OTHER places first reduces B0,
then... but c10^2=1 vs nB0^2 needs B0 < 1/2 — impossible. So the p-adic reduction at a
place where all mus are p-adic units with b0=0 NEVER gives anything?? That contradicts
the method's purpose. The missing piece: the full Smart iteration first uses ARCHIMEDEAN
(LLL real-log) reduction + reduction at SMALL places to bring B0 down to ~hundreds, and
the LEMMA used for the final SIEVE is different (Lemma IX.4 / sieve, not this LLL step).
The p-adic LLL step DOES fire when m0_logp != 0 (mu0 nontrivial) — at places where
possible_mu0s are nontrivial. At v=(50069) mu0=+-1 trivially... Hmm, but actually for the
S-unit equation x+y=1, Smart Ch.IX: the p-adic linear form involves mu0 that DOES vary:
possible_mu0s as coded = {+-1} here. So indeed degenerate.

Correct interpretation: the reduction lemma for ord_v bound when b0=0: we seek upper bound
on min valuation: standard de Weger lemma (e.g. Smart Lemma VI.5'): if |b_i|<=B0 and the
lattice min (c10^2 > n B0^2) then ord >= u implies... The lattice here INCLUDES e_i because
y=0. Hmm wait — re-read Sage matrix: A = block([[A11=I_n, A12=0],[A21^T, A22=p^u I_m]]).
A is (n+m)x(n+m). minimal_vector(A.T, y): lattice spanned by ROWS of A.T = COLUMNS of A.
y has n+m entries: y[i+n] = -mod(b0[i], p^u) — first n entries 0, last m = -b0 part.
With b0=0: y=0. minimal_vector(L, 0)... Let me fetch Sage's minimal_vector to see if it
excludes the trivial point.
"""
print("see analysis in docstring; fetching Sage minimal_vector source next")
