# Enumerate D8, fusion system F_D8(A6) approx, Lambda_F, and normalizer/centralizer subbisets for P=Z.
from itertools import product

# D8 as dihedral group order 8: elements (i,j) with i in Z4 (rotation), j in Z2 (reflection)
# mult: (i1,j1)*(i2,j2) = (i1 + (-1)^j1 * i2, j1+j2 mod 2)
def mul(a,b):
    i1,j1=a; i2,j2=b
    if j1==0:
        return ((i1+i2)%4, (j1+j2)%2)
    else:
        return ((i1-i2)%4, (j1+j2)%2)
def inv(a):
    i,j=a
    if j==0:
        return ((-i)%4,0)
    else:
        return (i,1)
def conj(g,x):
    return mul(mul(g,x),inv(g))

elems=[(i,j) for i in range(4) for j in range(2)]
def ename(e):
    i,j=e
    if j==0:
        return ['1','r','r2','r3'][i]
    else:
        return ['s?','rs?','r2s?','r3s?'][i]  # (i,1)= r^i s
# fix names: (0,1)=s, (1,1)=rs, (2,1)=r2s, (3,1)=r3s
names={(0,0):'1',(1,0):'r',(2,0):'r2',(3,0):'r3',(0,1):'s',(1,1):'rs',(2,1):'r2s',(3,1):'r3s'}

S=elems
Z=[(0,0),(2,0)]
V=[(0,0),(2,0),(0,1),(2,1)]  # {1,r2,s,r2s}
Vp=[(0,0),(2,0),(1,1),(3,1)] # {1,r2,rs,r3s}
C4=[(0,0),(1,0),(2,0),(3,0)]
Q1=[(0,0),(0,1)]  # <s>
Q1p=[(0,0),(2,1)] # <r2s>
Q2=[(0,0),(1,1)]  # <rs>
Q2p=[(0,0),(3,1)] # <r3s>

def subgroup_generated(gens):
    H={(0,0)}
    changed=True
    while changed:
        changed=False
        for h in list(H):
            for g in gens:
                for x in [mul(h,g),mul(g,h)]:
                    if x not in H:
                        H.add(x); changed=True
    return H

def all_subgroups():
    subs=set()
    for r in range(1<<8):
        gens=[elems[i] for i in range(8) if (r>>i)&1]
        H=subgroup_generated(gens)
        subs.add(frozenset(H))
    return sorted(subs,key=lambda h:(len(h),sorted(h)))

subs=all_subgroups()
print("num subgroups:",len(subs))
for h in subs:
    print(len(h),sorted([names[x] for x in h]))

# Normalizers/centralizers in S
def normalizer(H):
    H=set(H)
    return [g for g in S if all(mul(mul(g,h),inv(g)) in H for h in H)]
def centralizer(H):
    H=set(H)
    return [g for g in S if all(mul(g,h)==mul(h,g) for h in H)]

print("N_S(Z)=",len(normalizer(Z)), "C_S(Z)=",len(centralizer(Z)))
print("N_S(Q1)=",len(normalizer(Q1)))

# Define alpha: V->V cycling s -> r2 -> r2s -> s ; i.e. (0,1)->(2,0)->(2,1)->(0,1)
# V elements: 1, r2, s, r2s
alpha_map={(0,0):(0,0),(0,1):(2,0),(2,0):(2,1),(2,1):(0,1)}
# check automorphism
for a in V:
    for b in V:
        assert alpha_map[mul(a,b)]==mul(alpha_map[a],alpha_map[b]), (a,b)
print("alpha ok")
# beta: V'->V' cycling rs -> r2 -> r3s -> rs
beta_map={(0,0):(0,0),(1,1):(2,0),(2,0):(3,1),(3,1):(1,1)}
for a in Vp:
    for b in Vp:
        assert beta_map[mul(a,b)]==mul(beta_map[a],beta_map[b])
print("beta ok")

# Build fusion system morphisms: represent homomorphisms as dicts on subgroups.
# Generate via closure: start with all conjugations c_g: N_S(P,Q)-> etc, plus alpha^{±1}, beta^{±1}, then close under composition, restriction, inversion? For saturated fusion system generated by these, Hom_F(P,Q) = {phi: P->Q injective | ...}. Since groups small, we can compute by brute force: all injective homomorphisms, then take smallest fusion system containing generators closed under axioms? Simpler: compute group G=A6 realization? Too heavy.
# Instead compute F-conjugacy using generators: build category via BFS on isomorphisms between subgroups.
# Approach: nodes = subgroups; edges = generating isomorphisms (Inn + alpha,beta and their restrictions?). Then Hom = paths + restrictions.
# Generators:
#  - for each g in S, each P, c_g: P -> gPg^{-1}
#  - alpha: V->V, alpha^{-1}, and all restrictions? In fusion systems, if alpha in F then all its restrictions to subgroups... but restrictions to which? All restrictions alpha|_A for A<=V are also in F. Similarly beta.
# Then close under composition and restriction (restriction of any morphism to subgroup) and inversion? Composition closure will generate e.g. beta^{-1} alpha: Q1 -> Q2.

def apply_map(mp, x):
    return mp[x]

def restrict_map(mp, dom, sub):
    return {x: mp[x] for x in sub}

# represent morphism by (dom tuple, cod tuple, map tuple). Let's BFS.
from collections import defaultdict

def all_conj_maps():
    maps=[]
    for P in subs:
        P=list(P)
        for g in S:
            Q=tuple(sorted([mul(mul(g,x),inv(g)) for x in P]))
            # check Q is subgroup (it is)
            mp={x: mul(mul(g,x),inv(g)) for x in P}
            maps.append((frozenset(P),frozenset(Q),mp))
    return maps

conj_maps=all_conj_maps()

# generating isos: alpha, beta + inverses on V,Vp
def inv_map(mp, dom):
    invm={}
    for x,y in mp.items():
        invm[y]=x
    return invm

gen=[(frozenset(V),frozenset(V),dict(alpha_map)),(frozenset(V),frozenset(V),inv_map(alpha_map,V)),
     (frozenset(Vp),frozenset(Vp),dict(beta_map)),(frozenset(Vp),frozenset(Vp),inv_map(beta_map,Vp))]
gen+=conj_maps

# closure: set of morphisms (dom frozenset, cod frozenset, maptuple). Include inclusions? For fusion system Hom includes non-iso (inclusions composed with isos). We'll generate isomorphisms first, then Hom(P,Q) = {incl o iso}.
# Close isos under composition, restriction to subgroups (with appropriate cod restriction), inversion.
iso_set=set()
def key(dom,cod,mp):
    return (tuple(sorted(dom)),tuple(sorted(cod)),tuple(sorted([(a,mp[a]) for a in dom])))

for d,c,m in gen:
    # only isos (bijective)
    if len(d)==len(c):
        iso_set.add(key(d,c,m))

changed=True
while changed:
    changed=False
    cur=list(iso_set)
    # decode
    def decode(k):
        dt,ct,mt=k
        return (set(dt),set(ct),dict(mt))
    # composition
    for k1 in cur:
        d1,c1,m1=decode(k1)
        for k2 in cur:
            d2,c2,m2=decode(k2)
            if c1==d2:
                # m2 o m1 : d1 -> c2
                try:
                    m={x: m2[m1[x]] for x in d1}
                except KeyError:
                    continue
                k=key(d1,c2,m)
                if k not in iso_set:
                    iso_set.add(k); changed=True
    # inversion
    for k1 in cur:
        d1,c1,m1=decode(k1)
        m={v:k for k,v in m1.items()}
        k=key(c1,d1,m)
        if k not in iso_set:
            iso_set.add(k); changed=True
    # restriction: for each iso f:d->c, each A<=d, get f|_A : A -> f(A)
    # need subgroups list
    sublist=[set(s) for s in subs]
    for k1 in cur:
        d1,c1,m1=decode(k1)
        for A in sublist:
            if A<=d1:
                B=set(m1[x] for x in A)
                # B must be subgroup (it will be)
                m={x:m1[x] for x in A}
                k=key(A,B,m)
                if k not in iso_set:
                    iso_set.add(k); changed=True
    # Note: this loop may blow up but groups tiny.

print("num isos:",len(iso_set))

# F-conjugacy classes of subgroups
def f_conj(P,Q):
    for k in iso_set:
        dt,ct,mt=k
        if set(dt)==set(P) and set(ct)==set(Q):
            return True
    return False

# classes
classes=[]
used=set()
for P in subs:
    if tuple(sorted(P)) in used: continue
    cl=[P]
    used.add(tuple(sorted(P)))
    for Q in subs:
        if tuple(sorted(Q)) in used: continue
        if f_conj(P,Q):
            cl.append(Q); used.add(tuple(sorted(Q)))
    classes.append(cl)
for cl in classes:
    print("class size",len(cl),"orders",set(len(c) for c in cl), [[names[x] for x in sorted(c)] for c in cl])

# Identify class of Z
for cl in classes:
    if frozenset(Z) in [frozenset(c) for c in cl]:
        print("Z-class:", [[names[x] for x in sorted(c)] for c in cl])
