# V4/A4 test of Conjecture 9.16 for noncentric P of order 2.
# S = C2 x C2 (abelian => every proper P noncentric, fully normalized since N_S=S).
# F = F_S(A4): Aut_F(S) = C3 cycling the three involutions.
from itertools import product
from collections import defaultdict

# Model V4 as F2^2
S = [(0,0),(1,0),(0,1),(1,1)]
def add(a,b): return (a[0]^b[0], a[1]^b[1])
def neg(a): return a
Z=(0,0); A=(1,0); B=(0,1); C=(1,1)
names={Z:'1',A:'a',B:'b',C:'c'}
subs = [
    frozenset([Z]),
    frozenset([Z,A]),
    frozenset([Z,B]),
    frozenset([Z,C]),
    frozenset(S),
]
P = frozenset([Z,A])  # our test P = <a>
Qs = subs

# F-morphisms: all injective group homs generated by C3 cycling a->b->c plus identities.
# Represent hom by dict. Build all injective homs, keep those in F:
# F(S,S) = {id, al, al^2} with al: a->b->c->a; F between C2s: all isos; C2->S: all injective; 1->anything: trivial.
# enumerate all maps and check homomorphicity
allmaps = {}
def all_homs(D, E):
    # E ambient S; image must lie in S (any subgroup allowed? codomain S)
    res=[]
    for vals in product(S, repeat=len(D)):
        mp=dict(zip(sorted(D),vals))
        if mp[Z]!=Z: continue
        ok=True
        for x in D:
            for y in D:
                if add(x,y) in D:
                    if mp[add(x,y)]!=add(mp[x],mp[y]): ok=False;break
            if not ok: break
        if not ok: continue
        # injective?
        if len(set(mp.values()))<len(D): continue
        res.append(mp)
    return res

HOM = {}  # (D) -> list of maps D->S in F
al = {Z:Z,A:B,B:C,C:A}
def al2(x): return al[al[x]]
FSS = [{x:x for x in S}, dict(al), {x:al2(x) for x in S}]
for D in subs:
    lst=[]
    if len(D)==1:
        lst=[{Z:Z}]
    elif len(D)==2:
        # all 3 injective homs (generator -> any involution)
        lst=all_homs(D,S)
        assert len(lst)==3
    elif len(D)==4:
        lst=FSS
    HOM[tuple(sorted(D))]=lst
print("HOM sizes:", {k:len(v) for k,v in HOM.items()})

# Orbit types: (Q, psi) with Q<=S, psi in F(Q,S). (S,S)-conjugacy: S abelian => each pair own class.
types=[]
for Q in subs:
    for psi in HOM[tuple(sorted(Q))]:
        types.append((Q,psi))
print("num types:",len(types))
for i,(Q,psi) in enumerate(types):
    print(i, sorted([names[x] for x in Q]), {names[a]:names[b] for a,b in psi.items()})

# Coset model: G_Q,psi = {(psi(q),q)} <= S x S. Points = left cosets. Fixed by (Pp,phi): coset rG fixed iff r^{-1}(phi(p),p)r in G forall p.
def graph(Q,psi): return set((psi[q],q) for q in Q)
def coset_reps(Q,psi):
    G=graph(Q,psi); SxS=[(a,b) for a in S for b in S]
    seen=set(); reps=[]
    for r in SxS:
        if r in seen: continue
        cos=set(((add(r[0],g1)),(add(r[1],g2))) for (g1,g2) in G)
        for c in cos: seen.add(c)
        reps.append(r)
    return reps
def fixed_count(Q,psi,Pp,phi):
    G=graph(Q,psi)
    n=0
    for r in coset_reps(Q,psi):
        ok=True
        for p in Pp:
            e=(phi[p],p)
            # r^{-1} e r in G? additive: (-r0+ e0 + r0, ...) = e since abelian! So condition independent of r: e in G.
            # Wait S x S abelian => conjugate = itself. So coset rG fixed iff e*rG = rG iff r^{-1}er in G iff e in G (abelian).
            # So fixed = either all or nothing!
            if e not in G: ok=False;break
        if ok: n+=1
    return n

# Since S abelian, fixed_count is either 0 or full orbit size. Check:
# e in G <=> phi(p)=psi(p) for p in Pp cap Q... precisely: (phi(p),p)=(psi(q),q) for some q: p=q in Pp cap Q and phi=psi there.
# So [Q,psi]_{(Pp,phi)} = 16/|Q| if phi|_{Pp cap Q}=psi|_{Pp cap Q} (and Pp cap Q... need p in Q) else 0. Actually need Pp<=Q and phi=psi|_{Pp}? Since e=(phi(p),p) in G={(psi(q),q)} requires p in Q and phi(p)=psi(p). So condition: Pp<=Q and phi==psi|_{Pp}.
NM=len(types)
pairs=[]  # all (Pp,phi) with phi in F
for Pp in subs:
    for phi in HOM[tuple(sorted(Pp))]:
        pairs.append((Pp,phi))
print("num pairs:",len(pairs))
import numpy as np
M=[[fixed_count(Q,psi,Pp,phi) for (Q,psi) in types] for (Pp,phi) in pairs]
for i,(Pp,phi) in enumerate(pairs):
    print("pair",sorted([names[x] for x in Pp]),{names[a]:names[b] for a,b in phi.items()},"->",M[i])

# F x F classes of pairs: (Pp,phi)~(Pp',phi') iff exists eta1:Pp->Pp', eta2:phi(Pp)->phi'(Pp') in F with phi'=eta2 phi eta1^{-1}.
# Compute F-isos between subgroups: reuse HOM restricted? iso = bijective maps in HOM with image exactly target.
def f_isos(D,E):
    res=[]
    for mp in HOM[tuple(sorted(D))]:
        if set(mp.values())==set(E):
            res.append(mp)
    return res
def fequiv(i,j):
    Pp,phi=pairs[i]; Pp2,phi2=pairs[j]
    img1=set(phi.values()); img2=set(phi2.values())
    for e1 in f_isos(Pp,Pp2):
        for e2 in f_isos(frozenset(img1),frozenset(img2)):
            if all(phi2[e1[p]]==e2[phi[p]] for p in Pp):
                return True
    return False
classes=[]; used=[False]*len(pairs)
for i in range(len(pairs)):
    if used[i]: continue
    cl=[i]; used[i]=True
    for j in range(i+1,len(pairs)):
        if not used[j] and fequiv(i,j): cl.append(j); used[j]=True
    classes.append(cl)
print("F-classes of pairs:")
for cl in classes:
    print([(sorted([names[x] for x in pairs[i][0]]),{names[a]:names[b] for a,b in pairs[i][1].items()}) for i in cl])

# Stability: M[i]*c equal for all i in same class.
# Find minimal c >= 0 integers with c[type(S,id)]>=1 (=1 minimal) stable. Greedy level-by-level à la Reeh:
# Actually solve: minimize total size subject to stability + c[S,id]=1. Small ILP by brute force BFS since sizes small.
# Orbit sizes:
sizes=[16//len(Q) for (Q,psi) in types]
print("sizes:",sizes)
idx_Sid = next(i for i,(Q,psi) in enumerate(types) if len(Q)==4 and all(psi[x]==x for x in Q))
print("idx_Sid:",idx_Sid)
# Brute force: bound each c in 0..3, require c[idx]=1, check stability; minimize sum c_i*sizes.
best=None
# 13 types -> 4^12 too big. Instead use level structure: stability classes decouple? Let's do ILP via PuLP? not installed. Use brute force with constraint propagation:
# Note fixed matrix is 0/fullsize. Stability within class: rows identical? Let's inspect: rows in same class must have same pattern over columns for stability to be achievable... Actually M rows in same F-class are generally DIFFERENT rows (different pairs), stability demands M[i]c = M[j]c.
# Since abelian, M[i][t] nonzero iff Pp<=Q_t and phi=psi_t|_{Pp}. For class of (S, alpha^k): rows differ by alpha; columns [S,alpha^k] each match exactly one row. So c on those must be equal! Similarly C2-rows: F-class of all (C2, incl-ish)... let's just solve with itertools but reduce: group columns by F x F class too? Columns in same F x F class must have equal c? NO — minimal solution uses one basis element, not uniform. Hmm, but Theorem 5.3: Omega_S = unique minimal containing [S,id]; search directly: BFS over c vectors by increasing total order, test stability. Use recursion with pruning.
import itertools, sys
# order columns; fix c[idx_Sid]=1.
# Bound: try total "extra size" increasing. Use DFS with stability linear constraints.
# Represent constraints: for each class cl with rows R: for consecutive rows, sum_t (M[r1][t]-M[r2][t]) c_t = 0.
cons=[]
for cl in classes:
    for k in range(len(cl)-1):
        cons.append([M[cl[k]][t]-M[cl[k+1]][t] for t in range(NM)])
print("num constraints:",len(cons))
# DFS over t with bounds 0..4, c[idx]=1, prune using partial sums? Sizes small; do best-first search.
best=[None]
def search(order, c, bound_total):
    pass
# Simpler: use scipy? Use brute force via integer linear programming with `itertools.product` on lower orbits only.
# Observe: constraints for rows (S,.): M row for (S,alpha^j) matches only columns with Q=S,psi=alpha^j (entry 4) — since Pp=S<=Q requires Q=S. So stability among the 3 S-rows forces c[S,id]=c[S,al]=c[S,al2]. With c[S,id]=1 => all three =1. Good, that fixes S-columns (each 1, size 4 each =12).
# Remaining: C2 rows and trivial rows. Columns with Q=C2 or 1.
# C2-rows: F-class structure? pairs (C2->S): 3 domains x 3 maps = 9 rows. F-equivalence: all with same...? Since all C2s F-conjugate and maps differ by post-composition... likely ALL 9 in ONE class? Check output above. Then stability: each such row has matches: S-columns (Q=S): row (Pp=C2,phi) vs column (S,alpha^j): Pp<=S yes, phi==alpha^j|_{Pp}? For fixed phi (generator->x), how many alpha^j extend it? Each phi extends to exactly one alpha^j (since alpha^j determined by image of one generator? alpha cycles a->b->c; restriction to <a>: alpha^j(a) = ... distinct for j=0,1,2. Yes exactly one). So each C2-row gets 4 from exactly one S-column (=4). Plus C2-columns: (Q=C2',psi): match iff Pp<=Q (i.e., Pp==Q since same order) and phi==psi. So row (Pp,phi) matches exactly one C2-column: (Pp, phi) itself (entry 8). Plus trivial column (Q=1): Pp<=1? No (Pp order 2). So 0.
# Stability across all 9 rows: 4 (from S-cols, same for all rows since each row gets exactly one 4) + 8*c[(Pp,phi)] must be equal => all C2-column coefficients equal! Say c2. Minimal c2=0 works (each row total 4). So C2-columns all 0? But wait need check: is the S-column contribution really equal across rows? Each row matches exactly one S-column with value 4, and all S-columns have c=1, so yes each row gets 4. Equal. So c2=0 OK.
# Trivial rows: single row (1, trivial). Matches: S-columns: 4 each? (1<=S, trivial==alpha|_1) => 3 columns x4 =12. C2-columns: each (Q,psi): 1<=Q, trivial==psi|_1 => all 9 columns x16. Plus trivial column x16. Stability trivially (single row class). Minimal => c1=0, c2=0.
# So Lambda_F = 3 orbits [S,id],[S,al],[S,al2], size 12. Verify: is it F-stable? C2-rows all 4 ✓; S-rows: row (S,alpha^j) matches only column (S,alpha^j) (4) ✓ equal; trivial row 12 ✓. Generated ✓. Augmentation 12/4=3 prime to 2 ✓ characteristic. Minimal ✓.
# So compute N-sub for P=<a>, K=Aut(P)=1 (also =Inn since abelian? Inn(P)=1; K>=Inn and <=Inn both hold).
# N-sub: points with Stab (Q,psi): P<=Q, psi(P)=P.
# Orbit [S,id]: stabilizer (S,id): P<=S, id(P)=P ✓ all 4 pts selected.
# Orbit [S,al]: stabilizer (S,al): al(P)=<b> != P ✗ 0 pts.
# Orbit [S,al2]: al2(P)=<c> ✗ 0 pts.
# So N-sub = [S,id] as (S,S)-set, size 4. N=N_S(P)=S. N-fusion N_F(P): computed below; if Lambda_N=[S,id], equality HOLDS again!
# Let's verify N-fusion and Lambda_N computationally.
