"""Lane-480: E2-vanishing of the naive h6^2*h7 h0-tower at stem 253 (stdlib only).

Rigorous lemma L1 (target narrowing, NOT a window claim):
  In Ext_A^{*,*}(F2,F2), h6*h7 = 0 (Adams 2-line relation h_i*h_{i+1}=0;
  cited e.g. in LWX Sec 1 / Cor 1.5 proof: 2-line generated by {h_i h_j} with
  h_i h_{i+1}=0; also listed in BX Example 1.23 Sq^0-family discussion context).
  Hence h6^2*h7 = h6*(h6*h7) = 0, and h0^k*h6^2*h7 = 0 for all k >= 0.
  Bidegrees: h6^2 at (stem 126, filt 2), h7 at (127,1); product at (253,3);
  h0^k multiple at (253,3+k). For the killing window r=6..9 (filts 8..11),
  k=5..8: this whole decomposable family contributes ZERO at E2.
  So no killing-target E2 ancestor lies in the h0-tower on h6^2*h7.

Also records: h0*h7^2 = 0 on E3+ (from d2(h8)=h0 h7^2), consistent with
check_h0_narrowing.py; and h0*h6^2 is hit by d2(h7) (so zero on E3+ as an
E2 product — compatible with h6^2 itself surviving, LWX).

Run: python3 output/artifacts/check_l1_vanishing.py -> L1_VANISHING_OK
"""
import sys

def main():
    h6 = (63, 1)    # (stem, filt)
    h7 = (127, 1)
    h62 = (2*h6[0], 2*h6[1])
    assert h62 == (126, 2), h62
    prod = (h62[0] + h7[0], h62[1] + h7[1])
    assert prod == (253, 3), prod
    print("h6*h7 = 0 in Ext (2-line relation) => h6^2*h7 = h6*(h6*h7) = 0 at (stem 253, filt 3)")
    for k in range(0, 9):
        print(f"h0^{k}*h6^2*h7 = 0 at (stem 253, filt {3+k})")
    window = {6: 8, 7: 9, 8: 10, 9: 11}  # r -> filt
    for r, f in window.items():
        k = f - 3
        assert k in (5, 6, 7, 8), (r, f, k)
        print(f"d_{r} filt {f}: h0^{k}*h6^2*h7 = 0 — family contributes nothing")
    print("L1_VANISHING_OK")

if __name__ == "__main__":
    sys.exit(main())
