from math import gcd, isqrt

# The sharp lattice L = U(4).
Q = ((0,4),(4,0))
det = Q[0][0]*Q[1][1]-Q[0][1]*Q[1][0]
assert det == -16

# Pairing ideal is generated by Gram entries.
pairing_divisibility = gcd(gcd(abs(Q[0][0]), abs(Q[0][1])), abs(Q[1][1]))
assert pairing_divisibility == 4
assert 12 % pairing_divisibility == 0

# q(x,y)=8xy, so all norms are multiples of 8.
targets = {2,4,6,12}
for x in range(-20,21):
    for y in range(-20,21):
        norm = 8*x*y
        assert norm not in targets

# A primitive positive vector exists, for example (1,1), of square 8.
assert 8*1*1 == 8
assert gcd(1,1) == 1

# Explicit primitive embedding L -> U^3.
# Coordinates are (e1,f1,e2,f2,e3,f3), with e_i.f_i=1.
a = (1,0,0,0,0,0)
b = (0,4,1,0,0,0)

def cup(v,w):
    return (
        v[0]*w[1] + v[1]*w[0] +
        v[2]*w[3] + v[3]*w[2] +
        v[4]*w[5] + v[5]*w[4]
    )

assert cup(a,a) == 0
assert cup(b,b) == 0
assert cup(a,b) == 4

# The 2x2 minor using coordinates e1,e2 equals 1, so the span is primitive.
minor_e1_e2 = a[0]*b[2] - a[2]*b[0]
assert minor_e1_e2 == 1

# Numerical sharpness: the binary-form reduction used in the proof gives m^2 <= Delta.
# Hence Delta < 16 forces m <= 3, and the even lattice primitively represents 2m in {2,4,6}.
for Delta in range(1,16):
    max_m = isqrt(Delta)
    assert max_m <= 3

print("determinant=-16")
print("pairing_image=4Z")
print("contains_12=true")
print("target_norms_2_4_6_12_absent=true")
print("primitive_positive_norm=8")
print("primitive_embedding_minor=1")
print("sharp_threshold=16")
print("VERIFY_OK")
