"""Full pipeline: enumerate sigma-invariant STS(21) per FIX pattern, Pasch-filter,
Pasch-switch twin test, isomorphism test (brute force w/ degree pruning), involution check.
Saves all single-Pasch systems + twin verdicts."""
import sys, time, json
sys.setrecursionlimit(100000)
from itertools import combinations, permutations
def sig(x): return x^1 if x<18 else x
P2id={}; n=0
def pid(a,b):
    global n
    if a>b:a,b=b,a
    sa,sb=sig(a),sig(b)
    e,f=(sa,sb) if sa<sb else (sb,sa)
    ra,rb=a,b
    if e<a or (e==a and f<b): ra,rb=e,f
    if (ra,rb) not in P2id: P2id[(ra,rb)]=n; n+=1
    return P2id[(ra,rb)]
for a in range(18):
    for b in range(a+1,18):
        if sig(a)==b: continue
        pid(a,b)
P3=[t for t in combinations(range(18),3) if not (sig(t[0])==t[1] or sig(t[0])==t[2] or sig(t[1])==t[2])]
P3=[t for t in P3 if t<tuple(sorted((sig(t[0]),sig(t[1]),sig(t[2]))))]

def enum_pattern(asg,cap,tlim):
    Fof=[int(c) for c in asg]
    fixcell=[[0]*9 for _ in range(3)]
    for i,f in enumerate(Fof): fixcell[f][i]=1
    m1col={}; nc=72
    for f in range(3):
        for i in range(9):
            if not fixcell[f][i]: m1col[(f,i)]=nc; nc+=1
    rows=[]
    for f in range(3):
        F=18+f
        for i in range(9):
            for j in range(i+1,9):
                if fixcell[f][i] or fixcell[f][j]: continue
                for x in (2*i,2*i+1):
                    for y in (2*j,2*j+1):
                        t=tuple(sorted((F,x,y))); s=tuple(sorted((sig(F),sig(x),sig(y))))
                        if t>s: continue
                        rows.append(([pid(x,y),m1col[(f,i)],m1col[(f,j)]],('MIX',t)))
    for t in P3:
        rows.append(([pid(t[0],t[1]),pid(t[0],t[2]),pid(t[1],t[2])],('P3',t)))
    col_rows=[[] for _ in range(nc)]
    for ri,(cl,_) in enumerate(rows):
        for c in cl: col_rows[c].append(ri)
    rowmask=[]
    for cl,_ in rows:
        m=0
        for c in cl: m|=(1<<c)
        rowmask.append(m)
    FULL=(1<<nc)-1
    sols=[]; t0=time.time(); stop=[False]
    def dfs(rem,chosen):
        if stop[0]: return True
        if time.time()-t0>tlim: stop[0]=True; return True
        if rem==0: sols.append(list(chosen)); return len(sols)>=cap
        best=-1;bestn=10**9;besto=None
        r=rem
        while r:
            lsb=r&(-r); c=lsb.bit_length()-1; r^=lsb
            opts=[ri for ri in col_rows[c] if rowmask[ri]&~rem==0]
            if not opts: return False
            if len(opts)<bestn: bestn=len(opts);best=c;besto=opts
            if bestn<=1: break
        for ri in besto:
            chosen.append(ri)
            if dfs(rem&~rowmask[ri],chosen):
                if len(sols)>=cap or stop[0]: return True
            chosen.pop()
        return False
    dfs(FULL,[])
    # decode to orbit lists
    out=[]
    for s in sols:
        mix=[rows[ri][1][1] for ri in s if rows[ri][1][0]=='MIX']
        p3=[rows[ri][1][1] for ri in s if rows[ri][1][0]=='P3']
        out.append((mix,p3))
    return out,stop[0]

def expand(FIX,mix,p3):
    blocks=set()
    blocks.add((18,19,20))
    for i,f in enumerate(FIX):
        blocks.add(tuple(sorted((18+f,2*i,2*i+1))))
    for t in mix:
        blocks.add(tuple(sorted(t))); blocks.add(tuple(sorted((sig(t[0]),sig(t[1]),sig(t[2])))))
    for t in p3:
        blocks.add(tuple(sorted(t))); blocks.add(tuple(sorted((sig(t[0]),sig(t[1]),sig(t[2])))))
    assert len(blocks)==70
    return blocks

def pasches(blocks):
    res=[]
    for s6 in combinations(range(21),6):
        s=set(s6)
        inside=[b for b in blocks if set(b)<=s]
        if len(inside)==4:
            from collections import Counter
            d=Counter(x for b in inside for x in b)
            if all(d[x]==2 for x in s6):
                res.append((s6,inside))
    return res

def switch(blocks,s6,inside):
    # Pasch trade: the 4 triples are {a,b,c},{a,d,e},{b,d,f},{c,e,f)}-type; opposite trade = other 4 triples on same 6-set completing... standard: opposite = complement triples within 6-set: the 4 triples NOT in inside among C(6,3) restricted... Actually opposite Pasch on same 6 points: the unique other set of 4 triples on these 6 points forming STS(6)-like config: inside union opposite = all... no: K6 edge-set partition: 4 triples cover 12 of 15 pairs; opposite covers the same 12 pairs differently? NO — Pasch switch replaces 4 blocks by the 4 complementary... let me recall: Pasch {abc, ade, bdf, cef} on {a,b,c,d,e,f}; opposite = {abd? } hmm. Correct opposite: {adf? ...}. Standard switch: {abc,ade,bdf,cef} -> {abd?} no.
    # Definition: the 6-set's 4 triples use 12 pairs; remaining 3 pairs form a perfect matching... The opposite trade uses the SAME 12 pairs: pairs are partitioned into 4 triples differently. E.g. Pasch generated by pairs: opposite = swap. Concretely: blocks {x1x2x3, x1y2y3, y1x2y3, y1y2x3} <-> {y1y2y3... } hmm 6 points {x1,x2,x3,y1,y2,y3}? A Pasch is two triples + two more: {abc, ade, bdf, cef}: pairs used: ab ac bc, ad ae de, bd bf df, ce cf ef. Opposite trade: {abd?} — pairs ab,ad,bd are used (in different blocks). New grouping must reuse exactly these 12 pairs: {abd? no: ab,ad,bd — ab in abc, ad in ade, bd in bdf — yes!} So opposite includes abd? Check: abd uses ab,ad,bd — all used. Similarly ace? ac,ae,ce used yes. bcf? bc,bf,cf used yes. def? de,df,ef used yes. So opposite = {abd, ace, bcf, def}. General algorithm: find the partition: the 3 pairs NOT covered (matching): here {af? ...} total pairs 15, used 12, unused 3 = {af? be? cd?}: af: a-f? blocks with a: abc,ade; f in bdf,cef. af unused yes. be unused yes. cd unused yes. Opposite = triples each containing exactly one unused pair? abd contains... unused pairs af,be,cd: abd has none. Hmm so rule: opposite triples avoid the matching pairs. Simplest robust method: among all C(6,3)=20 triples, the opposite = the 4 triples disjoint (as pair-sets) ... compute: candidates = triples whose 3 pairs are all in used-pair-set, minus inside = exactly 4 = opposite. Verify count.
    s=set(s6)
    used=set()
    for b in inside:
        for p in combinations(b,2): used.add(tuple(sorted(p)))
    opp=[]
    for t in combinations(s6,3):
        ps=[tuple(sorted(p)) for p in combinations(t,2)]
        if all(p in used for p in ps) and tuple(sorted(t)) not in inside:
            opp.append(tuple(sorted(t)))
    assert len(opp)==4, (s6,inside,opp)
    return opp

def canon_invariant(blocks):
    # cheap isomorphism invariant: Pasch count + distribution of block-intersection... use full brute-force iso only when needed
    return len(pasches(blocks))

def iso(blocks1,blocks2):
    # brute-force isomorphism with pruning: 21! impossible in general; use backtracking with pair signatures.
    # signature: for each point, number of Pasch 6-sets containing it; refine by block-membership counts.
    # For small use (single-Pasch systems), strong: Pasch points (6) vs others (15) distinguished.
    b1=set(blocks1); b2=set(blocks2)
    if len(b1)!=len(b2): return None
    # incidence signatures via iterative color refinement (WL-1 on point-block incidence)
    def refine(blocks):
        blocks=list(blocks)
        blk_of=[[] for _ in range(21)]
        for bi,b in enumerate(blocks):
            for x in b: blk_of[x].append(bi)
        col={x:0 for x in range(21)}
        for _ in range(10):
            sigs={}
            for x in range(21):
                key=(col[x],tuple(sorted(col[y] for bi in blk_of[x] for y in blocks[bi] if y!=x)))
                sigs.setdefault(key,[]).append(x)
            new={}
            for k,xs in sorted(sigs.items()):
                for x in xs: new[x]=len(new)
            # normalize: map distinct keys to ids
            key2id={k:i for i,k in enumerate(sorted(sigs))}
            ncol={x:key2id[(col[x],tuple(sorted(col[y] for bi in blk_of[x] for y in blocks[bi] if y!=x)))] for x in range(21)}
            if ncol==col: break
            col=ncol
        return col
    c1=refine(b1); c2=refine(b2)
    from collections import Counter
    if Counter(c1.values())!=Counter(c2.values()): return None
    # backtrack over color classes
    import itertools
    classes={}
    for x in range(21): classes.setdefault(c1[x],[]).append(x)
    targets={}
    for x in range(21): targets.setdefault(c2[x],[]).append(x)
    order=sorted(range(21),key=lambda x:(len(classes[c1[x]]),x))
    b2s=set(blocks2)
    mapping={}
    used=set()
    # order points by class size then index
    bl1=list(blocks1)
    blkset2=set(blocks2)
    def bt(k):
        if k==21:
            # verify
            return all(tuple(sorted(mapping[x] for x in b)) in blkset2 for b in bl1)
        x=order[k]
        for y in targets[c1[x]]:
            if y in used: continue
            # local check: pairs (x,z) mapped must be in a common block of b2 for mapped z
            ok=True
            for z,w in mapping.items():
                # pair x,z in some block of b1; image pair y,w must be in some block of b2
                # find block of b1 containing x,z
                b=None
                for bb in bl1:
                    if x in bb and z in bb: b=bb; break
                # find block of b2 containing y,w
                found=False
                for bb in blocks2:
                    if y in bb and w in bb: found=True; break
                if not found: ok=False; break
            if not ok: continue
            mapping[x]=y; used.add(y)
            if bt(k+1): return True
            del mapping[x]; used.remove(y)
        return False
    if bt(0): return dict(mapping)
    return None

if __name__=="__main__":
    t0=time.time()
    pats={"000000012":None,"000001112":None,"000111222":None}
    total_single=0
    twins=[]
    for asg in pats:
        sols,timed=enum_pattern(asg,cap=400,tlim=120)
        print(f"pattern {asg}: {len(sols)} sols timed={timed}",flush=True)
        FIX=[int(c) for c in asg]
        nsp=0
        for (mix,p3) in sols:
            B=expand(FIX,mix,p3)
            P=pasches(B)
            if len(P)==1:
                nsp+=1; total_single+=1
                s6,inside=P[0]
                opp=switch(B,s6,inside)
                B2=(B-set(inside))|set(opp)
                m=iso(B,B2)
                sigpres = set(sig(x) for x in s6)==set(s6)
                print(f"  SINGLE-PASCH {asg} pasch6={s6} sig-pres={sigpres} twin-iso={'YES' if m else 'NO'}",flush=True)
                if m:
                    twins.append((asg,FIX,mix,p3,s6,inside,opp,m))
        print(f"  -> single-Pasch in {asg}: {nsp}",flush=True)
    print("TOTAL single:",total_single,"twins:",len(twins),"t=",round(time.time()-t0,1))
    json.dump([{"asg":a,"fix":f,"mix":[list(t) for t in m],"p3":[list(t) for t in p],"s6":list(s),"inside":[list(t) for t in ins],"opp":[list(t) for t in o],"iso":iso_} for (a,f,m,p,s,ins,o,iso_) in twins],open("twins.json","w"),indent=1)
