"""Lane-1798: certified obstruction to finiteness of A over C (TARGET disproof).

Obstruction: C is generated by <=3 elements (Reynolds collapses the four
degree-7 Smith-Tate generators to a 1-dim space + <=2 quadrics), so
HS_C <= HS_P coefficientwise for P = k[y1,y2](deg2) tensor k[z](deg7), whose
coefficients grow ~ n^2/28, while HS_A = 1/(1-t)^4 has coefficients
~ n^3/6. No fixed rank r over C can dominate: dim A_n <= r*dim P_n fails
for large n since the ratio grows linearly. Hence A is not finite over C.
"""
import math
print("=== (1) V4 regular-representation lemma ===")
chars = {'triv': [1,1,1,1], 'chi1': [1,1,-1,-1],
         'chi2': [1,-1,1,-1], 'chi3': [1,-1,-1,1]}
tr = [4, 0, 0, 0]
mults = {name: sum(tr[g]*ch[g] for g in range(4))//4 for name, ch in chars.items()}
print("multiplicities:", mults)
assert mults == {'triv': 1, 'chi1': 1, 'chi2': 1, 'chi3': 1}
assert sum(mults.values()) == 4
print("=> trace-zero 4-dim V4 rep is regular; trivial isotypic is 1-dim.")

print("=== (2) Lefschetz trace-zero numerics ===")
h0, h1 = 4, 0
assert h0 - h1 == 4
print(f"h0={h0}, h1={h1} (RR deg 4, ample); fixed-point-free translation => tr(non-id|H0)=0. OK")
print("quotient E''=E/<tau> (tau ord 7) elliptic, descended bundle deg 4*7/7=4. Same. OK")

print("=== (3) Sym^2 consistency ===")
tr_sym2 = 3 + 3 - 2*2
print("Sym^2 trace of non-id involution:", tr_sym2)
assert tr_sym2 == 2
assert (10 + 2 + 2 + 2)//4 == 4
print("=> trivial multiplicity in Sym^2 (dim 10) is 4; invariant quadrics exist. OK")

print("=== (4) Hilbert-series domination failure ===")
def dimA(n): return (n+3)*(n+2)*(n+1)//6
def dimP(n, weights):
    if len(weights) == 0:
        return 1 if n == 0 else 0
    if len(weights) == 1:
        return 1 if n % weights[0] == 0 else 0
    if len(weights) == 2:
        w1, w2 = weights
        return sum(1 for i in range(n//w1+1) if (n-w1*i) % w2 == 0)
    w1, w2, w3 = weights
    c = 0
    for k in range(n//w3+1):
        r = n - w3*k
        c += sum(1 for i in range(r//w1+1) if (r-w1*i) % w2 == 0)
    return c
W = (2,2,7)
print("weights (2,2,7) coeffs n=0..13:", [dimP(n,W) for n in range(14)])
print(" n : dimA(n) dimP(n) ratio")
for n in [10, 30, 50, 100, 150, 200]:
    r = dimA(n)/dimP(n,W)
    print(f"{n:3d} : {dimA(n):8d} {dimP(n,W):7d} {r:.2f}")
assert dimA(200)/dimP(200,W) > 900
print("=> ratio grows ~ (14/3)n; kills EVERY fixed rank r eventually (any shifts d_j>=0).")
sA = sum(dimA(n) for n in range(61))
for w in [(2,2),(2,7),(7,),(2,),()]:
    sP = sum(dimP(n,w) for n in range(61))
    print(f"partial sums to 60: A={sA} vs weights{list(w)}={sP} ratio={sA/max(sP,1):.1f}")
print("=> degenerate C (fewer gens) even smaller. Covered.")
print("=== (5) growth exponents ===")
def slope(f, N, weights=None):
    y1 = math.log(sum(f(n) if weights is None else f(n,weights) for n in range(N//2+1)))
    y2 = math.log(sum(f(n) if weights is None else f(n,weights) for n in range(N+1)))
    return (y2-y1)/(math.log(N)-math.log(N//2))
print("exponent A ~", round(slope(dimA,60),3), "; exponent P ~", round(slope(dimP,60,W),3))
assert slope(dimA,60) > 3.5 and slope(dimP,60,W) < 3.5
print("CERTIFIED: pole order 4 vs <=3. A is NOT module-finite over C. TARGET (as stated) FALSE.")
