#!/usr/bin/env python3
"""Exact and numerical checks for finite-index exponent-lattice formulas."""
from __future__ import annotations

import math
import sympy as sp

q, L, M = sp.symbols("q L M", positive=True)
m, S1, S2 = sp.symbols("m S1 S2")

# Denominator Laurent coefficients for periods qL and qM.
p_m2 = 1 / (q**2 * L * M)
p_m1 = (L + M) / (2 * q * L * M)
p_0 = sp.Rational(1, 4) + M / (12 * L) + L / (12 * M)

# If the residue numerator is m - S1*y + S2*y^2/2 + O(y^3),
# these are the three heat-kernel coefficients.
c2_general = sp.simplify(m * p_m2)
c1_general = sp.simplify(m * p_m1 - S1 * p_m2)
c0_general = sp.simplify(m * p_0 - S1 * p_m1 + S2 * p_m2 / 2 - 1)

assert c2_general == m / (q**2 * L * M)

# Diagonal congruence A == B (mod q): residues (j,j).
diag_S1 = q * (q - 1) * (L + M) / 2
diag_S2 = q * (q - 1) * (2 * q - 1) * (L + M)**2 / 6
subs_diag = {m: q, S1: diag_S1, S2: diag_S2}

diag_c2 = sp.simplify(c2_general.subs(subs_diag))
diag_c1 = sp.simplify(c1_general.subs(subs_diag))
diag_c0 = sp.simplify(c0_general.subs(subs_diag))

assert sp.simplify(diag_c2 - 1 / (q * L * M)) == 0
assert sp.simplify(diag_c1 - (L + M) / (2 * q * L * M)) == 0
assert sp.simplify(
    diag_c0 - (L / (12 * q * M) + M / (12 * q * L) + (q**2 - 12*q + 2) / (12*q))
) == 0

# q=1 reproduces the unrestricted two-generator lattice.
assert sp.simplify(diag_c2.subs(q, 1) - 1 / (L * M)) == 0
assert sp.simplify(diag_c1.subs(q, 1) - (L + M) / (2 * L * M)) == 0
assert sp.simplify(
    diag_c0.subs(q, 1) - (L / (12 * M) + M / (12 * L) - sp.Rational(3, 4))
) == 0


def subgroup_from_generators(q0: int, gens: list[tuple[int, int]]) -> set[tuple[int, int]]:
    """Subgroup of (Z/qZ)^2 generated by gens."""
    H = {(0, 0)}
    changed = True
    while changed:
        changed = False
        for a, b in list(H):
            for u, v in gens:
                w = ((a + u) % q0, (b + v) % q0)
                if w not in H:
                    H.add(w)
                    changed = True
    return H


def moment_coeffs(q0: int, H: set[tuple[int, int]], L0: float, M0: float):
    s1 = sum(i * L0 + j * M0 for i, j in H)
    s2 = sum((i * L0 + j * M0)**2 for i, j in H)
    mm = len(H)
    c2 = mm / (q0*q0*L0*M0)
    c1 = mm*(L0+M0)/(2*q0*L0*M0) - s1/(q0*q0*L0*M0)
    c0 = mm*(0.25 + M0/(12*L0) + L0/(12*M0)) \
        - s1*(L0+M0)/(2*q0*L0*M0) + s2/(2*q0*q0*L0*M0) - 1
    return c2, c1, c0


def axis_period(q0: int, H: set[tuple[int, int]], axis: int) -> int:
    for d in range(1, q0 + 1):
        w = (d % q0, 0) if axis == 0 else (0, d % q0)
        if w in H:
            return d
    raise AssertionError


def heat(q0: int, H: set[tuple[int, int]], L0: float, M0: float, y0: float):
    num = sum(math.exp(-(i*L0 + j*M0)*y0) for i, j in H)
    den = (1.0 - math.exp(-q0*L0*y0)) * (1.0 - math.exp(-q0*M0*y0))
    return num / den - 1.0

# Check the invariant leading coefficient, boundary coefficient, and O(y) heat remainder
# on several finite-index sublattices represented modulo q.
L0, M0 = math.log(2.0), math.log(3.0)
examples = [
    (2, [(1, 1)]),
    (2, [(1, 0)]),
    (3, [(1, 1)]),
    (4, [(1, 2)]),
    (6, [(2, 0), (1, 3)]),
    (8, [(2, 2), (0, 4)]),
]
for q0, gens in examples:
    H = subgroup_from_generators(q0, gens)
    c2, c1, c0 = moment_coeffs(q0, H, L0, M0)
    index = q0*q0 // len(H)
    assert abs(c2 - 1.0/(index*L0*M0)) < 1e-12
    ax = axis_period(q0, H, 0)
    ay = axis_period(q0, H, 1)
    c1_boundary = 1.0/(2*ax*L0) + 1.0/(2*ay*M0)
    assert abs(c1 - c1_boundary) < 1e-12
    scaled = []
    for y0 in (2e-3, 1e-3, 5e-4):
        rem = heat(q0, H, L0, M0, y0) - c2/y0**2 - c1/y0 - c0
        scaled.append(rem/y0)
    assert max(abs(v) for v in scaled) < 20.0
    print(f"q={q0}, index={index}, |H|={len(H)}: c2={c2:.12g}, c1={c1:.12g}, c0={c0:.12g}, rem/y={scaled[-1]:.12g}")

# The moment formulas are independent of the auxiliary period used to represent a fixed lattice.
def residue_set(q0: int, predicate):
    return {(i, j) for i in range(q0) for j in range(q0) if predicate(i, j)}

for predicate in [
    lambda i, j: (i-j) % 2 == 0,
    lambda i, j: j % 2 == 0,
]:
    vals = []
    for q0 in (2, 4, 6, 8):
        H = residue_set(q0, predicate)
        vals.append(moment_coeffs(q0, H, L0, M0))
    for got in vals[1:]:
        assert max(abs(a-b) for a, b in zip(vals[0], got)) < 1e-12

# The exponent monoid generated by (q,0), (0,q), (1,1) is A == B (mod q).
for q0 in range(2, 13):
    generated = set()
    limit = 40
    for aa in range(limit // q0 + 1):
        for bb in range(limit // q0 + 1):
            for cc in range(limit + 1):
                A = q0*aa + cc
                B = q0*bb + cc
                if A <= limit and B <= limit:
                    generated.add((A, B))
    expected = {(A, B) for A in range(limit + 1) for B in range(limit + 1) if (A-B) % q0 == 0}
    assert generated == expected

print("general residue-moment Laurent identities: PASS")
print("finite-index leading and boundary coefficient checks: PASS")
print("auxiliary-period invariance checks: PASS")
print("diagonal collision-family coefficient checks: PASS")
print("finite exponent-monoid identity checks (q=2..12, A,B<=40): PASS")
print("heat-kernel O(y) checks: PASS")
print(f"sympy version: {sp.__version__}")
