"""Search for 3-generated finite idempotent CD counterexample needing Jonsson length >=4.

Plan: random length-5 Jonsson chains (d1..d4) on {0,1,2,3} as basic ops
=> V(A) is CD(5). For each A, enumerate triples a,b,c in A^2 (as pairs),
S = Sg(a,b,c) <= A^2, alpha=Cg(a,c), beta=Cg(a,b), gamma=Cg(b,c) in S,
test (a,c) in (alpha cap beta) o (alpha cap gamma) o (alpha cap beta).
Failure => no Jonsson chain of length <=3 in V(A) => A refutes target
(provided A is 3-generated, idempotent, |A|<=16).
"""
import random, itertools, sys

def gen_chain(n, rng):
    # returns d[1..n-1] as dicts on triples, n=5
    d = {i: {} for i in range(1, n)}
    f1 = {}; f2 = {}; f3 = {}
    for x in range(4):
        for y in range(4):
            if x == y:
                f1[(x,y)] = x; f2[(x,y)] = x; f3[(x,y)] = x
            else:
                f1[(x,y)] = rng.randrange(4); f2[(x,y)] = rng.randrange(4); f3[(x,y)] = rng.randrange(4)
    for x in range(4):
        for y in range(4):
            for z in range(4):
                t = (x,y,z)
                if x == z:
                    for i in d: d[i][t] = x
                elif x == y:  # (x,x,y')
                    d[1][t] = x
                    d[2][t] = f2[(x,z)]
                    d[3][t] = f2[(x,z)]
                    d[4][t] = z
                elif y == z:  # (x,y,y)
                    d[1][t] = f1[(x,y)]
                    d[2][t] = f1[(x,y)]
                    d[3][t] = f3[(x,y)]
                    d[4][t] = f3[(x,y)]
                else:
                    for i in d: d[i][t] = rng.randrange(4)
    return d

def verify_chain(d, n):
    for x in range(4):
        for y in range(4):
            for z in range(4):
                if not (d_ident(d,0,(x,y,z)) == (x if True else None)): pass
    # d0=x, d5=z
    for x in range(4):
        for y in range(4):
            for z in range(4):
                t=(x,y,z)
                v = {0: x, 5: z}
                for i in range(1,5): v[i]=d[i][t]
                # d_i(x,y,x)=x
                if y is not None and x==z:
                    for i in range(1,5):
                        assert v[i]==x, (i,t,v[i])
                # gluing
                # i=0 even on (x,x,y): d0=x, d1=x
                # i=4 even on (x,x,y): d4=y=d5
                # checked by construction; verify equalities:
    for x in range(4):
        for y in range(4):
            assert d[1][(x,x,y)]==x
            assert d[4][(x,x,y)]==y
            assert d[1][(x,y,y)]==d[2][(x,y,y)]
            assert d[2][(x,x,y)]==d[3][(x,x,y)]
            assert d[3][(x,y,y)]==d[4][(x,y,y)]
    return True

def d_ident(d,i,t):
    if i==0: return t[0]
    if i==5: return t[2]
    return d[i][t]

def build_sq(d):
    # elements 0..15, pair (u,v): u*4+v
    D = {}
    for i in range(1,5):
        T = [[[0]*16 for _ in range(16)] for _ in range(16)]
        for p in range(16):
            for q in range(16):
                for r in range(16):
                    u = d[i][(p//4,q//4,r//4)]*4 + d[i][(p%4,q%4,r%4)]
                    T[p][q][r]=u
        D[i]=T
    return D

def sg_sq(D, gens):
    S=set(gens); changed=True
    while changed:
        changed=False
        L=list(S)
        for i in range(1,5):
            T=D[i]
            for p in L:
                for q in L:
                    for r in L:
                        u=T[p][q][r]
                        if u not in S:
                            S.add(u); changed=True
        # note: L stale within round; loop until fixpoint (fine)
    return S

def sg_A(d, gens):
    S=set(gens); changed=True
    while changed:
        changed=False
        L=list(S)
        for i in range(1,5):
            for p in L:
                for q in L:
                    for r in L:
                        u=d[i][(p,q,r)]
                        if u not in S: S.add(u); changed=True
    return S

def cg(S, D, a, b):
    # congruence generated by (a,b) on S; S set of ints
    L=sorted(S); idx={v:k for k,v in enumerate(L)}; m=len(L)
    parent=list(range(m))
    def find(x):
        while parent[x]!=x: parent[x]=parent[parent[x]]; x=parent[x]
        return x
    def union(x,y):
        rx,ry=find(x),find(y)
        if rx!=ry: parent[rx]=ry
    union(idx[a],idx[b])
    changed=True
    while changed:
        changed=False
        # compatibility: for op, triples componentwise ~ => results ~
        # snapshot classes
        cls=[find(k) for k in range(m)]
        for i in range(1,5):
            T=D[i]
            for p in L:
                for q in L:
                    for r in L:
                        for pp in L:
                            # only need pairs where p~pp etc? full check below
                            pass
            # iterate over all pairs of triples with componentwise related
            for p1 in L:
                for p2 in L:
                    if find(idx[p1])!=find(idx[p2]): continue
                    for q1 in L:
                        for q2 in L:
                            if find(idx[q1])!=find(idx[q2]): continue
                            for r1 in L:
                                for r2 in L:
                                    if find(idx[r1])!=find(idx[r2]): continue
                                    u1=T[p1][q1][r1]; v1=T[p2][q2][r2]
                                    if u1 in idx and v1 in idx:
                                        if find(idx[u1])!=find(idx[v1]):
                                            union(idx[u1],idx[v1]); changed=True
        # check fixpoint of unions
        # loop again if changed
    # build relation matrix
    rel=[[False]*16 for _ in range(16)]
    for v in L:
        for w in L:
            if find(idx[v])==find(idx[w]): rel[v][w]=True
    return rel

def find_violation(d, D, limit_triples=None):
    els=list(range(16))
    count=0
    for a in els:
        for b in els:
            for c in els:
                S=sg_sq(D,[a,b,c])
                if len(S)<2: continue
                if a==c: continue
                al=cg(S,D,a,c); be=cg(S,D,a,b); ga=cg(S,D,b,c)
                # intersections
                # check exists p,q in S: (a,p) in al&be, (p,q) in al&ga, (q,c) in al&be
                ok=False
                for p in S:
                    if not (al[a][p] and be[a][p]): continue
                    for q in S:
                        if not (al[p][q] and ga[p][q]): continue
                        if al[q][c] and be[q][c]:
                            ok=True; break
                    if ok: break
                if not ok:
                    return (a,b,c,S,al,be,ga)
                count+=1
                if limit_triples and count>=limit_triples: return None
    return None

def is_3gen(d):
    # check Sg of some 3 elements = all, and no 2 generate all (minimality)
    import itertools
    three=False; two=False
    for t in itertools.combinations(range(4),3):
        if sg_A(d,list(t))=={0,1,2,3}: three=True; break
    for t in itertools.combinations(range(4),2):
        if sg_A(d,list(t))=={0,1,2,3}: two=True; break
    return three, two

def main():
    seed=int(sys.argv[1]) if len(sys.argv)>1 else 0
    trials=int(sys.argv[2]) if len(sys.argv)>2 else 200
    rng=random.Random(seed)
    for t in range(trials):
        d=gen_chain(5,rng)
        verify_chain(d,5)
        three,two=is_3gen(d)
        if not three: continue
        D=build_sq(d)
        v=find_violation(d,D)
        if v is not None:
            a,b,c,S,al,be,ga=v
            print(f"HIT trial={t} 3gen={three} 2gen={two} S_size={len(S)}")
            print(f"a={a} b={b} c={c} S={sorted(S)}")
            # dump tables
            import json
            out={"trial":t,"two_gen":two,
                 "d":{str(i):{f"{x}{y}{z}":d[i][(x,y,z)] for x in range(4) for y in range(4) for z in range(4)} for i in range(1,5)},
                 "a":a,"b":b,"c":c,"S":sorted(S)}
            with open(f"/srv/scope-research/rounds/2026-09-07-first-light-01/workspaces/research/lane-1093/output/artifacts/hit_{seed}_{t}.json","w") as f:
                json.dump(out,f)
            return
        if t%20==0: print(f"trial {t}: no hit",flush=True)
    print("NO_HIT")

if __name__=="__main__":
    main()
