#!/usr/bin/env python3
import itertools
from collections import Counter

N=3
PERMS=tuple(itertools.permutations(range(N)))
PID={p:i for i,p in enumerate(PERMS)}
P6=6**6

# map label permutation s and preference permutation p to relabeled preference s∘p
PREFMAP=[[0]*6 for _ in range(6)]
for si,s in enumerate(PERMS):
    for pi,p in enumerate(PERMS):
        PREFMAP[si][pi]=PID[tuple(s[x] for x in p)]

# encode/decode base-6 profile of six preference-permutation indices
TUPLES=[None]*P6
for idx in range(P6):
    x=idx; a=[0]*6
    for j in range(5,-1,-1):
        a[j]=x%6; x//=6
    TUPLES[idx]=tuple(a)

def encode(t):
    x=0
    for v in t: x=6*x+v
    return x

def stable_count_idx(idx):
    t=TUPLES[idx]
    men=[PERMS[t[i]] for i in range(3)]
    women=[PERMS[t[3+i]] for i in range(3)]
    mr=[[0]*3 for _ in range(3)]; wr=[[0]*3 for _ in range(3)]
    for m in range(3):
        for r,w in enumerate(men[m]): mr[m][w]=r
    for w in range(3):
        for r,m in enumerate(women[w]): wr[w][m]=r
    c=0
    for match in PERMS:
        inv=[0]*3
        for m,w in enumerate(match): inv[w]=m
        ok=True
        for m in range(3):
            for w in range(3):
                if match[m]!=w and mr[m][w]<mr[m][match[m]] and wr[w][m]<wr[w][inv[w]]:
                    ok=False; break
            if not ok: break
        c += ok
    return c

STABLE=[stable_count_idx(i) for i in range(P6)]

# Group action. sm,sw are permutation indices. swap exchanges the two sides first.
def act(idx, smi, swi, swap=False):
    t=TUPLES[idx]
    if not swap:
        M=t[:3]; W=t[3:]
    else:
        M=t[3:]; W=t[:3]
    sm=PERMS[smi]; sw=PERMS[swi]
    out=[0]*6
    for old in range(3):
        out[sm[old]]=PREFMAP[swi][M[old]]
    for old in range(3):
        out[3+sw[old]]=PREFMAP[smi][W[old]]
    return encode(out)

GROUP=[(smi,swi,swap) for smi in range(6) for swi in range(6) for swap in (False,True)]
assert len(GROUP)==72

# Route A: orbit partition from five generators, not all 72 elements.
# S3 is generated by transposition (01) and cycle (012).
trans=PID[(1,0,2)]; cyc=PID[(1,2,0)]; ident=PID[(0,1,2)]
GENERATORS=[(trans,ident,False),(cyc,ident,False),(ident,trans,False),(ident,cyc,False),(ident,ident,True)]
parent=list(range(P6)); size=[1]*P6

def find(x):
    while parent[x]!=x:
        parent[x]=parent[parent[x]]; x=parent[x]
    return x

def union(a,b):
    ra,rb=find(a),find(b)
    if ra==rb:return
    if size[ra]<size[rb]: ra,rb=rb,ra
    parent[rb]=ra; size[ra]+=size[rb]

for g in GENERATORS:
    for i in range(P6):
        union(i,act(i,*g))

roots={}
for i in range(P6):
    r=find(i); roots.setdefault(r,[]).append(i)
class_dist=Counter(); orbit_dist=Counter()
for members in roots.values():
    ks={STABLE[i] for i in members}; assert len(ks)==1
    k=next(iter(ks)); s=len(members)
    class_dist[k]+=1; orbit_dist[(k,s)]+=1

# Route B: Burnside independently counts fixed profiles by stable-count stratum.
fixed_by_k=Counter()
for g in GROUP:
    for i in range(P6):
        if act(i,*g)==i:
            fixed_by_k[STABLE[i]] += 1
burnside={k: fixed_by_k[k]//72 for k in fixed_by_k}
assert all(fixed_by_k[k]%72==0 for k in fixed_by_k)

raw=Counter(STABLE)
EXPECTED_RAW={1:34080,2:11484,3:1092}
EXPECTED_CLASSES={1:491,2:161,3:17}
EXPECTED_ORBITS={(1,12):2,(1,36):32,(1,72):457,(2,12):1,(2,24):1,(2,72):159,(3,12):1,(3,36):2,(3,72):14}
assert dict(raw)==EXPECTED_RAW
assert dict(class_dist)==EXPECTED_CLASSES
assert burnside==EXPECTED_CLASSES
assert dict(orbit_dist)==EXPECTED_ORBITS
assert len(roots)==669

# Canonical representative of the unique maximally symmetric three-stable class.
maxsym=[]
for members in roots.values():
    if STABLE[members[0]]==3 and len(members)==12:
        maxsym.append(min(members))
assert len(maxsym)==1
rep_tuple=TUPLES[maxsym[0]]
EXPECTED_REP=(0,3,4,3,4,0)
assert rep_tuple==EXPECTED_REP
for k in EXPECTED_CLASSES:
    assert sum(s*c for (kk,s),c in orbit_dist.items() if kk==k)==raw[k]

print('VERIFY_OK')
print('raw_profiles',P6)
print('raw_distribution',dict(sorted(raw.items())))
print('full_symmetry_classes',len(roots))
print('class_distribution',dict(sorted(class_dist.items())))
print('orbit_size_distribution',sorted(orbit_dist.items()))
print('burnside_distribution',dict(sorted(burnside.items())))
print('unique_stabilizer6_three_stable_rep', rep_tuple)
