#!/usr/bin/env python3

def diamond(n, rel, subset):
    out = 0
    for x in range(n):
        for y in range(n):
            if ((rel >> (x*n+y)) & 1) and ((subset >> y) & 1):
                out |= 1 << x
                break
    return out

def marked_condition(n, rel, null_atoms):
    full = (1 << n) - 1

    # The principal ideal generated by null_atoms must be modal.
    if diamond(n, rel, null_atoms) & ~null_atoms:
        return False

    measurable = list(range(1 << n))

    # On a finite Boolean algebra, every countable family has the same
    # intersection as a finite family of distinct measurable sets.
    for family in range(1, 1 << (1 << n)):
        inter = full
        dinter = full
        for i, subset in enumerate(measurable):
            if (family >> i) & 1:
                inter &= subset
                dinter &= diamond(n, rel, subset)
        if (inter & ~null_atoms) == 0 and (dinter & ~null_atoms) != 0:
            return False
    return True

def partial_function_characterization(n, rel, null_atoms):
    for x in range(n):
        if (null_atoms >> x) & 1:
            continue
        successors = [y for y in range(n) if (rel >> (x*n+y)) & 1]

        # Modal ideal closure forbids surviving-to-null arrows.
        if any((null_atoms >> y) & 1 for y in successors):
            return False

        # At most one surviving successor.
        surviving = [y for y in successors if not ((null_atoms >> y) & 1)]
        if len(surviving) > 1:
            return False
    return True

expected_counts = {1: 4, 2: 41, 3: 1176}
for n in range(1, 4):
    count = 0
    for rel in range(1 << (n*n)):
        for null_atoms in range(1 << n):
            direct = marked_condition(n, rel, null_atoms)
            structural = partial_function_characterization(n, rel, null_atoms)
            assert direct == structural, (n, rel, null_atoms, direct, structural)
            count += int(direct)
    assert count == expected_counts[n], (n, count, expected_counts[n])

# Smallest branching obstruction: point 0 reaches both 0 and 1.
n = 2
branching_rel = (1 << (0*n+0)) | (1 << (0*n+1))
assert not marked_condition(n, branching_rel, 0)

# Its complex diamond sends each singleton, and their union, to {0}.
a = 1 << 0
b = 1 << 1
assert diamond(n, branching_rel, a) == a
assert diamond(n, branching_rel, b) == a
assert diamond(n, branching_rel, a | b) == a
assert diamond(n, branching_rel, a & b) == 0
assert (diamond(n, branching_rel, a) & diamond(n, branching_rel, b)) != 0

print("VERIFY_OK")
