#!/usr/bin/env python3
import sympy as s

w=s.symbols('w')
mod=s.Poly(w*w+19,w,domain=s.QQ)
def red(e):
    return s.rem(s.Poly(s.expand(e),w,domain=s.QQ),mod).as_expr()

# Khatri--Rao matrix displayed in Example 4.1.
M=s.Matrix([
 [0,0,0, 2,0,-3],
 [0,0,0, 0,-1,1],
 [0,0,0,-2,3,0],
 [1,0,0, 0,0,0],
 [0,1,0, 0,1,0],
 [0,0,1, 0,0,0],
])
assert M.rank()==5
ker=M.nullspace()[0]
assert s.Matrix(ker*2)==s.Matrix([0,-2,0,3,2,2])
left=M.T.nullspace()[0]
assert list(left)==[1,3,1,0,0,0]

# The conic in the plane coordinates z0,z1,z2 after substituting the
# displayed parametrization of the plane containing Y.
z0,z1,z2,t=s.symbols('z0 z1 z2 t')
Q=9*z0**2-18*z0*z1+18*z0*z2+11*z1**2+z1*z2-28*z2**2
A=s.hessian(Q,(z0,z1,z2))/2
assert A.det()==-s.Rational(5913,4)  # smooth conic
Qt=s.expand(Q.subs({z0:3,z1:2-2*t,z2:2}))
assert Qt==44*t**2+16*t+17
assert s.discriminant(Qt,t)==-2736

# The two points where the row line of the center meets the conic.
def outer(y,z):
    return s.Matrix([y[0]*z[0],y[0]*z[1],y[0]*z[2],
                     y[1]*z[0],y[1]*z[1],y[1]*z[2]])

def branch(eps):
    z=s.Matrix([33,26-3*eps*w,22])
    y=s.Matrix([-22*eps*w,57-4*eps*w])
    # They lie on the conic modulo w^2+19.
    assert red(Q.subs({z0:z[0],z1:z[1],z2:z[2]}))==0
    P=outer(y,z)
    q=(M*P).applyfunc(red)
    # Projective image is q0=[0:17:-51:-66:-77:-44].
    q0=s.Matrix([0,17,-51,-66,-77,-44])
    # all 2x2 minors of [q,q0] vanish
    QQ=s.Matrix.hstack(q,q0)
    for i in range(6):
        for j in range(i+1,6):
            assert red(QQ.extract([i,j],[0,1]).det())==0

    # Tangent direction in P1 and tangent direction on the conic.
    dy=s.Matrix([-y[1],y[0]])
    grad=s.Matrix([s.diff(Q,zv) for zv in (z0,z1,z2)])
    g=grad.subs({z0:z[0],z1:z[1],z2:z[2]}).applyfunc(red)
    dz=s.Matrix([g[1],-g[0],0])
    assert red((g.T*dz)[0])==0
    v=(M*outer(dy,z)).applyfunc(red)
    r=(M*outer(y,dz)).applyfunc(red)
    T=s.Matrix.hstack(q,v,r)
    d3=red(T.extract([0,1,3],[0,1,2]).det())
    if eps==1:
        assert d3==294060492*(24*w+329)
    else:
        assert d3==-294060492*(24*w-329)
    return q,v,r

Bp=branch(1)
Bm=branch(-1)
# The two projective tangent planes are transverse in H=P4: vector spans
# generated by the common q plus two tangent directions from each branch
# have full vector rank five.
C=s.Matrix.hstack(Bp[0],Bp[1],Bp[2],Bm[1],Bm[2])
d5=red(C.extract([0,1,3,4,5],[0,1,2,3,4]).det())
assert d5==2357771608607690880*w

# Singular-scheme length of the analytic model: for the transverse union
# V(us,ut,vs,vt) in A4, the dimension-2 Jacobian/Fitting ideal is m^2.
u,v,ss,tt=s.symbols('u v ss tt')
fs=[u*ss,u*tt,v*ss,v*tt]
J=s.Matrix([[s.diff(f,x) for x in (u,v,ss,tt)] for f in fs])
mins=[]
for rr in s.utilities.iterables.combinations(range(4),2):
    for cc in s.utilities.iterables.combinations(range(4),2):
        mins.append(s.expand(J.extract(rr,cc).det()))
G=s.groebner(fs+mins,u,v,ss,tt,order='lex')
expected={u**2,u*v,u*ss,u*tt,v**2,v*ss,v*tt,ss**2,ss*tt,tt**2}
got={s.expand(p.as_expr()) for p in G.polys}
assert got==expected
# Quotient by m^2 has basis 1,u,v,ss,tt, hence length 5.
print('CENTER=[0:-2:0:3:2:2]')
print('TARGET_POINT=[0:17:-51:-66:-77:-44]')
print('CONIC_RESTRICTION=44*t^2+16*t+17 DISCRIMINANT=-2736')
print('TRANSVERSE_TANGENT_MINOR=2357771608607690880*w, w^2=-19')
print('SINGULAR_SCHEME_BASIS=1,u,v,s,t LENGTH=5')
print('VERIFY_OK')
