# k=1 scores best but still far from full. So single-theta Kummer over K1 rarely Galois.
# ----------------------------------------------------------------------------
# STRATEGIC RETHINK. The literature (Vogel; Morishita; Amano) constructs the mod-3 Heisenberg extension NOT as
# K1(cuberoot Th)/K directly Galois, but notes R/K is Galois because theta can be chosen in a SUBFIELD-respecting
# way... Actually, let me recall Vogel's thesis "On the Galois group of the Redei extension" / Amano Thm:
# The field R = K(pi1^{1/3}, pi2^{1/3}, theta^{1/3})?? i.e. adjoin BOTH cube roots AND theta root: degree 27 with
# Heisenberg group. R/K Galois is then more plausible: R = K1(theta^{1/3}) with theta in K1 — adjoining theta root
# AND pi2 root? Since pi2^{1/3}: from N(Th)=pi2, pi2^{1/3}=Th^{1/3}sigma(Th)^{1/3}sigma^2(Th)^{1/3} requires the OTHER
# roots. So define R = K1(Th^{1/3}, sigma(Th)^{1/3}): then R contains pi2^{1/3} (product) and is sigma-stable
# (sigma permutes generators) => R/K GALOIS. Degree: [R:K1] up to 9; [R:K] up to 27. Heisenberg iff exactly 27
# with right group. THIS is the natural construction! The "defining equations" = the two cubics.
# Then: ramification: R/K1 ramified at primes dividing Th, sigma(Th) [and lambda]. For R/K ramified exactly at
# pi1,pi2: need (Th) = P^a * (cube) with P|pi2... Since N(Th)=pi2 (prime!), (Th) as K1-ideal has norm pi2, so
# (Th) = Q (single prime above pi2, degree 1) — automatically! Similarly (sigma Th)=sigma(Q). So R/K1 ramified
# exactly at Q, sigma(Q), sigma^2(Q) (primes above pi2) + K1-ramified primes (above pi1, lambda). Over K:
# ramification exactly at pi1, pi2, (lambda?). Good — matches "ramification exactly at pi1,pi2" up to lambda.
# Degree check: [R:K1]=9 iff Th, sigma(Th) independent mod cubes (neither a cube, ratio not a cube). Our local
# tests show Th non-cube etc. Then [R:K]=27 automatically (K1/K degree 3, R/K1 degree 9, R/K Galois).
# TRIPLE SYMBOL: Frobenius of pi3 in Gal(R/K): pi3 splits in K1 (3 primes P_i); in R, each P_i: residue degree
# determined by whether Th, sigma(Th) are cubes mod P_i — the pair of chars gives element of C3^2 = Gal(R/K1);
# plus action... the triple symbol [pi1,pi2,pi3] = the commutator-pairing value: specifically the Frobenius
# projected to the CENTER of Heisenberg group. Center corresponds to... K1 contains... the fixed field of center
# is K(pi1^{1/3},pi2^{1/3}) (degree 9, abelian C3xC3 over K). So: pi3's Frobenius in Gal(K(pi1^{1/3},pi2^{1/3})/K)
# is trivial (since pairwise symbols 1 => pi3 splits completely there). The remaining data = central element =
# computed from Th(r) chars COMBINED for the specific prime: the value is Th(r1)*sigma... precisely the Massey
# product. Concretely: with P|r1 chosen, Frob_P acts on u=Th^{1/3} by zeta^{a} (a=char of Th(r1)), on
# v=sigma(Th)^{1/3} by zeta^{b}. The commutator [Frob_P lifted, sigma] = ... The triple symbol = a*?+b*? combo.
# The STANDARD formula (Morishita, Amano): [pi1,pi2,pi3]_3 = (theta(r1)/pi3)_3 for a SUITABLE choice of prime
# r1|pi3 in K1 — but which? The one satisfying r1 ≡ ...? Hmm, in Redei's Q-case, the symbol uses the prime above
# p3 split appropriately. For the Heisenberg case, I recall: [p1,p2,p3] = Artin of (a prime above p3 in K1 chosen
# via the decomposition in the DIHEDRAL subfield?)...
# PRAGMATIC RESOLUTION: compute the FULL Galois action numerically: R as number field is degree 27 — too big for
# hand-rolled arithmetic? Actually K1 elements are triples over K (dim 6 over Q); R elements = pairs over K1
# (dim 54 over Q). Frobenius computation = factoring mod pi3: R mod (prime above pi3) = F_{N3}[t]/(t^3-pi1, u^3-Th,
# v^3-sTh) — finite ring arithmetic, CHARACTERS computable. The Galois group acts; Frobenius element identified by
# its action on generators: Frob(x)=x^{N3} for residue fields. Since pi3 splits completely in K1? NO — pi3 splits
# into 3 primes each of residue degree 1 (residue field F_{N3}). Over each, adjunction: u^3=Th(r_i): splits iff
# Th(r_i) is a cube. So decomposition group at P_i maps to Gal(R/K1) via the two chars (a_i, b_i). The triple
# symbol should be a specific COMBINATION. The center of Gal(R/K): R^{center-fixed}... center fixes K1? No:
# center < Gal(R/K) with quotient Gal(K(mu... Let me just compute: Gal(R/K) generated by sigma (order 3, lifts
# t->wt), tau1: u->w u, tau2: v->w v. Relations: sigma tau1 sigma^{-1} = tau2, sigma tau2 sigma^{-1} = tau1^{-1}tau2^{-1}
# (since sigma(u)^3=sigma(Th), sigma(u)=v*... up to cube root of unity factors). Center = <tau1 tau2 sigma... >?
# Order-27 Heisenberg (exponent 3): center = commutator subgroup = <[sigma,tau1]> = tau1^{-1}tau2. So center
# corresponds to acting u->w^{-1}u, v->wv simultaneously?? Hmm: [sigma,tau1] = sigma tau1 sigma^{-1} tau1^{-1} =
# tau2 tau1^{-1}. Center element c=tau2 tau1^{-1}: u->w^{-1}u, v->+1... v->w v. So central char = b-a where a,b are
# the tau1,tau2 exponents of Frobenius! At prime P_i: frob acts u->u^{N3}=zeta^{a_i} u, v->zeta^{b_i} v where
# a_i=(Th(r_i)/pi3), b_i=(sigmaTh(r_i)/pi3). Central component = b_i - a_i. For well-definedness need b_i-a_i
# independent of i. CHECK THIS on data!
from eisen import *
import math
def ksigma(A): return (A[0],emul(OMEGA,A[1]),emul(W2,A[2]))
def transversal(pi):
    N=enorm(pi); q=int(math.isqrt(N))
    if q*q==N: return [(a,b) for a in range(q) for b in range(q)]
    else: return [(a,0) for a in range(N)]
def cube_roots_mod(m,pi):
    mm=emod(m,pi); return [c for c in transversal(pi) if econg(epowmod(c,3,pi),mm,pi)]
def evalK1(Th,r,pi):
    return emod(eadd(eadd(Th[0],emul(Th[1],r)),emul(Th[2],emul(r,r))),pi)
def charval(v,pi):
    if edivides(pi,v): return '0'
    return cubic_symbol(v,pi)
pi1=(1,3); Th=((-6,-6),(-6,-3),(-3,1)); STh=ksigma(Th)
print("Th=",list(map(e2str,Th)),"sigmaTh=",list(map(e2str,STh)))
primes=enum_primary_primes(2000)
for pi,N in primes:
    if eeq(pi,pi1) or eeq(pi,(1,6)): continue
    if cubic_symbol(pi1,pi)!=0 or cubic_symbol((1,6),pi)!=0: continue
    if N>700: continue
    rts=cube_roots_mod(pi1,pi)
    if len(rts)!=3: continue
    row=[]
    for r in rts:
        a=charval(evalK1(Th,r,pi),pi); b=charval(evalK1(STh,r,pi),pi)
        if a=='0' or b=='0': row.append((e2str(r),a,b,'-'))
        else: row.append((e2str(r),a,b,(b-a)%3))
    print(e2str(pi),N,row)
