"""Full pipeline: BFS classes + Brandt matrices for disc 109. Uses PARI qfminim for fingerprints."""
from itertools import product
import numpy as np, sys, json
sys.path.insert(0,'output/artifacts')
from hnf import hnf_full_rank
from brandt_main import RM, GENS_O, toL, toO, mulL
from brandt_step import matrix_units, coords_map
from cypari2 import Pari
pari = Pari()

QMAT = np.diag([1.0,2.0,109.0,218.0])
def rows_O_to_L(B):
    return np.array([[r[0],r[1]+r[3]/2,r[2],r[3]/2] for r in B])

def fp_of_ideal(B, nkeep=14, perscale=26):
    """Fingerprint: sorted normalized short norms via PARI qfminim. B: HNF rows in O-coords."""
    Bm = np.array(B, dtype=float)
    idx = round(abs(np.linalg.det(Bm)))
    NJ = int(round(np.sqrt(idx))); assert NJ*NJ == idx
    BL = rows_O_to_L(B)
    G = BL @ QMAT @ BL.T
    # scale to integers: entries are multiples of 1/4 (halves from v)
    S = 4
    M = np.round(G*S).astype(int)
    bound = S*NJ*perscale
    P = pari('qfminim([%s], %s)' % (';'.join(','.join(str(x) for x in row) for row in M.tolist()), int(bound)))
    n = int(pari('Pq := %s; 0' % 'x') if False else P[1])
    V = np.array([list(map(int, list(pari('P[3][,%d]' % (k+1))))) for k in range(n)], dtype=float).T
    Marr = np.array(M.tolist(), dtype=float)
    vals = sorted(round(float(V[:,k] @ Marr @ V[:,k])/(S*NJ), 6) for k in range(n))
    return tuple(vals[:nkeep]), NJ

print("fp(O)=", fp_of_ideal(np.eye(4, dtype=int)), flush=True)

def subideals_of_rep(Brep, l, units_cache):
    """All right subideals J'⊂I (I given by HNF O-coords rows) with [I:J']=l^2. Returns HNF list."""
    units = units_cache[l]
    mulm_dict = {}
    def mulm(a,b):
        a0,a1,a2,a3=a; b0,b1,b2,b3=b
        return ((a0*b0-2*a1*b1-109*a2*b2-218*a3*b3)%l,(a0*b1+a1*b0+109*a2*b3-109*a3*b2)%l,
                (a0*b2+a2*b0-2*a1*b3+2*a3*b1)%l,(a0*b3+a3*b0+a1*b2-a2*b1)%l)
    e11,e12,e21,e22 = units
    Bm = np.array(Brep, dtype=float); Bi = np.linalg.inv(Bm)
    # V = I/lI: represent as F_l^4 via coords c (O-coords mod l); lattice membership via Bi.
    # Right action of g (O-coords) on V: c ↦ c @ RM[g] mod l. Matrix units as O-coord vectors mod l:
    # e_ij are L-coords mod l; convert: c=(x0,x1-x3,x2,2x3).
    def x2c(x): return (x[0]%l,(x[1]-x[3])%l,x[2]%l,(2*x[3])%l)
    E = {k: np.array([[int(v)%l for v in (np.array(x2c(e))@np.array(RM[g]) if False else 0)] for e in [(1,0,0,0)]]) for k,g in []}
    # Right action matrices on V (4x4 over F_l): R_g[c] = c @ RM[g]; for e's use L-coord mult converted.
    # Get action of L-vector t on V: c ↦ x2c(mulm(c2x(c), t)) with c2x(c)=(c0, c1+c3/2, c2, c3/2), 1/2=(l+1)//2 mod l for odd l.
    inv2 = (l+1)//2
    def c2x(c): return (c[0]%l,(c[1]+inv2*c[3])%l,c[2]%l,(inv2*c[3])%l)
    def act_L(c, t):
        return x2c(mulm(c2x(c), t))
    # action matrices (rows = images of basis)
    def actmat(t):
        return np.array([act_L(list(e),t) for e in [(1,0,0,0),(0,1,0,0),(0,0,1,0),(0,0,0,1)]], dtype=int)%l
    A11, A12, A21, A22 = actmat(e11), actmat(e12), actmat(e21), actmat(e22)
    # Ve11 = {c : c@A11 == c}; basis:
    from itertools import product as pr
    Ve11 = [c for c in pr(range(l),repeat=4) if tuple(int(v)%l for v in (np.array(c)@A11%l))==c]
    assert len(Ve11)==l**2, (l, len(Ve11))
    # pick basis a1,a2 of Ve11 (2-dim over F_l): find 2 independent
    def indep(pts):
        basis=[]
        for p in pts:
            if all(v==0 for v in p): continue
            M = np.array(basis+[list(p)],dtype=float)
            if np.linalg.matrix_rank(M)>len(basis): basis.append(list(p))
            if len(basis)==2: break
        return basis
    ab = indep(Ve11); assert len(ab)==2
    a1,a2 = ab
    # V-basis: a1, a2, a1@A12, a2@A12
    Vb = [a1,a2, [int(v)%l for v in np.array(a1)@A12%l], [int(v)%l for v in np.array(a2)@A12%l]]
    Vbm = np.array(Vb,dtype=float)
    assert abs(round(np.linalg.det(Vbm)))%l!=0, "V basis singular?"
    # neighbor submodules: S⊗span((α,β)): generated (as M2-mod) by w=α a1+β a2: {w, w@A12}; submodule elts: all M2-combos = {s w + t w@A12 ... } no: submodule generated by w: wرداری M2 = span{w@A11=w, w@A12, w@A21=0, w@A22=0} = span{w, w@A12}. So submodule = {s*w + t*(w@A12)}.
    seen=set(); lines=[]
    for u,v in pr(range(l),repeat=2):
        if (u,v)==(0,0): continue
        key=tuple(sorted([((s*u)%l,(s*v)%l) for s in range(l)]))
        if key in seen: continue
        seen.add(key); lines.append((u,v))
    assert len(lines)==l+1
    out=[]
    for (u,v) in lines:
        w = [(u*a1[i]+v*a2[i])%l for i in range(4)]
        w2 = [int(x)%l for x in np.array(w)@A12%l]
        Sub = set()
        for s in range(l):
            for t in range(l):
                Sub.add(tuple((s*w[i]+t*w2[i])%l for i in range(4)))
        assert len(Sub)==l**2
        # pullback: {x ∈ I : x mod l ∈ Sub}: gens = lifts + l*Brep rows
        gens = [list(p) for p in Sub] + [(l*int(Brep[i][j]) if False else 0) for i in range(4) for j in range(4)]
        gens = [list(p) for p in Sub] + [[int(l*Brep[i][j]) for j in range(4)] for i in range(4)]
        B,d = hnf_full_rank(gens)
        assert d==l**2,(l,(u,v),d)
        out.append(B)
    return out

if __name__=="__main__":
    cache={l: matrix_units(l) for l in [2,3,5,7,11,13]}
    print("units cached", flush=True)
    Js = subideals_of_rep(np.eye(4,dtype=int).tolist(), 3, cache)
    print(f"O has {len(Js)} norm-3 subideals", flush=True)
    for B in Js:
        print("  fp=", fp_of_ideal(np.array(B))[:1], flush=True)
